UI: Add Back Button To Wallet Creation
tallycash/extension pull request #1018
Opened 2022-02-23 03:32 UTC by dills122

# Issue
During initial setup, importing wallet views had a back button that would navigate the user to the `Add Wallet` view, but the `Create Password` view during wallet creation did not have this setup.

# Fix
Add a back button that is in line with the look of the `Add Wallet` and other setup views.

2022-02-24 15:07 UTC, Shadowfiend requested changes
Thanks for the contribution! Small note below, and I want to give it a test drive and make sure no unexpected state ends up in the system, but this seems like a great little UX addition :)

2022-02-25 01:24 UTC, dills122 commented on ui/components/Keyring/KeyringSetPassword.tsx
> +          }
Got this updated, combined the two rulesets.

2022-02-25 01:27 UTC, dills122 commented
No problem! Hoping to try make it a more regular thing and get more involved with the project.

Really digging this project!

2022-02-28 13:26 UTC, cairomassimo approved these changes
Looks good!

2022-02-28 14:56 UTC, merged

2022-03-01 08:36 UTC, cairomassimo commented
Thanks @Shadowfiend for merging! I was waiting for CI then forgot to do it (and to enable auto-merge).