Fix swap approval stuck in the "Waiting for approval transaction state"
tallycash/extension pull request #1041
Opened 2022-02-25 13:04 UTC by cairomassimo

Fixes #983.

2022-03-01 08:49 UTC, cairomassimo commented
Reminder: let's merge this regardless of the ideal UX design, which we can do later. It's a bug fix (and quite a critical one, there is no workaround for users besides removing and re-installing the extension) and it's impeding testing other improvements for Swaps.

2022-03-02 18:27 UTC, wojciech-turek reviewed
It feels hacky but it works, one small non-blocking comment.

Because I feel this is hacky I'd love another set of eyes on this one.

2022-03-08 14:19 UTC, greg-nagy requested changes
I know this is a really big pain point and agree that this needs to be fixed! 
This fix is an ingenious and I like it a lot.

Blocker: But right now it ties together the windows opened by the dApps and the extension popup window and if any of those are closed rejects all the transaction. I think this needs to be fixed before this change can be merged otherwise we will have really disturbing race conditions on our hand. 

Maybe blocker: not sure if loosing txs because of a window close is an acceptable UX even for a short term, but I would like to lean on others for this decision.

Nonblocker: I would prefer to lean onto the `webext-redux` lib which has this same functionality built in. Wouldn't block on this though. Left some notes on possible integration ideas, but I am open to any other idea.

2022-03-08 14:19 UTC, greg-nagy commented on background/main.ts
> +  private connectPopupMonitor() {
We have the very same functionality implemented in a more robust way in the `webext-redux`. I would prefer to lean onto that solution, even if we need to fork the package — it's a long time coming anyway.

This current solution would cause race conditions with dApps I think. e.g 

A dApp requires a signature, I open the extension and close it, and by the time I want to sign the transaction from the dapp it has already been rejected. Might not be the most common thing, that's true but it feels that it's a dangerous territory.

2022-03-08 16:49 UTC, greg-nagy commented
@cairomassimo the "reject all the pending tx on popup close" behavior is good to go. If you can fix the implementation to reject only on popup close then this PR is ready to go I think.

2022-03-09 08:10 UTC, cairomassimo commented
Thanks @wojciech-turek and @greg-nagy for all the comments on this. This was meant as a quick fix, and the behavior is not ideal. But to get a better UX we need to work much more (e.g. changing the internal state to handle more than one transactions in parallel, one per popup window, and more). I don't think it's worth doing it in this PR.

My understanding is that, even for internal transactions, we already "reject" them when the extension popup is closed, e.g. by clicking outside (internally they are not rejected, they are left as pending - but this has no user-facing consequences). That's why I still think it's worth merging this as is. I will work more on improving transaction signing anyway. Hopefully this will become obsolete/unnecessary at some point, regardless whether we merge it or not :)

2022-03-09 08:13 UTC, cairomassimo commented on background/redux-slices/0x-swap.ts
>  export const { setFinalSwapQuote, clearSwapQuote } = swapSlice.actions
Fixed!

2022-03-09 08:30 UTC, greg-nagy approved these changes
I am unconfortable merging this solution based on the "it works will come up with a proper fix later" argument because these confusing details are the ones that tend to stick in the codebase for the longest time. 

But on the other hand given the timing, the lack of alternatives for the problem let's 🚢

2022-03-09 08:32 UTC, merged