Assistive assets: Abstract asset helpers for easier multi-network handling
tallycash/extension pull request #1045
Opened 2022-02-25 22:46 UTC by Shadowfiend

Draft until #1040 and #1039 both land and this is rebased onto main.

The primary addition here is `AssetDataHelper`, accessible as
`chainService.assetData.*`. This wraps token metadata, balance, and
transfer lookup. Currently it does all Alchemy-specific calls and
only tries to fall back for token metadata, but it provides the
foundation for non-Alchemy fallbacks for networks that may not have
Alchemy-specific calls or support.

2022-03-01 11:33 UTC, cairomassimo requested changes
Some valueable code improvements that should be done before merging this

2022-03-01 11:33 UTC, cairomassimo commented on background/services/chain/asset-data-helper.ts
> +    if (typeof provider === "undefined") {
Non-blocking: I've seen this `typeof x === "undefined"` all around the codebase. Why not `x === undefined` instead? AFAIK it's guaranteed equivalent in strict JS and TypeScript.

2022-03-01 11:33 UTC, cairomassimo commented on background/services/chain/asset-data-helper.ts
> +        async (provider) => {
I would replace this (and the two other instances below) with something like:

```typescript
const provider = await this.getProviderForNetwork(addressOnNetwork.network)
if (provider === undefined) return []
// ... body of the callback
```

It looks much simpler. I don't see enough value in extracting this pattern into a higher-order function.

2022-03-01 11:33 UTC, cairomassimo commented on background/services/chain/asset-data-helper.ts
> +            ) {
Is it possible to invert the logic here, and make the `if` into an early return (outside of `try`)?
We are 7 indentation levels deep.
If not, maybe extracting a method would make it look better.

2022-03-01 11:33 UTC, cairomassimo commented on background/services/chain/asset-data-helper.ts
> +          ) {
Same as above

2022-03-01 11:33 UTC, cairomassimo commented on background/services/chain/asset-data-helper.ts
> +            ) {
Same as above

2022-03-01 11:33 UTC, cairomassimo commented on background/services/chain/asset-data-helper.ts
> +    const provider = this.providerTracker.providerForNetwork(network)
I would replace this with a simpler method `getProviderForNetwork`. See below.

2022-03-01 11:33 UTC, cairomassimo commented on background/services/chain/serial-fallback-provider.ts
> +  async subscribeFullPendingTransactions(
This method is quite long and wide (indentation-wise).
Would benefit from extracting methods from its body and/or a rework.

2022-03-01 11:33 UTC, cairomassimo commented on background/services/chain/serial-fallback-provider.ts
> +      )
E.g., these lines could be extracted into a `private` method `subscribeFullPendingTransactionsAlchemy(...)` (with same signature as `subscribeFullPendingTransactions`)

2022-03-01 11:33 UTC, cairomassimo commented on background/services/chain/serial-fallback-provider.ts
> +      if (errorString.match(/unsupported subscription/i)) {
We are silently ignoring an error if the condition is false.

Perhaps
```typescript
      if (!errorString.match(/unsupported subscription/i)) throw error
```
or at the bare minimum we need a comment saying that we are ignoring errors purposfully.

2022-03-01 11:33 UTC, cairomassimo commented on background/services/chain/serial-fallback-provider.ts
> +      }
This could also be another method, say, `subscribeFullPendingTransactionsStandard`.

2022-03-01 18:16 UTC, Shadowfiend commented on background/services/chain/asset-data-helper.ts
> +    if (typeof provider === "undefined") {
It's only guaranteed by eslint rules, unfortunately. `undefined` can also be overridden globally by setting `window.undefined` in any dependency, so even if the file itself is in strict mode it's not protected from this kind of scope poisoning.

I'm intending on turning on a raft of TypeScript-aware rules that will flag these kinds of conditionals and make sure we're being fully defensive with them sometime after launch.

2022-03-01 18:29 UTC, Shadowfiend commented on background/services/chain/asset-data-helper.ts
> +        async (provider) => {
Strong disagree as to the simplicity here (this seems like a familiarity thing, not a simplicity thing), but it's a pattern that's not really in use in our codebase and should go.

2022-03-01 18:34 UTC, Shadowfiend commented on background/services/chain/serial-fallback-provider.ts
> +      if (errorString.match(/unsupported subscription/i)) {
Yikes, yep. Thanks for flagging.

2022-03-02 09:22 UTC, cairomassimo commented on background/services/chain/asset-data-helper.ts
> +    if (typeof provider === "undefined") {
I just investigated this a bit. It looks like we are safe.

From [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/undefined#description):

> In modern browsers (JavaScript 1.8.5 / Firefox 4+), undefined is a non-configurable, non-writable property, per the ECMAScript 5 specification. (Even when this is not the case, avoid overriding it.)

I tested this:

```javascript
function a() { undefined = 1; return undefined }
function b() { 'use strict'; undefined = 1; return undefined }
```

In the above example, `a` still returns `undefined`, not `1`, while `b` throws `TypeError`. IIUC, in no case ECMAScript 5+ allows global `undefined` to be overwritten.

ES5 has 99.5% browser support (https://caniuse.com/es5), i.e., everything apart from IE8 (which we definitely don't target).

2022-03-10 03:55 UTC, Shadowfiend commented on background/services/chain/asset-data-helper.ts
> +    if (typeof provider === "undefined") {
You're absolutely right! In fact, we had this conversation when we originally introduced the approach. Unfortunately the above fails in the case of a local variable (unless `use strict` is enabled); as a minimal test case:

```javascript
> (function() { let undefined = "blap"; let booyan = "blap"; return booyan === undefined })()
< true
```

On paper this shouldn't be a concern, but given that we're writing relatively sensitive code, we chose to operate with a little extra paranoia around this particular issue.

I haven't been mentioning it across the board because it's a bit excessive to enforce this without a linter rule, and my intent was to switch such a rule on at some point… However, the rule that does this ([`no-undefined`](https://eslint.org/docs/rules/no-undefined)) doesn't support autofix… So I'm thinking it's time to pull back from that stance.

2022-03-10 12:52 UTC, greg-nagy commented on background/services/chain/asset-data-helper.ts
> +    if (typeof provider === "undefined") {
I had this very same question and argument for sooo long. It's so calming to finally have an answer.

2022-03-10 21:19 UTC, Shadowfiend commented on background/services/chain/serial-fallback-provider.ts
> +      }
I went a slightly different path here, since the “standard” path is really the final fallback. The Alchemy path is in its own function and returns `"unsupported"` as a non-error return value if the provider returns an unsupported error, at which point we fall back on this standard approach.

Other Alchemy errors are thrown up as proper errors, and propagated into callers.

2022-03-10 22:04 UTC, Shadowfiend commented
This guy should be ready for another look.

2022-03-11 15:29 UTC, greg-nagy approved these changes
I think these changes are good to 🚢

@Shadowfiend Would you mind shareing a couple of thoughts about what you have in mind for dealchemyfing the codebase?

2022-03-11 15:30 UTC, merged

2022-03-11 19:51 UTC, Shadowfiend commented
> Would you mind shareing a couple of thoughts about what you have in mind for dealchemyfing the codebase?

There are 1-3 RFBs in this… Keep an eye out :)