💅✨  UI polish
tallycash/extension pull request #1110
Opened 2022-03-07 15:12 UTC by henryboldi

Covers a few issues mentioned by @VladUXUI in #1078

2022-03-08 19:48 UTC, greg-nagy requested changes
This PR is a beauty :)

But the send button dissapers on my machine (osx, chrome) becuase of the 0px height of the icon. :(

2022-03-08 19:48 UTC, greg-nagy commented on ui/components/Wallet/WalletAssetListItem.tsx
> +              <Link
This change gives the send icon 0px height and renders it invisible.

2022-03-08 19:48 UTC, greg-nagy commented on ui/components/Wallet/WalletAssetListItem.tsx
> +                className="icon_send_asset"
I think this icon and the span are duplicates.

2022-03-08 20:12 UTC, henryboldi commented on ui/components/Wallet/WalletAssetListItem.tsx
> +                className="icon_send_asset"
Crap I think I missed some changes in my commit on this. Ty for catching it

2022-03-08 20:32 UTC, henryboldi commented on ui/components/Wallet/WalletAssetListItem.tsx
> +              <Link
Should be fixed now :)

2022-03-09 08:19 UTC, greg-nagy approved these changes
I think this PR is good improvmenet so let's 🚀

Our current implementation diverges from the design in the usage of send and swap icons but that's good for a follow up pr

design: 
![CleanShot 2022-03-09 at 09 18 33](https://user-images.githubusercontent.com/7690112/157400716-8a219b39-3686-44c5-9281-dc7892270b59.png)

current implementation:
![CleanShot 2022-03-09 at 09 14 00](https://user-images.githubusercontent.com/7690112/157400655-6fd62d0b-6b7e-40e7-b8b7-fdc70800c9d4.png)

2022-03-09 08:19 UTC, merged