Properly display infinite token approval
tallycash/extension pull request #1133
Opened 2022-03-10 11:11 UTC by jagodarybacka

### What is new
Mark with red color infinite spend limit. User can change spend limit and it will be white. 
Add tooltip to explain spend limit role.

2022-03-10 11:15 UTC, cairomassimo reviewed
Minor code style suggestions

2022-03-10 11:15 UTC, cairomassimo commented on ui/components/SignTransaction/SignTransactionSpendAssetInfoProvider.tsx
> +                    { spend_amount: true },
```suggestion
                    "spend_amount",
```

2022-03-10 11:15 UTC, cairomassimo commented on ui/components/SignTransaction/SignTransactionSpendAssetInfoProvider.tsx
> +                color: #d64045;
We should have a shared color for this, I guess. If not, we should probably add one.

2022-03-10 12:13 UTC, cairomassimo reviewed
Position of tooltip does not match position/layout in the specs (https://www.figma.com/file/q8gfu9XTbYBF07KMnDCtsD/UI---Dark?node-id=7667%3A186256) on my machine.
![Screenshot from 2022-03-10 14-09-33](https://user-images.githubusercontent.com/4115717/157659007-077be9b8-a02f-4f0c-a7ac-85d47effefca.png)

specs

![Screenshot from 2022-03-10 14-11-38](https://user-images.githubusercontent.com/4115717/157659209-2ef69025-f65b-44a3-9d81-9bb800aaf3c3.png)

@VladUXUI it's not clear from the specs how it should be positioned

2022-03-10 12:19 UTC, Shadowfiend commented on ui/components/SignTransaction/SignTransactionSpendAssetInfoProvider.tsx
> +                    has_error: approvalLimitString === null,
Not blocking, but I would mark this as "dangerous" rather than "has error", since an infinite approval isn't strictly an error, we just want to make sure the user is aware it's dangerous.

2022-03-10 15:10 UTC, jagodarybacka commented
Regarding tooltip position - right now we don't have any control over the tooltip position and either I can allow to pass the desired position to the tooltip component or we can think about something smarter. What do you think @cairomassimo ?

2022-03-11 09:45 UTC, greg-nagy requested changes
Good PR, code looks good, agreed on some improvements, leaving this review mostly as a record of that convo.

2022-03-11 09:45 UTC, greg-nagy commented on ui/components/SignTransaction/SignTransactionSpendAssetInfoProvider.tsx
> +              <SharedTooltip>
Please make the tooltip configurable through props and center the position of this tooltip

2022-03-11 13:54 UTC, greg-nagy requested changes
The horizontal positioning is not yet perfect, but I would the center solution is already shipable :)

2022-03-11 13:54 UTC, greg-nagy commented on ui/components/Shared/SharedTooltip.tsx
> +      return width ? `right: -${width / 2 + 8}px;` : ""
The positioning on the center is not perfect but kinda works 
![CleanShot 2022-03-11 at 14 50 00](https://user-images.githubusercontent.com/7690112/157880320-de427ad1-5bde-4b85-a5d7-e99f04c3edec.png)



Left and right are not good

![CleanShot 2022-03-11 at 14 51 01](https://user-images.githubusercontent.com/7690112/157880485-e6dc88de-2c84-471c-9327-3496a2c04a16.png)


![CleanShot 2022-03-11 at 14 49 20](https://user-images.githubusercontent.com/7690112/157880221-b16db177-9b31-432c-b045-a1137ddf5277.png)

2022-03-11 14:04 UTC, jagodarybacka commented on ui/components/Shared/SharedTooltip.tsx
> +      return width ? `right: -${width / 2 + 8}px;` : ""
How would you like right and left to work then?

2022-03-11 14:08 UTC, greg-nagy commented on ui/components/Shared/SharedTooltip.tsx
> +      return width ? `right: -${width / 2 + 8}px;` : ""
I don't think we need them now, so I am ok with simply just removing those and keeping the center as default. 

If you want to fix them properly then I believe the normal behavior would be to close the right side of the pop-up to the right side of the window while showing the whole text so the user can read it.

2022-03-11 14:13 UTC, jagodarybacka commented on ui/components/Shared/SharedTooltip.tsx
> +      return width ? `right: -${width / 2 + 8}px;` : ""
But you can get properly positioned right and left - this tooltip has defined width as this is the simplest way to get center position. If you'll set smaller width in props then it will be fine. It's up to developer and design of given tooltip to decide about width and position I guess.

2022-03-11 14:22 UTC, greg-nagy commented on ui/components/Shared/SharedTooltip.tsx
> +      return width ? `right: -${width / 2 + 8}px;` : ""
I am ok keeping only the center position as a default. 

But if I am presented with an option to position left and right I would not expect the component to move my content out of the visible area. I understand that it can mean that in the end the component is not positioned left or right.

This is "position correctly, not a problem if the content is not visible" vs "make the content visible, and position according to the instruction if there is enough space".

2022-03-11 14:31 UTC, jagodarybacka commented on ui/components/Shared/SharedTooltip.tsx
> +      return width ? `right: -${width / 2 + 8}px;` : ""
ok, so lets keep center position as an only option for now

2022-03-11 14:42 UTC, Shadowfiend commented on ui/components/Shared/SharedTooltip.tsx
> +      return width ? `right: -${width / 2 + 8}px;` : ""
Quick thoughts:
- some sort of clamping is reasonable. 
- any version of this will require judicious application by the dev, I expect, because we can’t predict what constraints a tooltip will exist in. 
- with that in mind and as a future reference, I think it’s fine to land a PR that brings tools to the table and then improve it in follow up work, given the current usage doesn’t hit it.

2022-03-11 14:43 UTC, Shadowfiend commented on ui/components/Shared/SharedTooltip.tsx
> +      return width ? `right: -${width / 2 + 8}px;` : ""
(The above comment shouldn’t change the current path here, I’m really focused on future approached here.)

2022-03-11 14:55 UTC, jagodarybacka commented on ui/components/Shared/SharedTooltip.tsx
> +      return width ? `right: -${width / 2 + 8}px;` : ""
@Shadowfiend I agree, as for now this is the only tooltip we have implemented. As I'm scrolling through figma there will be more tooltips in near future. IMO ideal solution would be probably to left the decision to the tooltip component as where it should be rendered but I think it is strongly out of scope of this task.

2022-03-11 15:34 UTC, greg-nagy approved these changes

2022-03-11 15:36 UTC, greg-nagy commented on ui/components/Shared/SharedTooltip.tsx
> +      return width ? `right: -${width / 2 + 8}px;` : ""
> with that in mind and as a future reference, I think it’s fine to land a PR that brings tools to the table and then improve it in follow up work, given the current usage doesn’t hit it.

I will think about this. I usually have a different approach but this made me think and wonder if I should reevaluate my approach.

2022-03-11 15:36 UTC, merged