Show currency on sign tx page
tallycash/extension pull request #1210
Opened 2022-03-21 11:27 UTC by jagodarybacka

Mentioned by #1101
### What
Show ETH and $ signs on the sign tx page to let user know how much they are going to spend

### Demo
![Screenshot 2022-03-21 at 12 25 57](https://user-images.githubusercontent.com/20949277/159251774-7ae7afed-b0a8-45eb-8cc8-d9e8eedb2f33.png)

2022-03-21 17:18 UTC, 0xDaedalus requested changes

2022-03-21 17:18 UTC, 0xDaedalus commented on ui/components/SignTransaction/SignTransactionSignInfoProvider.tsx
> +              <div className="eth_value">{ethValue} ETH</div>
I think that `enrichAssetAmountWithMainCurrencyValues` should return an `asset` which should have a `symbol` property you can use here instead of hard-coding `ETH`.

2022-03-22 13:34 UTC, greg-nagy requested changes
This works fine for ETH but nothing else. 

I am not sure where you should get the information for the asset. Please try to figure it out, but if it proves to be a pain just reach out and we can figure it out.

![CleanShot 2022-03-22 at 14 32 13](https://user-images.githubusercontent.com/7690112/159493419-3ae0cc53-17af-43d8-8a55-86068bf4d7c6.png)

2022-03-22 14:21 UTC, Shadowfiend commented
Let's 100% not block this merge on that.

Recognizing simple asset transfers and presenting them correctly is something we can put under #374 (we can use existing enrichments for it), and recognizing asset transfers as a general class and swaps as a general class is something we're going to require enrichment for (likely via Blocknative), and that we'll have to make some tough calls on how we interpret and display. Recognizing our own swaps is doable with less work but will probably require some architectural fiddling.

2022-03-22 14:25 UTC, greg-nagy approved these changes
I lean on the opinion from @Shadowfiend 

let's 🚀

2022-03-22 14:31 UTC, merged