Show currency network fee
tallycash/extension pull request #1215
Opened 2022-03-21 15:02 UTC by jagodarybacka

Mentioned by #1101
Resolves #957

### What

* Show dollar value of network fee in the network fee settings button - value is corresponding to the value that user will see after opening settings panel. Value changes after user changes selected option or gas limit. 
![Screenshot 2022-03-21 at 15 58 14](https://user-images.githubusercontent.com/20949277/159288750-723c8f92-b1eb-4593-ad95-8f4f3f864492.png)

* Fix border styles issue - elements of network fee settings panel

2022-03-21 18:02 UTC, 0xDaedalus commented
lgtm!

2022-03-21 18:05 UTC, Shadowfiend commented
Sorry, forced this back to draft as I want to give #1204 an opportunity to land. It cleans up types in such a way that should reduce the code here.

@jagodarybacka feel free to make any adjustments locally and then force-push to replace the merges.

2022-03-21 18:09 UTC, 0xDaedalus requested changes
Visually looks great and handlers small and large dollar values well.  Just a couple of small code comments and we're good to go!

2022-03-21 18:09 UTC, 0xDaedalus commented on ui/components/NetworkFees/FeeSettingsButton.tsx
> +      <FeeSettingsText showDollarValue />
I wonder if we can assume that if a dollar value is available then we should _always_ show it.  As a user of the wallet I think I'd like this a lot but maybe its too broad of a generalization.

This is just me musing and not a blocking comment.

2022-03-21 18:09 UTC, 0xDaedalus commented on ui/components/NetworkFees/FeeSettingsText.tsx
> +  currencyPrize: PricePoint | undefined,
I think we want `currencyPrice` here

2022-03-21 18:09 UTC, 0xDaedalus commented on ui/components/NetworkFees/FeeSettingsText.tsx
> +) => {
lets explicitly type what this function returns

2022-03-21 18:10 UTC, Shadowfiend commented on ui/components/NetworkFees/FeeSettingsButton.tsx
> +      <FeeSettingsText showDollarValue />
I tend to agree we shouldn't hide this behind a prop unless we know for sure we want to hide it in certain circumstances.

Definitely need to QA that layouts are ready for that behavior though.

2022-03-23 11:12 UTC, Shadowfiend approved these changes
Couple of quick morning notes/questions before I actually get started for the day 😅

2022-03-23 11:12 UTC, Shadowfiend commented on ui/components/NetworkFees/FeeSettingsText.tsx
> +        asset: ETH,
Rather than hardcode this, let's use the current price point's first asset. Price points are in a stable order when they reach us here, and this will be more future-proof for other EVM chains that need similar fee logic.

2022-03-23 11:12 UTC, Shadowfiend commented on ui/components/NetworkFees/FeeSettingsButton.tsx
> +      <FeeSettingsText showDollarValue />
Believe this still outstanding. Are we avoiding dollar values in other places for a reason?

2022-03-23 17:58 UTC, Shadowfiend approved these changes
Gave it a test drive, looks amazing. Let's :guitar:

2022-03-23 18:36 UTC, merged