👛 Refactor add wallet page w/ update to new design
tallycash/extension pull request #1222
Opened 2022-03-22 13:37 UTC by henryboldi

This PR includes an updated add wallet page. It makes room for all our options
which now includes Ledger. Plus, this introduces a hierarchy that aligns with
our and user preferences on how to onboard onto Tally. 

I refactored the code a bit to use `accountCreateButtonInfos`, which includes
the sections and info for onboarding button options. The idea is to make this
page more configurable and dry. Also of note, I've added an `unstyled` option
to `SharedButton` so that `SharedButton` can be optionally used purely for
wrapping button content.

To test, navigate the add wallet page from initial onboarding and from the
account switcher menu. Then try each of the add option buttons and make sure
that they send you to the appropriate page.

<img width="320" alt="Add wallet" src="https://user-images.githubusercontent.com/1918798/159493781-aaeb1aff-7f52-4d58-a853-c24e390be41c.png">

Closes #1180

2022-03-23 18:10 UTC, 0xDaedalus requested changes
Test drove and everything worked great!  

Icons do look a bit off on my end though (notice the black circles).

<img width="91" alt="image" src="https://user-images.githubusercontent.com/94649004/159766705-514c9030-38d5-4a72-905e-1eda3dea966e.png">

Also - I think we've chosen to steer away from `.png`'s and go with `.svg`'s for our icons from now on per [this comment](https://github.com/tallycash/extension/pull/1159#discussion_r828839024).

2022-03-23 18:10 UTC, 0xDaedalus commented on ui/pages/Onboarding/OnboardingAddWallet.tsx
> +                        <img
Are we able to use the new `SharedIcon` component here?

2022-03-23 18:37 UTC, henryboldi commented
> Icons do look a bit off on my end though (notice the black circles).

@0xDaedalus, I'm guessing you've got to exit and run `yarn start` again

2022-03-23 18:41 UTC, henryboldi commented on ui/pages/Onboarding/OnboardingAddWallet.tsx
> +                        <img
Confused on what benefit `SharedIcon` provides over using the image tag

2022-03-23 20:56 UTC, VladUXUI commented on ui/pages/Onboarding/OnboardingAddWallet.tsx
>        </div>
It looks like there is a close button? But onboarding doesn't have a close button, since there is nothing to close.
Is this maybe a left over from Add account from the accounts modal?

2022-03-23 20:59 UTC, VladUXUI commented on ui/pages/Onboarding/OnboardingAddWallet.tsx
>        </div>
Just now saw the screenshot. So yes, the onboarding flow shouldn't have a close button, but the screen from account switcher does.

2022-03-23 21:00 UTC, VladUXUI commented
A quick not here (non blocking) is that Ledger has a different icon(new tab 16px) to show that it's going to be opened in a window/tab

2022-03-24 02:20 UTC, Shadowfiend commented on ui/pages/Onboarding/OnboardingAddWallet.tsx
> +                        <img
Consistent rendering across all icon usages, a central place to provide a full catalog of available icons (via types), and a central place to manage changes like file type preference and image rendering choices (e.g. using file variants depending on requested size).

2022-03-24 05:14 UTC, henryboldi commented on ui/pages/Onboarding/OnboardingAddWallet.tsx
> +            </>
100% agree on both of your points being an improvement over the approach I took. I will keep this in mind next time I encounter something like this.

2022-03-24 07:40 UTC, henryboldi commented on ui/pages/Onboarding/OnboardingAddWallet.tsx
> +                        <img
Hmm.. It'll be convoluted to implement here because each of these icons use two colors. And if we extract the icon without the background there're different sizes. I don't believe these icons conform to our normal few sizes —particularly the Ledger and Tally logo symbols. Additionally, these icons are not buttons as the `SharedIcon` component implies. But I like where `SharedIcon` is headed

2022-03-24 08:01 UTC, henryboldi commented on ui/pages/Onboarding/OnboardingAddWallet.tsx
> +            </>
Made an update that adds `AddWalletRow` :)

2022-03-25 15:02 UTC, 0xDaedalus approved these changes
good to go on my end 👍

2022-03-25 16:43 UTC, merged