🏰 Pass IPFS asset icons through gateway
tallycash/extension pull request #1295
Opened 2022-04-05 06:51 UTC by henryboldi

2022-04-05 14:38 UTC, Shadowfiend reviewed
Oof, this is now the third place we're doing gateway stuff. Time to pull it up to a shared lib—let's move https://github.com/tallycash/extension/blob/main/background/services/name/index.ts#L56-L91 up to `background/lib/storage-gateway.ts` or so, and then reuse from here, `NameService`, and… The third place 😏

2022-04-11 01:06 UTC, mhluongo requested changes
Let's parse URLs properly!

2022-04-11 01:06 UTC, mhluongo commented on ui/components/Shared/SharedAssetIcon.tsx
> +  if (logoURL && new URL(logoURL) && logoURL.includes("ipfs")) {
I believe you want

```
if (logoURL && new URL(logoURL) && (new URL(logoURL)).protocol === "ipfs") {
```

... otherwise any URL that happens to include "ipfs", eg `https://example.com/ipfs/tokenImage.jpg`, will get munged here.

2022-04-11 05:03 UTC, henryboldi commented on ui/components/Shared/SharedAssetIcon.tsx
> +  if (logoURL && new URL(logoURL) && logoURL.includes("ipfs")) {
Good point, thank you 🙏
<br/>

I think there should be a colon here though,
`.protocol === "ipfs:"`
> The protocol getter steps are to return this’s URL’s scheme, followed by U+003A (:).

Which was also missing in `function storageGatewayURL`

2022-04-11 10:02 UTC, mhluongo commented on background/lib/storage-gateway.ts
> +    case "ar":
Missed a `:` here!

2022-04-11 15:15 UTC, henryboldi commented on background/lib/storage-gateway.ts
> +    case "ar":
Updated :)

2022-04-11 15:43 UTC, mhluongo commented on ui/components/Shared/SharedAssetIcon.tsx
> +  if (logoURL && new URL(logoURL) && new URL(logoURL).protocol === "ipfs:") {
Okay one more: this should support `"ar:"` as well :sweat_smile:

2022-04-11 16:30 UTC, mhluongo submitted a review, later dismissed
Looking good — merging on conflict resolution + green build.

2022-04-11 16:56 UTC, mhluongo approved these changes
🌄

2022-04-11 16:56 UTC, merged