Signing page improvements
tallycash/extension pull request #1340
Opened 2022-04-20 16:11 UTC by jagodarybacka

### What has been done
* improved `SharedSkeletonLoader` component 
  - made it more configurable via props
  - added animation
  - made it handle showing loaded data internally - based on `isLoaded` prop  
* refactored code around signing data and transaction
  - removed rendering empty React Fragments when transaction details are not yet loaded
  - handled `undefined` values that can happen because of lack of transaction data
  - all this refactoring was to make it possible to display meaningful UI while app is waiting for transaction data and to render `SkeletonLoaders` where it is impossible to display data.
* improved how data sign page is loading 
  - added skeleton loaders to the places that are loading a little bit longer
* improved how transaction sign page is loading - added loading page
  - as we have multiple transaction pages that are really similar to each other we can display loading page while app is loading transaction data. Loading page uses the same layout as transaction pages.

![Screenshot 2022-04-22 at 14 18 43](https://user-images.githubusercontent.com/20949277/164712981-7dcecafc-a367-4ee9-9ad0-7fcf79b3724b.png)

### Testing
1. Sign message testing
Go to uniswap and try to swap USDC - click on `Allow uniswap protocol use your usdc`
2. Sign transaction testing
Try to swap assets or send eth to another address

**Expected:** loading screen should be visible for ~1s, then transaction should be handled as usual

2022-04-22 07:41 UTC, henryboldi commented
On initial checks, this appears to work properly. I know we discussed (offline) expediting the merge of this PR. However, admittedly, "refactored code around signing data" seems essential to QA rigorously. And I don't want to rush in a merge before the more detailed description is written

2022-04-25 15:15 UTC, Shadowfiend commented
> For posterity, would it be helpful to add the motivation and choices around "refactored code around signing data" here?

In general this should be in the commit messages as well! Answering the question “why” is at least as important as answering the question “what” :)

2022-04-26 09:39 UTC, jagodarybacka commented
@henryboldi Thank you! Description and commit messages fixed 🛠

2022-04-27 04:23 UTC, henryboldi requested changes
Merging blocked by a regression to "Read-only accounts cannot sign"'s display.

Anyway, the UX improvement here is awesome! Amazing work!! 😁👑

<hr/>

### Non-blocking thoughts


I think these changes generally imply that if something is `undefined` then it's loading. I don't know if that's a correct assumption for us to make. How would we then handle a timeout or another kind of error? So if `undefined` doesn't mean loading, then we don't need to make all of these props optional, and we don't need to add a bunch of optional chaining. Well, the optional chaining might be unavoidable given that `SharedSkeletonLoader` accepts children.

What do you think of adding something to the effect of an `isLoading` prop with a [discriminating union](https://www.typescriptlang.org/docs/handbook/unions-and-intersections.html#discriminating-unions)? So the data is required unless hypothetically `hasError` is true or `isLoading` is true.

2022-04-27 04:23 UTC, henryboldi commented on ui/pages/SignDataDetailPanel.tsx
> +  if (keys.length > 2)
Why key length over 2?

2022-04-27 10:19 UTC, greg-nagy commented on ui/components/SignTransaction/SignTransactionContainer.tsx
> +            {!signingMethod === null && (
I think `bool === null` will always be false.

2022-04-27 10:24 UTC, greg-nagy commented on ui/components/Shared/SharedSkeletonLoader.tsx
> +  margin?: string
SharedSkeletonLoader.defaultProps might be a good idea here

2022-04-27 10:25 UTC, greg-nagy commented on ui/components/SignData/SignTypedDataInfo.tsx
> +  const { typedData, annotation } = typedDataRequest ?? {
I think this is also a good canidate for defaultProps

2022-04-27 10:41 UTC, greg-nagy commented on ui/pages/SignDataDetailPanel.tsx
> +  if (keys.length > 2)
I think this comes from the deleted logic below from L38
The why is a good question though.

2022-04-27 11:31 UTC, jagodarybacka commented on ui/components/SignTransaction/SignTransactionContainer.tsx
> +            {!signingMethod === null && (
oh no, I missed that `!`... Thank you for noticing

2022-04-27 12:16 UTC, jagodarybacka commented on ui/components/Shared/SharedSkeletonLoader.tsx
> +  margin?: string
@henryboldi in this case I think `width`, `height` and `borderRadius` are important properties of this component, `customStyles` I would say should be just additional styles that can be whatever. 
As I'm thinking about it maybe margin could be included in `customStyles` but I would leave it as it is for now.

2022-04-27 12:36 UTC, jagodarybacka commented on ui/components/SignData/SignTypedDataInfo.tsx
> +  const { typedData, annotation } = typedDataRequest ?? {
Turns out it is not even possible to get `typedDataRequest =  undefined` here 🙃

2022-04-27 13:10 UTC, jagodarybacka commented on ui/pages/SignDataDetailPanel.tsx
> +  if (keys.length > 2)
So it was just moved/refactored - no regression should be visible. Why - as I can see from the commits history it was needed to implement new design of these fields. But I'm not sure if decision based on keys length is the best way to do it.

2022-04-27 13:39 UTC, greg-nagy approved these changes
Loving this feature :) 

Let's 🚀

2022-04-27 13:40 UTC, merged