Rename Addresses [Draft]
tallycash/extension pull request #1345
Opened 2022-04-21 16:41 UTC by 0xDaedalus

Dropping this here for now for comments - description & slight design fixes coming.

2022-04-21 17:52 UTC, henryboldi commented
Alternatively, we can put it behind a feature flag, so the PR can be reviewed + merged without the feature being entirely complete!

2022-04-21 18:05 UTC, mhluongo commented
https://giphy.com/gifs/why-not-both-dont-we-have-3ohfFhG5VDtDTzQv2o

2022-04-21 22:35 UTC, 0xDaedalus commented
> Instead of suffixing [DRAFT] might I suggest you convert this to a draft?

Whoopsie forgot to change the title when converting it out of draft

2022-04-22 12:59 UTC, mhluongo commented
Giving this a look! I think we should try to merge #1347 first as @mul1sh has been working on it for a while, you okay with that @0xDaedalus?

2022-04-22 13:03 UTC, mhluongo commented on ui/components/Shared/SharedInput.tsx
> +          if (e.key === "Enter" && typeof onPressEnter !== "undefined") {
This sort of surprises me — are we using key events across the whole extension?

2022-04-22 13:03 UTC, mhluongo commented on ui/components/Shared/SharedAccountItemSummary.tsx
> +  const dispatch = useDispatch()
Can this be dropped?

2022-04-22 13:08 UTC, mhluongo commented
Hmm, looking more closely, this might not even affect that PR.

2022-04-22 14:40 UTC, Shadowfiend commented on ui/components/Shared/SharedInput.tsx
> +          if (e.key === "Enter" && typeof onPressEnter !== "undefined") {
`onSubmit` and forms is def The Way™ here.

2022-04-22 14:44 UTC, Shadowfiend commented on background/services/preferences/index.ts
> +      this.addressBook[correspondingEntryIndex] = newEntry
Super excited for this, but… Pretty sure this won't survive browser restarts/extension reloads. For this address book to persist I think we need to move it to IndexedDB :grimacing: (I thought this was a nice-to-have, but fairly certain it's a req.)

On the bright side, once it's in IndexedDB you can just do direct lookups using the indices :grin:

2022-04-25 14:09 UTC, 0xDaedalus commented on background/services/preferences/index.ts
> +      this.addressBook[correspondingEntryIndex] = newEntry
The name seems to be persisting for me on extension upgrade, browser close + open, as well as full computer restart

2022-04-26 21:11 UTC, henryboldi requested changes
- [x] Functions as expected and persists
        - Persists on close
        - Persists on restart extension
        - Persists on browser relaunch
- [x] The code has been updated based on the feedback

Excellent work sir! 👏👑

However, I'm seeing this visual bug. It looks like the bottom of the buttons are cut off. I think the spacing just needs to be adjusted.
<img width="320" alt="edit name" src="https://user-images.githubusercontent.com/1918798/165392861-5e093720-2a4a-4b26-a676-e162dd67920f.png">

2022-04-26 22:36 UTC, 0xDaedalus commented
Good catch - tyty.  Updated visual: 
<img width="385" alt="image" src="https://user-images.githubusercontent.com/94649004/165403904-b4c984a1-dcc6-48cd-bb20-7a1ff0768df8.png">

2022-04-26 23:10 UTC, henryboldi approved these changes
👑👑👑

2022-04-26 23:16 UTC, merged