UNS domain resolution support
tallycash/extension pull request #1347
Opened 2022-04-21 19:44 UTC by mul1sh

Replaces #1137

Will fix https://github.com/unstoppabledomains/gitcoin-bounties/issues/3

@mhluongo @Shadowfiend @0xJordi this is the final PR for UNS domain support.

Apologies for opening & closing alot of PR's before 🙁 , the reason for this is that I always get the error shown in the attached picture, when I rebased my changes from the upstream `origin/main` and this crashed tally for me locally. The solution for this has been to always close the PR, delete the old branch and then reopen a new branch and then do a new PR from there.

Since this is more or less complete and upto date with main, I don't expect to do this again. 🙂

2022-04-21 19:46 UTC, mul1sh commented
Btw here is a video showing the functionality, really looking forward to the review  😃 

https://user-images.githubusercontent.com/2150634/164540802-9645f199-947c-4455-9ca9-66ea72ffb44c.mov

2022-04-21 22:00 UTC, mhluongo reviewed
Left a couple comments. Will leave greater review to @greg-nagy @Shadowfiend

2022-04-21 22:00 UTC, mhluongo commented on yarn.lock
> +"@unstoppabledomains/resolution@^7.1.4":
I'm pretty sure you aren't using this in the PR — maybe revert `yarn.lock` outside what `node-fetch` needs? This is a pretty big dependency, and will likely require some tweaks to build and list on Firefox

2022-04-21 22:00 UTC, mhluongo commented on background/services/name/resolvers/uns.ts
> +  const ALCHEMY_API_KEY = process.env.ALCHEMY_KEY
Nice hack, cool that Alchemy has support. We can do "native" resolution down the road.

2022-04-22 02:58 UTC, Shadowfiend requested changes
This is wonderful! And reverse resolving too, yay!

I left a few stylistic notes and a couple of implementation ones. Tried to call out the very few that should block merging the PR. 

Also wondering if we drop this behind a feature flag for testing/release timing purposes cc @greg-nagy @mr-michael .

2022-04-22 02:58 UTC, Shadowfiend commented on background/services/name/resolvers/uns.ts
> +          : { address: undefined }
Thoughts on adjusting this branch to attempt to resolve? Eg:

```suggestion
          : await this.lookUpAddressForName(addressOrNameOnNetwork) ?? { address: undefined }
```

2022-04-22 02:58 UTC, Shadowfiend commented on background/services/name/resolvers/uns.ts
> +      }
Not blocking, but this can be clarified with a `.map` + `.find`; roughly:

```typescript
      const data = (await reverseLookupAddress(address))?.data

      // check if any of the records returned has an NFT picture associated with it
      const avatarUrn = data
        .map((record: { attributes: { records: { [x: string]: string | undefined } } }) => {
          record.attributes.records["social.picture.value"]
        })
        .find(isDefined /* from lib/type-guards */)
```

2022-04-22 02:58 UTC, Shadowfiend commented on background/services/name/resolvers/uns.ts
> +      avatarUrn = avatarUrn.replace("1/erc1155", "eip155:1/erc721")
Believe we should anchor these to the start so we don't replace a valid URN should one appear, plus I think we can use a capturing group to do this once:

```suggestion
      avatarUrn = avatarUrn.replace(/^1\/(erc721| erc1155)/, "eip155:1/$1")
```

Wondering also if we should allow NameService to accept erc1155 strings so we don't have to impersonate erc721 here...

Anyway, only the starting anchor is blocking here I think.

2022-04-22 02:58 UTC, Shadowfiend commented on background/services/name/resolvers/uns.ts
> +      const name = data.data[0]?.attributes?.meta?.domain
Do we want to do a similar find as above where we pull the first defined one in case of weird records?

2022-04-22 08:16 UTC, mul1sh commented on background/package.json
> +    "@types/node-fetch": "^2.6.1",
If I remove it, I get the following error

<img width="711" alt="Screenshot 2022-04-22 at 10 14 11 AM" src="https://user-images.githubusercontent.com/2150634/164647059-8038f2da-708a-4a27-9818-01bc4c558d08.png">

2022-04-22 14:51 UTC, Shadowfiend requested changes
One small note on regex syntax, and I;ll to take this for a test drive today!

Any sample UNS domains that have known avatar info so I can test that piece?

2022-04-22 14:51 UTC, Shadowfiend commented on background/services/name/resolvers/uns.ts
> +      avatarUrn = avatarUrn.replace(/^1\/(erc1155 || erc721)/, "eip155:1/$1")
```suggestion
      avatarUrn = avatarUrn.replace(/^1\/(erc1155|erc721)/, "eip155:1/$1")
```

I believe this is the only way the regex will work :point_up_2: but haven't triple-checked.

2022-04-22 14:55 UTC, mul1sh commented
> One small note on regex syntax, and I;ll to take this for a test drive today!
> 
> Any sample UNS domains that have known avatar info so I can test that piece?

Yes 😃, please try with mine `mulili.crypto`

2022-04-22 14:58 UTC, mul1sh commented
> One small note on regex syntax, and I;ll to take this for a test drive today!
> 
> Any sample UNS domains that have known avatar info so I can test that piece?

Yes 😃, please try with mine `mulili.crypto`

2022-04-22 16:04 UTC, Shadowfiend commented
Avatar resolution seems to work, so does both forward and reverse resolution 💪 

One thing I noticed when adding a read-only address for `brad.crypto` is that we reverse-resolve to a different name in the extension:

<img width="400" alt="Screen Shot 2022-04-22 at 11 57 36" src="https://user-images.githubusercontent.com/8245/164751241-7fe06dc5-740d-4eec-bc30-578f6d27973a.png">

There are some unrelated issues here (e.g., we need to handle longer names better in the UI), but it seems like sorting by id `ASC` over `DESC` when doing the `/owners` lookup will put `brad.crypto` first—I'm not sure what that sort means in practice, is it reasonable to switch to `ASC` or will that break other stuff?

2022-04-22 17:51 UTC, mul1sh commented
> Avatar resolution seems to work, so does both forward and reverse resolution 💪
💯 
> 
> One thing I noticed when adding a read-only address for `brad.crypto` is that we reverse-resolve to a different name in the extension:

Yes this is because the address associated with `brad.crypto` has many other UNS domains associated with it, but as noted below sorting ASC will fix this.
> 
> <img alt="Screen Shot 2022-04-22 at 11 57 36" width="400" src="https://user-images.githubusercontent.com/8245/164751241-7fe06dc5-740d-4eec-bc30-578f6d27973a.png">
> 
> There are some unrelated issues here (e.g., we need to handle longer names better in the UI), but it seems like sorting by id `ASC` over `DESC` when doing the `/owners` lookup will put `brad.crypto` first—I'm not sure what that sort means in practice, is it reasonable to switch to `ASC` or will that break other stuff?

Nope it won't break anything, let me switch to this right now 🙂

2022-04-22 19:35 UTC, Shadowfiend commented
Sweet. I've captured the stacked issues that showed the brad.crypto problem as #1353 and #1354.

I'm going to drop this behind a feature flag and then merge so some of the non-dev folks get a chance to test it out before we go live. Thank you for all the work and the patience! I know this has been in the pipeline for a while (almost a month 😵) and appreciate your sticking with us as we fixed up the architecture a bit to make it work :pray:

2022-04-22 19:43 UTC, mul1sh commented
> Sweet. I've captured the stacked issues that showed the brad.crypto problem as #1353 and #1354.
> 
> I'm going to drop this behind a feature flag and then merge so some of the non-dev folks get a chance to test it out before we go live. Thank you for all the work and the patience! I know this has been in the pipeline for a while (almost a month 😵) and appreciate your sticking with us as we fixed up the architecture a bit to make it work 🙏

No worries, I didn't mind at all. And thank you too for the quick reviews, I much appreciate it. Looking forward to seeing it when it goes live 🙂 . Have a good one.

2022-04-22 19:46 UTC, Shadowfiend approved these changes
Let's go!

2022-04-22 19:50 UTC, merged

2022-05-03 02:17 UTC, SJQuality commented
Retested UNS to make sure it is still working properly on Main Build #2950