😊 The future is optimistic: Refactor ChainService to support Arbitrum and Optimism
tallycash/extension pull request #1355
Opened 2022-04-23 05:42 UTC by mhluongo

Add partial support for Arbitrum and Optimism in `ChainService`, guarded by a feature flag.

To test:

- [ ] Without the feature flag `MULTI_NETWORK` set, confirm account balances and asset transfers still function on mainnet
- [ ] Setting `MULTI_NETWORK` to `true` in `.env`, confirm account balances and transfers still function on mainnet
- [ ] After startup, you should see blocks from Optimism and Arbitrum in IndexedDB

2022-04-27 11:00 UTC, greg-nagy commented on background/services/chain/index.ts
> +import { camelCase } from "lodash"
It just cracked me up how not trivial this is and we need lodash for this 

https://stackoverflow.com/questions/2970525/converting-any-string-into-camel-case

2022-04-27 12:47 UTC, greg-nagy requested changes
It was fun to review this PR and also this is good addition. Ty 

When turning on the feature flag it breaks the gas estimation and everything fails that needs to be signed because of it

![CleanShot 2022-04-27 at 14 33 00](https://user-images.githubusercontent.com/7690112/165519224-5bf22b12-aa16-450e-81e4-80ac5ad2d2d7.png)

And in `tally/chain` > blocks only `Arbitrum One` blocks seem to be stored. (Haven't dug deep enough to find out what is actually going on)

![CleanShot 2022-04-27 at 14 44 22](https://user-images.githubusercontent.com/7690112/165520743-96cc03a1-07bb-45b2-ab20-434d7c069b06.png)


This is behind feature flag, so I would be ok to merge this after recorded the state in an issue (happy to create the issue) but not merging because the test scenarios you have defined are failing. 

Would you like to fix it or merge as is?

2022-04-27 12:47 UTC, greg-nagy commented on background/services/chain/index.ts
> +      ? [ETHEREUM, ARBITRUM_ONE, OPTIMISM]
this is `EVM_MAIN_NETWORKS`

2022-04-27 12:47 UTC, greg-nagy commented on background/services/chain/index.ts
> +        camelCase(network.name),
This camelCase feels weird to me as a way to index the the providers. 
This makes it possible to write `this.providers.arbitrumOne.send()` and when we decide we remove arbitrum one the code will break. 

Put it another way. It feels that we should have a defined list of networks and use properties on them 

I was wondering what would be the simplest way to implement camelCase for this usecase:
`"Arbitrum One".split(" ").map((el,ind) => (ind === 0 ? el[0].toLowerCase() : el[0].toUpperCase()) +  el.slice(1)).join("")`

2022-04-27 12:55 UTC, mhluongo commented on background/services/chain/index.ts
> +import { camelCase } from "lodash"
Yeah, I've done this one by hand a few times... then saw that already had `lodash` in our dep tree... :see_no_evil:

2022-04-27 12:56 UTC, mhluongo commented on background/services/chain/index.ts
> +      ? [ETHEREUM, ARBITRUM_ONE, OPTIMISM]
It is for now! It likely won't be in the future though, as different services might have different support.

2022-04-27 13:01 UTC, mhluongo commented
Hmm, I definitely want to fix that issue before merge, regardless of the feature flag. I'll take a turn here.

2022-04-27 13:18 UTC, mhluongo commented on background/services/chain/index.ts
> +import { camelCase } from "lodash"
Oof, my intent here was to add the same version we already had from the lockfile to `package.json` as good practice.. going to remedy this, we don't need new library code for `camelCase()` lol.

When lockfiles are sued correctly, the content hash can protect us from some supply chain issues. Longer term we'll want to explore Lavamoat + some other techniques to tame the dep tree, but  it's out of scope for where we are now IMO.

2022-04-27 13:23 UTC, greg-nagy commented on background/services/chain/index.ts
> +import { camelCase } from "lodash"
I think we are good here. My understanding right now, is that yarn satisfies all the above version needs — coming from different libs — with the `4.17.21` version of the lib. And that's the version in `node_modules` also.

2022-04-27 15:55 UTC, henryboldi commented on background/services/chain/index.ts
> +import { camelCase } from "lodash"
> saw that already had lodash in our dep tree... 🙈

Shouldn't we still explicitly list `lodash` as a package in package.json? If whatever package that we're using ends up dropping `lodash` then we'll break

2022-04-27 16:02 UTC, mhluongo commented on background/services/chain/index.ts
> +import { camelCase } from "lodash"
Yep, and that was in face my intent. Fixing this :)

2022-04-27 19:17 UTC, Shadowfiend commented on background/services/chain/index.ts
> +import { camelCase } from "lodash"
The real question I was going to ask is... Why camel case at all? This should be accessed as data via a constant rather than as direct property accesses, so why force camel casing?

2022-04-27 21:20 UTC, henryboldi commented
Just chiming in to say that I love how this PR is a behind a feature flag, rather than waiting for full implementation 😍

2022-04-28 12:53 UTC, mhluongo commented on background/services/chain/index.ts
> +import { camelCase } from "lodash"
I was under the impression that you wanted to maintain this style of access, but if you don't care and no one likes it... :bomb:

2022-04-28 14:00 UTC, Shadowfiend commented on background/services/chain/index.ts
> +import { camelCase } from "lodash"
Yeah nope. I'll reply in Greg's thread below, which I missed yesterday.

2022-04-28 14:02 UTC, Shadowfiend commented on background/services/chain/index.ts
> +        camelCase(network.name),
I think Matt's right that we will find ourselves at times wanting access to particular networks for particular things; however, I think we'll define that using a central set of constants and methods that interact with those rather than through direct named property access. In particular, our network constants let us look up providers by passing the relevant constant in, and that should be the correct path. Any direct property access by name should set off alarm bells, as Greg pointed out, because the property access is effectively unchecked *and mostly uncheckable*.

2022-04-29 20:37 UTC, mhluongo commented on background/services/chain/index.ts
> +        camelCase(network.name),
Should be resolved!

2022-04-29 21:22 UTC, mhluongo commented
This is ready for another look! Note I'm seeing blocks from Optimism, Arbitrum, and mainnet in IndexedDB locally.

I'm still looking into the block price issue though. Someone confirming that would be :ok_hand:

2022-05-03 14:21 UTC, greg-nagy approved these changes
Tests

- [x] Without the feature flag `MULTI_NETWORK` set, Make sure balances are still pulled when importing a new account from a Ledger
- [x] Without the feature flag `MULTI_NETWORK` set, confirm account balances and asset transfers still function on mainnet
- [x] Setting `MULTI_NETWORK` to `true` in `.env`, confirm account balances and transfers still function on mainnet
- [x] After startup, you should see blocks from Optimism and Arbitrum in IndexedDB
- [x] Make sure balances are still pulled when importing a new account from a Ledger
- [x] Confirm gas prices populate work when sending ETH

Looks good :)

2022-05-03 14:26 UTC, merged

2022-05-05 19:52 UTC, SJQuality commented
Behind a feature flag. This looks good with it off and through smoke testing.