🥗 Put our redux store on a diet
tallycash/extension pull request #1363
Opened 2022-04-27 03:48 UTC by henryboldi

For #1351:

- [x] [Prune asset prices older than a day from Redux store](https://github.com/tallycash/extension/commit/7f12585a84354e2a8e47cddc05d7457fe23fea0f)
     - We have 2 charts designed, which are both Daily (Overview and Earn landing
page). More complex charts are not planned for the foreseeable future. So let's
prune prices older than a day. In any case, the price data is stored w/o this filter
in IndexedDB if we need it. 

- [x] [Limit number of activities added to the store](https://github.com/tallycash/extension/commit/54dd0b55d86aa39af276f5d6fb92bcdd4e55d61f)
- [x] Limit blocks dispatched to what's relevant to an activity
     - If blocks are added as they're seen, it's challenging to check if they're needed
since activities are added asynchronously. Therefore, this adds blocks to the
Redux store that are known to correspond with an activity we want.

2022-04-27 13:58 UTC, 0xDaedalus reviewed
👑  Love how you link to commits in the PR description - going to steal that.

Know this is a draft - just dropping some initial comments.

2022-04-28 08:24 UTC, henryboldi commented on background/redux-slices/activities.ts
> +          if (immerState[address].ids.length >= 45) {
Great question. `45` was pretty arbitrary. It was just to explore the impact it'd have. In reality, I don't think the number of activities is a top concern. Activity accumulation is fairly slow, and it's rare to get out of hand.

2022-04-28 12:49 UTC, mhluongo requested changes
Trying to impress the architectural lines here. Services decide what to do with data ingestion, Redux machinery is for deciding what's in the Redux store.

The price stuff looks great IMO, and is good to merge in a smaller PR. Concerns here are around the blocks.

2022-04-28 12:49 UTC, mhluongo commented on background/main.ts
> +import { blockFromEthersBlock } from "./services/chain/utils"
This is a smell

2022-04-28 12:49 UTC, mhluongo commented on background/main.ts
> +          transactionInfo.transaction.blockHash || ""
A couple issues here

* `main.ts` shouldn't be interacting with providers like this. It's making multi-network more difficult, and it's compromising the layered architecture. This would quietly pull Ethereum blocks from non-Ethereum networks 
* The `ChainService` should make decisions on when to emit block info, not `main.ts`

2022-04-28 12:49 UTC, mhluongo commented on background/redux-slices/networks.ts
> +    addBlock: (immerState, { payload: block }: { payload: AnyEVMBlock }) => {
I like the action being split between "here's the latest block seen" and "here's a block". But the actual pruning should be happening in the reducer rather than changing the behavior of `blockSeen` IMO.

2022-04-28 12:51 UTC, mhluongo commented on background/redux-slices/activities.ts
> +          if (immerState[address].ids.length >= 45) {
So can we... not? and focus on fixing the problems we have now?

This makes my wallet personal less useful, and I think we can revisit here down the road by introducing an "infini-scroll" style lazy loading

2022-04-28 14:03 UTC, henryboldi commented on background/redux-slices/networks.ts
> +    addBlock: (immerState, { payload: block }: { payload: AnyEVMBlock }) => {
How is it possible to know which block are needed if the activities are being added asynchronous?

2022-04-28 14:06 UTC, henryboldi commented on background/main.ts
> +import { blockFromEthersBlock } from "./services/chain/utils"
100% knew this and did it anyway 😈 heh

2022-04-28 14:24 UTC, henryboldi commented on background/redux-slices/activities.ts
> +          if (immerState[address].ids.length >= 45) {
Yup @mhluongo, it was already reverted when I posted my reply. And I had crossed out the change in the PR description.

2022-04-28 14:48 UTC, mhluongo commented on background/redux-slices/networks.ts
> +    addBlock: (immerState, { payload: block }: { payload: AnyEVMBlock }) => {
If there's a block / activity relation we need to filter on in a reducer, are we can't... that implies we have the wrong slice structure I think.

2022-04-28 14:57 UTC, mhluongo commented on background/redux-slices/networks.ts
> +    addBlock: (immerState, { payload: block }: { payload: AnyEVMBlock }) => {
I can see that being a longer-term  thing though

2022-04-28 14:58 UTC, henryboldi commented
> The price stuff looks great IMO, and is good to merge in a smaller PR.

Smart idea to separate the price stuff into a smaller PR. Will do!

2022-04-29 16:56 UTC, 0xDaedalus requested changes
Henry Senpai you've outdone yourself again :bow:.  Only real blocking thing is the migration I think as well as maybe mhluongo's comment unless that has been resolved and I'm just misunderstanding.

Oh, whats the best way to test this PR?  I've clicked around and nothing seems obviously broken but curious to know if there is a better or more specific way.

2022-04-29 16:56 UTC, 0xDaedalus commented on background/main.ts
> +import { blockFromEthersBlock } from "./services/chain/utils"
I see this got marked as resolved but as far as I understand it mhluongo's comment is still valid right?  We want to be exporting from `services/chain` rather than `services/chain/utils` or am I misunderstanding?

2022-04-29 16:56 UTC, 0xDaedalus commented on background/main.ts
> +    delete newState.networks.evm["1"].blocks // Only mainnet at this time
I think we need optional chaining here.  v0.10.0 which I believe is our first public release does not have `networks` in its redux slice on app load - so any users upgrading from that version or a later version that still doesn't have `networks` will have a bricked app unless they reinstall due to trying to access `evm` of `undefined`.

Lots of discussion on the topic [here](https://github.com/tallycash/extension/pull/1327#discussion_r852423241).

2022-04-29 16:56 UTC, 0xDaedalus commented on background/services/enrichment/types.ts
> +  timestamp: UNIXTime | undefined
What do you think about calling this "blockTimestamp"?  I think it'd improve clarity a bit when reading code inline w/o having to reference the above comment.

2022-04-29 17:00 UTC, henryboldi commented on background/services/enrichment/types.ts
> +  timestamp: UNIXTime | undefined
I agree, good point!

2022-04-29 17:02 UTC, henryboldi commented
> Nothing blocking here except maybe mhluongo's comment unless that has been resolved

I believe they're resolved aside from longer-term ideas outside the scope of this PR 🙏

2022-04-29 17:27 UTC, henryboldi commented on background/main.ts
> +import { blockFromEthersBlock } from "./services/chain/utils"
Good catch! I meant to remove this in https://github.com/tallycash/extension/pull/1363/commits/9dba3ffcc72951053f23a12688b3380235b65963. It's not used in my changes at all anymore. Removed. ✔️

2022-04-29 17:50 UTC, mhluongo reviewed
Great approach, love removing all the blocks from the frontend and moving this to metadata summarized by the services. Waiting on a rename (and testing on my end) to approve, it's close!

2022-04-29 17:50 UTC, mhluongo commented on background/services/enrichment/index.ts
> +        transaction.blockHash ?? ""
If `transaction.blockhash` is `undefined` here, we don't want to use the block later, right?

2022-04-29 17:50 UTC, mhluongo commented on background/services/enrichment/types.ts
> +  timestamp: UNIXTime | undefined
Also nice to revert the `annotatedAt` rename and avoid the extra work.

2022-04-29 18:02 UTC, henryboldi commented on background/services/enrichment/types.ts
> +  timestamp: UNIXTime | undefined
> Also nice to revert the annotatedAt rename and avoid the extra work.

Can't say I agree with that one...

2022-04-29 18:06 UTC, mhluongo commented on background/services/enrichment/types.ts
> +  timestamp: UNIXTime | undefined
`timestamp` is a legacy name from the annotation, right? I don't see a migration for it...

And that said... there's also no migration to add `blockTimestamp` to existing transaction annotations, so I guess existing users won't have timestamps on their activities anymore?

2022-04-29 18:07 UTC, mhluongo commented on background/services/enrichment/types.ts
> +  timestamp: UNIXTime | undefined
Every rename or deletion in the Redux store is like changing a database schema in this architecture. Apologies if I'm missing something obvious, when to migrate / when we can avoid keeps surprising me.

2022-04-29 18:14 UTC, henryboldi commented on background/services/enrichment/types.ts
> +  timestamp: UNIXTime | undefined
You're right this needs a migration 😬

2022-05-03 17:45 UTC, 0xDaedalus approved these changes
Looks good my comments have been addressed 👍

2022-05-03 18:03 UTC, greg-nagy approved these changes
Seeing what you have done here is some top level awesomeness. 

Couldn't find anything to add, so I am mostly here to express my happiness :) 

(Don't want to steal the thunder by merging this, but want to ... soo badly :) I definitely want this to be part of the next release)

2022-05-03 18:03 UTC, greg-nagy commented on background/services/enrichment/index.ts
> +      | (Partial<EIP1559TransactionRequest> & {
This is a monster function. Respect for these changes 🔥

2022-05-03 19:19 UTC, merged