RNS domain resolution
tallycash/extension pull request #1366
Opened 2022-04-27 17:05 UTC by 7alip

Adds [rns-resolver.js](https://www.npmjs.com/package/@rsksmart/rns-resolver.js) dependency.

[RIF Name Service (RNS)](https://developers.rsk.co/rif/rns/)

2022-04-28 18:51 UTC, Shadowfiend commented
Not asking for a change here yet, more exploring the problem space, but—how hard would it be to implement this resolution without adding the new dependency + its transitives?

2022-05-06 08:18 UTC, 7alip commented
> Not asking for a change here yet, more exploring the problem space, but—how hard would it be to implement this resolution without adding the new dependency + its transitives?

Hi @Shadowfiend, sorry for late responding, I was on vacation after creating the PR.

I'm not sure if it's possible to do a secure implementation with zero dependencies. An alternative solution might be to use ethers Contract + abi approach, as you made for ERC20 + ERC721 contracts. But in this case I will need to use `@ensdomains/eth-ens-namehash` dependency which is not listed in package.json.

Here is a possible example solution.

```ts
import ethEnsNamehash from '@ensdomains/eth-ens-namehash'

const RNS_REGISTRY_ABI = [
  "function resolver(bytes32 node) public view returns (address)",
]

const RNS_RESOLVER_ABI = [
  'function addr(bytes32 node) public view returns (address)',
]

const rnsRegistryContract = new Contract(rnsRegistryAddress, RNS_REGISTRY_ABI).connect(signer)

const getAddrResolverContract = async (domainHash: string): Promise<Contract> => {
  const resolverAddress = await rnsRegistryContract.resolver(domainHash)
  return new Contract(resolverAddress, RNS_RESOLVER_ABI).connect(signer)
}

const addr = async (domain: string): Promise<string> => {
  const domainHash = ethEnsNamehash.hash(domain)
  const resolverContract = await getAddrResolverContract(domainHash)

  return resolverContract.addr(domainHash)
}
```

2022-05-06 18:32 UTC, 7alip commented
I updated the branch and there is no additional dependency now. I tested manually and it seems to be working.
![rns](https://user-images.githubusercontent.com/22167684/167197496-6d949f42-9169-4582-9d45-419e1684f093.png)

2022-05-07 03:15 UTC, Shadowfiend commented
Stunning 🤩 Will do a deeper pass as soon as I have a moment!

2022-05-24 21:56 UTC, Shadowfiend requested changes
Left a couple of small questions and requests, which I think block the merge.

Unrelatedly, I'm not clear on how reverse resolution works…
- I tried adding 12345.rsk as a read-only address. This resolved `0x35E642029b911a63c3beBcA05fa5e1a1460E57F0` as the address (in agreement with the [RNS manager](https://manager.rns.rifos.org/resolve?name=12345.rsk)).
- The wallet then reverse-resolves to find the name to display in the top right (this is due in part to #1353, but in this case it's useful), but doesn't find a reverse resolution for that address (also in agreement with the [RNS manager](https://manager.rns.rifos.org/resolve?name=0x35E642029b911a63c3beBcA05fa5e1a1460E57F0)).

I would expect 12345.rsk to resolve to `0x35e642029b911a63c3bebca05fa5e1a1460e57f0` and vice versa—but perhaps this is not how RNS works?

-----

Finally, the biggest issue I saw testing this is that I'm seeing the RSK provider start throttling pretty hard, and the result isn't… Great for the wallet itself. It may be an ethers thing where the retries are too aggressive, but overall we're seeing a lot of logging and slowdown from all the throttled lookups.

The throttling shouldn't block merging here, but I do think we need to avoid flipping the feature flag on until we're comfortable the underlying provider can handle the kind of volume we have. For reference, we do reverse resolution on to/from addresses for all transactions we see and any account that is added, as well as for any ERC20 `Transfer` sender or recipient.

We don't currently do aggressive caching of lookups, but if that's something that would help we can look into introducing a stronger caching framework into the `NameService`.

2022-05-24 21:56 UTC, Shadowfiend commented on background/services/name/resolvers/rns.ts
> +        logger.warn("Domain has no resolver")
We should not warn here, as this is a normal circumstance (anytime an address has no corresponding .rsk domain, it will have no resolver). We could use `logger.debug`, but I would almost say skip the logging.

2022-05-25 01:26 UTC, 7alip commented
Thanks a lot for reviewing and testing.

**Reverse**

> I would expect 12345.rsk to resolve to 0x35e642029b911a63c3bebca05fa5e1a1460e57f0 and vice versa—but perhaps this is not how RNS works?

`reverse` will not be resulting the address until the owner sets the reverse in RNS manager or by code. You can see how to do it the screenshot. For example [tally.rsk](https://testnet.manager.rns.rifos.org/resolve?name=0x29c6469246F9f93beA6631eD1F5edCC5Ff8288C3) for testnet.

<img width="1680" alt="rns-reverse" src="https://user-images.githubusercontent.com/22167684/170157678-215bcd6b-1fb4-4bc6-bc25-99dcd2808f77.png">

**Throttling**

> It may be an ethers thing where the retries are too aggressive, but overall we're seeing a lot of logging and slowdown from all the throttled lookups.

Let me try to test it some other external RPC providers instead of public node to make sure whether ethers causes the throttling.

2022-05-25 12:58 UTC, Shadowfiend commented on background/services/name/resolvers/rns.ts
> +      )
Got it! Now we're in "asking because curious" more than anything else, but if RSK support was added to the wallet and we wanted the associated RSK address, would this call look exactly the same or is there a version that takes a chain id or is similarly network aware?

2022-05-25 13:01 UTC, Shadowfiend commented
> reverse will not be resulting the address until the owner sets the reverse in RNS manager or by code.

Got it, so it's a separate step. Cool, that's the bit I was missing :)

> to make sure whether ethers causes the throttling

To be clear, I don't think ethers is causing the throttling---I think the subsequent slowdown in the extension during debugging might be due to ethers retrying too aggressively after it gets the 529 error from the server. I think the throttling is from our regular lookups.

2022-05-26 19:29 UTC, alepc253 commented
Hi @Shadowfiend, the RSK public node throws a `429 Too Many Requests` after exceeding the rate limit of 300 per minute (if you hit the maximum, you have 1 minute penalty). I don't know the testing you are doing but it's very likely that the slowdown is due to this.

2022-05-27 15:02 UTC, Shadowfiend approved these changes
This fellow is good to go behind the feature flag. Going to do a main merge, test drive, and land it!

Left a note on how I think we take the overall name resolution system closer to the finish line for cross-chain resolvers like RNS.

2022-05-27 15:51 UTC, alepc253 commented
@Shadowfiend yes, RNS is a multichain resolver so having a compatible chain type would make it trivial to pass the parameter and resolve all the chains

2022-05-31 13:59 UTC, merged