localize overview, menu, bug report page
tallycash/extension pull request #1402
Opened 2022-05-06 14:36 UTC by gasolin

distill strings and localize 3 pages
- menu
- bug report
- overview

<img width="381" alt="截圖 2022-05-06 下午10 35 46" src="https://user-images.githubusercontent.com/748808/167154728-2f7609c5-6b68-4537-9c90-5e62c05cb2be.png">

<img width="381" alt="截圖 2022-05-06 下午10 35 24" src="https://user-images.githubusercontent.com/748808/167154761-5efd4bc3-406f-45c9-9858-08720e1584e0.png">

2022-05-16 12:02 UTC, jagodarybacka commented
@gasolin Thank you for your contribution 🥇 

@tallycash/extension-devs how do we want to approach this PR - do we want to check it with some online translator (I've done this and it seems ok)?

2022-05-18 14:59 UTC, gasolin commented
@jagodarybacka this will be the last PR with language other than `en`,  future language changes could be come from weblate https://github.com/tallycash/extension/issues/438

2022-05-19 02:29 UTC, derolis88 requested changes
Personal Suggestions :)

3. Community Edition
 "社區版" 
47  "Use Tally Ho as default wallet"
設置為默認錢包
55. Join our community
加入我們的社區

2022-05-19 03:12 UTC, gasolin commented
> Personal Suggestions 😊
> 
> 3. Community Edition
>    社區版
> 
> 47 Use Tally Ho as default wallet 設置為默認錢包
> 
> 55. Join our community
>     加入我們的社區

hi, thanks for suggestions!

since the attach strings are `zh_tw` strings and `社區`, `默認` are more commonly used for `zh_cn` strings

2022-05-19 13:56 UTC, jagodarybacka requested changes
I've read your discussion on Discord and it seems that the translations we have right now are ready, right @derolis88?

btw, I will [hide translations behind the feature flag](https://github.com/tallycash/extension/issues/1498) so we will have time to properly create them and maybe add a language switcher 

One issue to fix @gasolin ⬇️

2022-05-19 13:56 UTC, jagodarybacka commented on ui/pages/Popup.tsx
> +      <div className="community_edition_label">{t("popupEdition")}</div>
I've noticed that we have regression regarding "Community edition" badge - it was accidentally removed during huge merge between repos we had last week. Can you remove this line for now? Don't remove "popupEdition" translation because I will add the badge back.

```suggestion
```

2022-05-21 05:57 UTC, gasolin commented
- comment addressed
- remove zh strings based on discord discussion https://discord.com/channels/808358975287722045/808360140008456203/976507037913587723
- add translation section in readme to describe the current approach (and as a reference to apply for the weblate open source hosting)

2022-05-24 11:22 UTC, merged