⛽️ Custom gas, miner fee, max base
tallycash/extension pull request #1418
Opened 2022-05-10 01:19 UTC by henryboldi

This adds a new gas picker interface which displays more information. Specifically, it displays a miner fee (`maxPriorityFee`) and max base (`maxFee - maxPriorityFee`) next to each option. Moreover, it adds the ability to pick a custom miner fee and max base.

- [x] **Displays max base and miner fee for each option**
A max base is somewhat unusual, but makes it clear for users. Typically, there's `maxPriorityFee` and `maxFee`. `maxPriorityFee` is included in the `maxFee` which can be confusing, so max base slips the base fee and the `maxPriorityFee`. A max priority fee is what we're calling the miner fee. While its naming implies max, visually always all is spent.
- [x] **Adds support for custom max base and miner fee**
Essentially this adds a custom gas option to Redux, which is then editable from the gas fee pick UI.
- [x] **Behind a feature flag. Set `CUSTOM_GAS_SELECT=true` to test**
Because the new gas feature is includes a slew of changes, I've put it behind a feature flag so we can merge changes into main incrementally. Due to the amount of changes to the settings, I've added `NetworkSettingsSelectDeprecated.tsx` which contains, aside from tweaks for compatibility with our updated store, the interface from the previous version.

_However, it's missing:_

- A migration for the custom gas field
Will add this in another PR. However, when testing make sure to give it a fresh install, and fresh `npm start`.
- Proper implementation of the design
I'd like to get the logic here approved separately from making it pretty.

<img width="300" alt="custom" src="https://user-images.githubusercontent.com/1918798/167777277-ba1cb700-4f66-4eb0-922d-587f440a6b9f.png">

🤘

2022-05-11 19:19 UTC, 0xDaedalus commented
> A migration for the custom gas field
Will add this in another PR. However, when testing make sure to give it a fresh install, and fresh npm start.

This makes me a bit nervous - I feel like migrations are one of the most fragile parts of our application and while I do agree that this PR already has quite a large diff I do think that our implicit convention of changes to the redux store requiring a corresponding migration is a useful convention to keep.

2022-05-11 19:58 UTC, 0xDaedalus requested changes
🎉 🎉 🎉  I am so frickin excited for this to land!!

2022-05-11 19:58 UTC, 0xDaedalus commented on background/constants/network-fees.ts
> +  0: "-",
We should be able to calculate estimated speed based on if the custom fee set right?  If the user is setting  the fee above whatever we predict `99` is we can say `<30 seconds` no?  Same with `> 5 mins` for less than our prediction for `70`.

2022-05-11 19:58 UTC, 0xDaedalus commented on background/constants/network-fees.ts
> +  0: 20n,
The `0` as a key for custom confidence feels a bit awkward here and maybe is an indicator that we could rework some of the data structures around fees (although I completely understand why you've chosen it) - probably out of the scope of this PR though.

2022-05-11 19:58 UTC, 0xDaedalus commented on background/redux-slices/transaction-construction.ts
> +    custom: {
Why do we add this to `intialState`?

2022-05-11 19:58 UTC, 0xDaedalus commented on background/redux-slices/transaction-construction.ts
> +        baseFeePerGas: estimatedFeesPerGas.baseFeePerGas,
I think this block might benefit from extracting the construction of the `instant`, `express,` and `regular` blocks into a function.

Something like
```
const makeBlockEstimate = (type, estimatedFeesPerGas):  BlockEstimate => {
return {
          maxFeePerGas:
            (estimatedFeesPerGas.baseFeePerGas * MAX_FEE_MULTIPLIER[type]) /
            10n,
          confidence: type,
          maxPriorityFeePerGas:
            estimatedFeesPerGas.estimatedPrices.find(
              (el) => el.confidence === type
            )?.maxPriorityFeePerGas ?? 0n,
          price:
            estimatedFeesPerGas.estimatedPrices.find(
              (el) => el.confidence === type
            )?.price ?? 0n,
        }
}
```

2022-05-11 19:58 UTC, 0xDaedalus commented on background/redux-slices/transaction-construction.ts
> +          price: 41000000000n,
We may want to comment why we hard-code to this number

2022-05-11 19:58 UTC, 0xDaedalus commented on ui/components/NetworkFees/FeeSettingsText.tsx
> +      ? truncateDecimalAmount(weiToGwei(networkSettings.values.maxFeePerGas), 0)
We can remove the `ESTIMATED_FEE_MULTIPLIERS_BY_TYPE` import from this file

2022-05-11 19:58 UTC, 0xDaedalus commented on ui/components/NetworkFees/NetworkSettingsSelect.tsx
> +        const basePrices = [regular, express, instant, custom]
I think `baseFees` might be a better variable name here to match line 181 (since we're extracting the variables from `estimatedFeesPerGas`)

2022-05-11 19:58 UTC, 0xDaedalus commented on ui/components/NetworkFees/NetworkSettingsSelectDeprecated.tsx
> +import { BlockEstimate } from "@tallyho/tally-background/networks"
Should this be called `Deprecated`?  Its a new component right?

2022-05-11 19:58 UTC, 0xDaedalus commented on ui/components/NetworkFees/NetworkSettingsSelect.tsx
> +              <button
Should this and the above `custom` implementation be factored out into standalone components?

2022-05-11 19:58 UTC, 0xDaedalus commented on ui/components/NetworkFees/NetworkSettingsSelectDeprecated.tsx
> +            parseAndValidate={(value) => {
I think we can avoid defining this function inline.

2022-05-11 19:58 UTC, 0xDaedalus commented on ui/components/NetworkFees/NetworkSettingsSelectDeprecated.tsx
> +          <button
Another component that can be factored-out into its own file I think.

2022-05-11 20:18 UTC, henryboldi commented on background/redux-slices/transaction-construction.ts
> +    custom: {
In `NetworkSettingsSelect` we use display the buttons using a map on the `gasOptions` object. If custom isn't present here, that option will not display. I added it to the initial state in particular because `custom` doesn't need to be grabbed from a service.

2022-05-11 20:19 UTC, henryboldi commented on background/redux-slices/transaction-construction.ts
> +        baseFeePerGas: estimatedFeesPerGas.baseFeePerGas,
Good point!

2022-05-11 20:20 UTC, henryboldi commented on ui/components/NetworkFees/NetworkSettingsSelectDeprecated.tsx
> +import { BlockEstimate } from "@tallyho/tally-background/networks"
This is essentially the old gas settings component.

2022-05-11 20:22 UTC, henryboldi commented on ui/components/NetworkFees/NetworkSettingsSelectDeprecated.tsx
> +          <button
I agree, but this is the old/deprecated version of the gas settings

2022-05-11 20:25 UTC, henryboldi commented on background/constants/network-fees.ts
> +  0: 20n,
100% agree! But me agreeing is custom so it's 0% 😜

2022-05-11 20:28 UTC, 0xDaedalus commented on ui/components/NetworkFees/NetworkSettingsSelectDeprecated.tsx
> +import { BlockEstimate } from "@tallyho/tally-background/networks"
I see - then I am confused by [this block of code](https://github.com/tallycash/extension/pull/1418/files#diff-332672ebfc50afcbf72043e6fb2f9c62c622ade6859df2e34e7e27aeed07a858R246).

My understanding here is custom gas select is net_new right?  The code makes it seem that if we have the CUSTOM_GAS_SELECT feature flag turned on we show the deprecated component - am i having a brain fart here?

2022-05-11 20:38 UTC, henryboldi commented on background/constants/network-fees.ts
> +  0: "-",
Estimated speed for custom values would be awesome! That said, it's actually not in the design.
<img width="525" alt="gas_select" src="https://user-images.githubusercontent.com/1918798/167943390-2df3e2b0-76d2-4af8-b30e-31bf4b20f1ff.png">

cc @VladUXUI

2022-05-11 20:46 UTC, henryboldi commented on ui/components/NetworkFees/NetworkSettingsSelectDeprecated.tsx
> +import { BlockEstimate } from "@tallyho/tally-background/networks"
Crap, it was meant to be `if (!CUSTOM_GAS_SELECT) {`! 😂

2022-05-12 00:46 UTC, mhluongo commented on background/constants/network-fees.ts
> +  0: "-",
I'm not sure those times makes sense with the behavior we've seen with EIP-1559 on mainnet... more likely we'd see something like

Instant, ~15 sec
Express, ~30 seconds
Regular, > 30 seconds


... seeing as increasing the max base fee doesn't make a tx land any faster, it makes a tx land more reliably... and increasing the priority should lead to it landing faster.
  
I don't have the data (we should collect it), but raising that before we remove the flag

2022-05-12 07:47 UTC, VladUXUI commented on background/constants/network-fees.ts
> +  0: "-",
>Estimated speed for custom values would be awesome!

Didn't think we can calculate this tbh, we can definitely add time for custom as well. 
I expect/assume most users will use custom for higher values, for these values we can probably show <30 sec
For lower values we can calculate based on our estimations.

That being said, i don't see this as a big gain for users, but if it makes sense to spend the dev time. I'm all for it

2022-05-12 07:51 UTC, VladUXUI commented on background/constants/network-fees.ts
> +  0: "-",
>seeing as increasing the max base fee doesn't make a tx land any faster

I mean i guess it depends on network conditions right? 
If network base fee goes higher than currently selected max base, then you have to potentially wait for the basefee to come down back again in order for your tx to be added/mined. Thus increasing the waiting times.

2022-05-12 07:54 UTC, VladUXUI commented on background/constants/network-fees.ts
> +  0: "-",
>Instant, ~15 sec
>Express, ~30 seconds
>Regular, > 30 seconds

My numbers were not based on anything tbh, so i'm good with anything here.
Just keeping in mind that it's best for the users to be pleasantly surprised that it's mined faster than feeling like they were cheated out of some gas.

Let's go with your values and we can adjust later if need be.
CC @henryboldi

2022-05-12 07:58 UTC, VladUXUI commented on background/constants/network-fees.ts
> +  0: 20n,
Uncertain if this assumption is actually correct. But i think users that use custom are going to set higher fees rather than lower ones.
So i guess the question is, should we also have pre-filed values for custom? Maybe Instant + 20%?

@henryboldi @mhluongo

2022-05-12 12:02 UTC, Shadowfiend commented on background/constants/network-fees.ts
> +  0: 20n,
You can just add a "custom" key, no?

2022-05-13 05:12 UTC, VladUXUI commented on ui/components/NetworkFees/NetworkSettingsSelect.tsx
> +            padding: 15px;
Small thing. This is probably 16px, as we always use multiple of 2

2022-05-19 02:22 UTC, mhluongo commented
Is this ready for another look? And if we're still missing the Redux migration... is there an associated issue?

2022-05-19 02:39 UTC, henryboldi commented
Yes, it's ready for another look! 🙇‍♂️

https://github.com/tallycash/extension/issues/1495

2022-05-19 03:39 UTC, Shadowfiend reviewed
Quick note that the migration should only be a separate PR if the redux store only requires them with the feature flag on---if the store will break on upgrade even with the flag off, we shouldn't merge until there's a migration.

2022-05-19 03:39 UTC, Shadowfiend commented on background/redux-slices/transaction-construction.ts
> +  custom?: BlockEstimate
Bothered by having a `custom` entry in an estimated fees type with a BlockEstimate structure when it's not actually an estimate.

But mostly in a "not willing to put in the time to suggest a better approach" way 😅

2022-05-19 03:43 UTC, henryboldi commented
> if the store will break on upgrade even with the flag off, we shouldn't merge until there's a migration.

Yes, I believe the store will not break. It'll work as normal but without the custom option.

2022-05-19 03:44 UTC, henryboldi commented on background/redux-slices/transaction-construction.ts
> +  custom?: BlockEstimate
I feel you! 😬

Hmm, would it be possible to solve this with some renaming?

2022-05-19 23:19 UTC, 0xDaedalus commented on ui/components/NetworkFees/NetworkSettingsSelect.tsx
> +    baseMaxFeePerGas: BigInt(maxFeePerGas) - BigInt(maxPriorityFeePerGas),
Do we need to mix units here?  Based on the other properties in this object it seems like it would be more consistent for this to be in `gwei`

2022-05-19 23:22 UTC, 0xDaedalus commented on ui/components/NetworkFees/NetworkSettingsSelectDeprecated.tsx
> +  maxFeePerGas: bigint
I think comments here that the units here are `wei` might be helpful to future contributors.

2022-05-19 23:24 UTC, 0xDaedalus commented on background/redux-slices/transaction-construction.ts
> +  maxPriorityFeePerGas: bigint
I think comments here that these are in `wei` might help future contributors.

2022-05-19 23:25 UTC, 0xDaedalus commented on background/redux-slices/transaction-construction.ts
> +  maxGwei: string
Should we consistently make the units in we use in here `wei` and then use `weiToGwei` where we need to display `Gwei` to the user?

2022-05-20 03:26 UTC, henryboldi commented on background/redux-slices/transaction-construction.ts
> +  maxGwei: string
That's a good idea. How would you feel about that happening in a follow-up PR?

2022-05-20 04:29 UTC, 0xDaedalus commented on background/redux-slices/transaction-construction.ts
> +  maxGwei: string
I feel 💯 about that!

2022-05-20 10:29 UTC, jagodarybacka commented on ui/components/Shared/SharedInput.tsx
> +    step = undefined,
`step` will be `undefined` anyway, no need to set it here I guess 😛

2022-05-20 10:31 UTC, jagodarybacka commented on ui/components/NetworkFees/NetworkSettingsSelectOptionButtons.tsx
> +          background: #002522;
we already have this color in 2 other places, maybe it is worth adding to CSS variables?

2022-05-22 18:48 UTC, 0xDaedalus approved these changes
What an absolute unit of a PR!  There is a small visual problem that I've made a [separate issue](https://github.com/tallycash/extension/issues/1505) but considering that the visual portion is feature flagged this guys is more-than-ready to be merged.  Bravo ser.

2022-05-22 18:49 UTC, merged