Add input for custom DAOs address
tallycash/extension pull request #1509
Opened 2022-05-23 14:46 UTC by jagodarybacka

Resolves #1461 

### What
* Added input under the list of DAOs so users are able to choose their own referrer by typing its name or address.
* Improved resolving names and avatars for these custom referrers
* Added "change" button for referrer so user can easily change it

![image](https://user-images.githubusercontent.com/20949277/169845330-93f05353-55f6-42c2-92e6-f3c301e93213.png)
![image](https://user-images.githubusercontent.com/20949277/169845382-c7984d8b-5f9b-435b-82e7-e02c7809cce8.png)

2022-05-23 14:51 UTC, jagodarybacka commented on background/services/signing/index.ts
> +          parseInt(`${typedData.domain.chainId}`)
for some reason I couldn't sign delegation because `typedData.domain.chainId` was a string but it is expected to be a number 🤔

2022-05-25 21:49 UTC, henryboldi commented
Looking good!! 👑

If I remember correctly, isn't this custom DAO address here not really intended for DAO addresses? Well, I see you've implemented it to work with any address, but, in that case, we're perhaps massaging regular addresses onto the DAO type and name in a way that can get messy.

 cc @VladUXUI

2022-05-26 09:18 UTC, jagodarybacka commented
@henryboldi Yeah so the PR's title is misleading, as I understand it can be any address that user wants to share the bonus with so it's more like... choosing the referrer? I'm getting lost in who it referrer and delegate 😂 

But it's the same thing, given address will receive the bonus, no matter if it is a dao or custom address, right? I couldn't put this address as the `referrer` in the redux state as this would mess up the UI (switching to referrer style interface of this page). 

Maybe we shouldn't save the `address + name` from this page as a DAO, maybe we can rename it? I don't know the right word that would fit here 😞

2022-05-26 13:12 UTC, henryboldi commented
> Maybe we shouldn't save the address + name from this page as a DAO, maybe we can rename it? I don't know the right word that would fit here

How about `bonusOrigin` or `bonusBy`?

2022-05-26 15:09 UTC, jagodarybacka commented
@henryboldi hmm, but it is at the same time `bonusBy` and `bonusFor` 😄 as right now this field in redux state is named `selectedDAO` I think we can name it `selectedForBonus`

2022-05-26 18:03 UTC, greg-nagy requested changes
This PR is looking good and works really well! Well done 🤩

There is the typing issue and a minor renaming that felt to be a blocker / should be explored and fixed ASAP.

2022-05-27 10:26 UTC, jagodarybacka commented on background/services/signing/index.ts
> +          parseInt(`${typedData.domain.chainId}`)
I will revert this change and I will fix it as a separate issue to not block this PR

2022-05-27 11:18 UTC, greg-nagy approved these changes
let's ⛴  this beauty ✨

2022-05-27 11:19 UTC, merged