(localize) distil strings from wallet Send and receive pages
tallycash/extension pull request #1559
Opened 2022-06-01 14:54 UTC by gasolin

related to #438

2022-06-02 10:24 UTC, jagodarybacka requested changes
Looks good, just one minor thing:

2022-06-02 10:24 UTC, jagodarybacka commented on ui/_locales/en/messages.json
> +  },
let's start with a lowercase letters so `"protocol___": { ...`

2022-06-04 08:00 UTC, gasolin commented on ui/_locales/en/messages.json
> +  },
thanks, comment addressed

2022-06-06 10:14 UTC, jagodarybacka approved these changes
Works fine, let's 🚀

2022-06-06 10:14 UTC, merged