💲 Add accounts to all EVM networks
tallycash/extension pull request #1571
Opened 2022-06-03 13:12 UTC by jagodarybacka

Resolves https://github.com/tallycash/extension/issues/1501

### What
To show and track a new account properly we need to add it to each EVM network we support when the account is added by the user.

### Test

Fresh install
1. Reinstall extension
2. Add wallet with seed
3. Check if the first address is fine on Ethereum mainnet and Polygon (it is displayed on the accounts list)
4. Add some new addresses to the same wallet on Ethereum
5. Switch to Polygon - added addresses should be visible on the list (even without selecting them as active accounts)
6. Add some new addresses to the same wallet on Polygon
7. Switch to Ethereum  - they should be on the list too

Migration testing
1. Checkout `main`
2. Add accounts to Ethereum (2+ addresses), don't switch to Polygon
3. Checkout this branch
4. Switch to Polygon - all the addresses should be there as well

![image](https://user-images.githubusercontent.com/20949277/171860754-a261b85b-fde9-4b5b-af0a-910862ccc555.png)

2022-06-03 13:33 UTC, 0xDaedalus requested changes
There's an edge case here we have to guard against - and I'm not sure of the best way to do it.

Consider the following steps

- checkout `main`
- import a wallet
- add 3 addresses to your wallet (do NOT switch to polygon)
<img width="378" alt="image" src="https://user-images.githubusercontent.com/94649004/171863724-10c06e35-9c05-4b5b-b594-6649c6a744e7.png">
- checkout your branch - refresh the extension
- switch to polygon (you'll only see one address)
- add another address
<img width="375" alt="image" src="https://user-images.githubusercontent.com/94649004/171863929-07a151b2-7eda-4e26-934d-b06c87600d1f.png">

That address will be in polygon (and properly added to Ethereum as well) - but the addresses you added on Ethereum will not be visible on the Polygon chain.  Unfortunately I think this will happen to _everyone_ who has more than one address imported into their wallet for a given keyring when we make the update from single-chain to multi-chain.

What do you think the best way forward here is?  This definitely feels like some kind of migration or perhaps we could simplify it to `as part of keyring service init - ensure that all addresses are present on all supported chains`.  We should think about the best approach here because we'll likely encounter this problem each time we add a new chain.

2022-06-03 13:33 UTC, 0xDaedalus commented on background/constants/networks.ts
> +export const EVM_MAIN_NETWORKS_SUPPORTED = [ETHEREUM, POLYGON]
I never knew how much I wanted this until this very moment :bow:

2022-06-03 13:37 UTC, Shadowfiend commented on background/constants/networks.ts
> +export const EVM_MAIN_NETWORKS_SUPPORTED = [ETHEREUM, POLYGON]
Any reason not to fix it so EVM_MAIN_NETWORKS only lists the ones we support? Feature flags can add or not like we do for name resolvers.

2022-06-03 13:38 UTC, jagodarybacka commented
@0xDaedalus Thank you, I haven't thought about this problem 😞 Will try to find a way to fix it for existing wallets

2022-06-03 13:40 UTC, jagodarybacka commented on background/constants/networks.ts
> +export const EVM_MAIN_NETWORKS_SUPPORTED = [ETHEREUM, POLYGON]
Yeah, I'm not sure why do we even show Arbitrum and Optimism in the dropdown if we don't have any support for them 😄

2022-06-03 14:22 UTC, Shadowfiend commented on background/constants/networks.ts
> +export const EVM_MAIN_NETWORKS_SUPPORTED = [ETHEREUM, POLYGON]
Guessing the state of play may have changed since we had that conversation (in particular, the focus on getting Polygon out the door as a complete package before the other two).

2022-06-03 14:23 UTC, Shadowfiend commented
A migration for existing wallets is a good idea IMO. This is a one-time thing, and future behavior will work this way.

We've fixed adding an address here, but we'll need to fix deleting an address as well.

2022-06-03 14:26 UTC, Shadowfiend commented on background/main.ts
> +          network,
We probably need to do this for Ledger accounts as well, right?

One important thing to note as we look further into the future: EVM compatibility isn't enough to say an address/network pair should be added for a new address. Certain networks will be EVM-compatible but will derive addresses differently. Not an issue right now as I believe the 3 L2s we're looking at all use the same Ethereum addresses.

2022-06-03 14:40 UTC, 0xDaedalus commented on background/main.ts
> +          network,
Whats an example of this type of network?  I'd love to start looking into this

2022-06-03 16:03 UTC, mhluongo commented on background/constants/networks.ts
> +export const EVM_MAIN_NETWORKS_SUPPORTED = [ETHEREUM, POLYGON]
Yep! We maybe remove them and rename `USE_MULTINETWORK` or something?

I was working on Arbi and Option in parallel. Now that we know we're going to focus on Polygon first, the feature flags need a lil refactor

2022-06-03 16:05 UTC, mhluongo commented on background/main.ts
> +          network,
RSK uses a different derivation path by default. If you're an RSK user you wouldn't expect the same address on Ethereum.

I think they should reconsider this, but there's a bunch of legacy wallets already 🤷‍♂️

2022-06-06 13:40 UTC, Shadowfiend commented
Perfectly down to do it separately, yeah. Just wanted to make sure that + Ledger didn't get missed before we un-feature-flag.

2022-06-07 15:04 UTC, jagodarybacka commented
This can be reviewed and tested.
Still to do (but can be done in the next PR):
- [ ] support Ledger with Polygon accounts
- [ ] fix the order of accounts on Polygon after the migration (they are the same but the order is different than on the Ethereum list)

2022-06-07 15:38 UTC, jagodarybacka commented
@0xDaedalus for Ledger I've added new issue, accounts order problem is right now only visible on this branch, either I will fix it tomorrow or we can merge it (if the rest will be working fine) and then create an issue (as this is minor problem anyway compared to not having accounts added to Polygon at all)

2022-06-07 16:29 UTC, merged

2022-06-08 02:57 UTC, Shadowfiend reviewed
Noticed something that makes me uncomfortable after merge, sorry. Lmk what you think here, I don't think it'll fundamentally change behavior on the user side right now.

2022-06-08 02:57 UTC, Shadowfiend commented on background/services/chain/index.ts
> +        EVM_MAIN_NETWORKS.map((network) => [
Sorry for not noticing this earlier, but hard objection to moving from the chain service managing supported networks to having it be a global. The chain service is the right source of truth for this info, and all uses of it right now have access to the chain service. Strongly recommend that we keep the logic that sets the "main networks" in here as supported networks.

It won't break anything now, but by globalizing this responsibility we're inviting the leaking of decisions based on this info into strange places.

2022-06-08 02:57 UTC, Shadowfiend commented on background/services/name/resolvers/uns.ts
> +        EVM_MAIN_NETWORKS.some((supportedNetwork) =>
I don't think this is correct behavior. UNS may not support a network even if we do.

2022-06-08 04:03 UTC, 0xDaedalus commented on background/services/chain/index.ts
> +        EVM_MAIN_NETWORKS.map((network) => [
We'll need to query `chainService.supportedNetworks` inside of `internal-ethereum-provider` to prevent a regression of the accidental uniswap polygon bug.

2022-06-08 12:01 UTC, jagodarybacka commented on background/services/chain/index.ts
> +        EVM_MAIN_NETWORKS.map((network) => [
@Shadowfiend ok, reverted back to using `chainService.supportedNetworks` - but the value is still based on `EVM_MAIN_NETWORKS` which is changed by feature flags so right now the behaviour is the same. I guess you are mostly thinking ahead that we would like to make the logic of `supportedNetworks` more complex, right?

2022-06-08 12:07 UTC, jagodarybacka commented on background/services/chain/index.ts
> +        EVM_MAIN_NETWORKS.map((network) => [
@0xDaedalus that file wasn't changed in this PR, can we make it a separate issue? Are you talking about [this line](https://github.com/tallycash/extension/blob/main/background/services/internal-ethereum-provider/index.ts#L219)?