Add Tokemak to list of sites to override Metamask
tallycash/extension pull request #1572
Opened 2022-06-03 17:22 UTC by imthinhvu

Adds Tokemak as one of the sites to override Metamask with

2022-06-06 10:27 UTC, jagodarybacka commented on window-provider/index.ts
> +const impersonateMetamaskWhitelist = ["opensea.io", "bridge.umbria.network", "tokemak.xyz"]
please run `yarn lint-fix` to satisfy the linter 🤓

2022-06-07 16:33 UTC, 0xDaedalus commented
I'm actually not sure that this is needed.  Tally Ho seems to connect to and work fine with tokemak without needing to override `window.ethereum.isMetaMask`.  Was there some specific functionality that was not working @imthinhvu ?

2022-06-07 16:41 UTC, imthinhvu commented
> I'm actually not sure that this is needed. Tally Ho seems to connect to and work fine with tokemak without needing to override `window.ethereum.isMetaMask`. Was there some specific functionality that was not working @imthinhvu ?

The connect doesn't work for me. When I try in Brave Browser with Shields down, I get the following error: 

<img width="1511" alt="Screen Shot 2022-06-07 at 12 40 39 PM" src="https://user-images.githubusercontent.com/4204797/172436668-39a12e3b-6ef8-4949-b272-120c06405e77.png">

If I use Metamask instead, it works fine.

2022-06-08 07:25 UTC, jagodarybacka commented
It's not blocking for this PR and if we really have this problem on Brave maybe we should merge it but I'm wondering:

do we even support Brave right now? As it is chromium/V8 based browser most of the features should be working fine but maybe there are some minor problems and I'm pretty sure we are not testing extension on anything besides Chrome and Firefox.

2022-06-09 13:54 UTC, greg-nagy requested changes
@imthinhvu Thank you very much for this PR. 

Tried on brave, but adding tokemak to the list did not make any difference.  In both cases clicking the `Metamask` button opens [this url](brave://wallet/crypto/onboarding).

Tested dApp connections on brave with uniswap and sushi and both worked well, so I assume the issue is with how tokemak is implemented dApp connection. 

Tried to search for the source for their UI, but couldn't find it.

Are you interested in digging deeper into the issue? We would be really happy to deliver a more robust impersonation feature.

2022-06-09 15:45 UTC, imthinhvu commented
Not at this time, but I can try to revisit this once I free up some time on my end. Can close this PR for now.

2022-06-09 15:45 UTC, closed without merging