Dapp Permission Redux Refactor
tallycash/extension pull request #1619
Opened 2022-06-13 22:54 UTC by 0xDaedalus

Partially Addresses #1604 

This PR changes our dappPermission redux store to match the desired spec in the [Multi Network RFC](https://github.com/tallycash/extension/blob/main/rfb/rfb-3-multinetwork-dapp-connections.md#redux)

Proper description pending

2022-06-17 11:19 UTC, jagodarybacka reviewed
hmm, uniswap is not working correctly but maybe that's my fault so can you check it? Sushi swap is fine, both connect and disconnect

2022-06-17 11:25 UTC, jagodarybacka commented
I've found a path to break it:
1. Connect and disconnect with dapp (sushiswap in my case)
2. reload the extension 
3. open extension -> blank screen

2022-06-17 12:27 UTC, greg-nagy commented
> hmm, uniswap is not working correctly but maybe that's my fault so can you check it? Sushi swap is fine, both connect and disconnect

it's not you, uni integration is broken for unknown reasons — will dig into it (gdi)

2022-06-17 14:08 UTC, greg-nagy requested changes
I've noticed a few inconsistent behaviors: 
- In the redux slice we store permission only for the current network, but in indexedDB we store permission for every network 
- When revoking a permission only the the current network is removed from both redux slice and indexedDB
- When granting or revoking permissions, the `permissionRequests` list is not updated properly
- When reloading the extension the permissions from the indexedDB are overwriting the redux slice (this is the intended behavior, but important in this context)

I think some or all the above are related [to the bug](https://github.com/tallycash/extension/pull/1619#issuecomment-1158776446) @jagodarybacka has found

note: redux devtools usually does not work for me, but this script can be used from devtools > sources > snipetts (left hand side, narrow window tab)

```
console.clear()
chrome.storage.local.get(["state"], ({state: stateString}) => {
    const state = JSON.parse(stateString)
    console.log("dapp.allowed.evm", JSON.stringify(state.dapp.allowed.evm, null, 2))
    console.log("dapp.permissionRequests", JSON.stringify(state.dapp.permissionRequests, null, 2))
})
```

2022-06-17 14:29 UTC, greg-nagy commented on background/redux-slices/selectors/dappSelectors.ts
> +      Object.keys(allowed.evm[chainId]).forEach((address) => {
> I've found a path to break it:
> Connect and disconnect with dapp (sushiswap in my case)
> reload the extension
> open extension -> blank screen

![CleanShot 2022-06-17 at 16 12 17](https://user-images.githubusercontent.com/7690112/174315590-fe8147a6-6474-4f4e-95c2-1770a15c7cd1.png)

![CleanShot 2022-06-17 at 16 13 51](https://user-images.githubusercontent.com/7690112/174315771-7c6d9647-9792-486b-87df-0a919ed97b35.png)

I found these issues. Scratching my head why this is happening.

```
console.clear()
chrome.storage.local.get(["state"], ({state: stateString}) => {

    function selector() {
        Object.keys(state.dapp.allowed.evm).forEach(([chainId]) => {
        console.log(chainId)    
        console.log(Object.keys(state.dapp.allowed.evm))
          Object.keys(state.dapp.allowed.evm[chainId]).forEach((address) => {
              console.log(address)
          })
        })
    }

    
    const state = JSON.parse(stateString)

    
    console.log("dapp.allowed.evm", JSON.stringify(state.dapp.allowed.evm, null, 2))
    console.log("dapp.permissionRequests", JSON.stringify(state.dapp.permissionRequests, null, 2))
    selector()
})
```

![CleanShot 2022-06-17 at 16 26 07](https://user-images.githubusercontent.com/7690112/174317946-e94b0d90-4c43-42b1-bede-2acba8263712.png)

```
['137'].forEach(([chainID]) => console.log(chainID))
VM348:1 1
```

2022-06-17 14:33 UTC, greg-nagy reviewed
Found the problem \o/

2022-06-17 14:33 UTC, greg-nagy commented on background/redux-slices/selectors/dappSelectors.ts
> +    Object.keys(allowed.evm).forEach(([chainId]) => {
`Object.keys(allowed.evm).forEach(([chainId]) => {` > `Object.keys(allowed.evm).forEach(chainId => {`

2022-06-17 17:13 UTC, 0xDaedalus commented on background/redux-slices/selectors/dappSelectors.ts
> +    Object.keys(allowed.evm).forEach(([chainId]) => {
oof. thanks - wonderful debugging

2022-06-17 17:14 UTC, 0xDaedalus commented on background/redux-slices/migrations/to-11.ts
> +  evm: {
I think I want the extra typesafety of having an explicit `evm` key while we don't support others VMs.  Once we do we can move to a `[networkFamily: string]` type signature

2022-06-18 20:50 UTC, Shadowfiend commented on background/redux-slices/selectors/dappSelectors.ts
> +      Object.keys(allowed.evm[chainId]).forEach((address) => {
> forEach(([chainId])

This should not have square brackets; we're deconstructing the first letter/number from the chain id instead of pulling the full chain id.

2022-06-18 20:55 UTC, Shadowfiend commented on background/redux-slices/migrations/to-11.ts
> +  evm: {
Migrations should def be specific in terms of what we expect, and snapshot-in-time in terms of not trying to track the long term goals.

For future typing purposes though, `[networkFamily: NetworkFamily]` is the correct typing from Greg's note, as `NetworkFamily` is more restrictive than `string`.

2022-06-18 21:00 UTC, Shadowfiend commented on background/services/provider-bridge/utils.ts
> +export type PermissionMap = {
I would nuke this file completely and have these in /index tbh.

We should not reference the redux state to define the `PermissionMap` type; instead, we should reference the `PermissionMap` type in the redux slice.

2022-06-21 21:43 UTC, 0xDaedalus commented on background/services/provider-bridge/utils.ts
> +export type PermissionMap = {
Doesn't the above pattern break our rule of avoiding services depending on redux?

2022-06-24 10:29 UTC, jagodarybacka reviewed
Wow, so much work done 🥳

2022-06-24 10:29 UTC, jagodarybacka commented on background/redux-slices/dapp.ts
> +          const permissions = [ETHEREUM, POLYGON].map((network) => ({
shouldn't we get suported networks from `chainService.supportedNetworks`?

2022-06-24 10:29 UTC, jagodarybacka commented on background/redux-slices/dapp.ts
> +              // chainID;
```suggestion
```

2022-06-24 10:29 UTC, jagodarybacka commented on background/redux-slices/dapp.ts
> +  allowed: {
It confuses me to have `allowed` and `allowedPages` side by side, can you maybe leave a comment here what is allowed? Below we have the method `initializeAllowedPages` but we are actually setting `allowed` field. I don't get at the first sight what should I expect from each field 😞

2022-06-24 12:16 UTC, 0xDaedalus commented on background/redux-slices/dapp.ts
> +          const permissions = [ETHEREUM, POLYGON].map((network) => ({
We don't really ever want to pull services into redux - and since the all-or-nothing approach to granting & denying is temporary - i think this is probably an ok amount of tech debt to assume for the time being.

2022-06-24 12:16 UTC, 0xDaedalus commented on background/redux-slices/dapp.ts
> +              // chainID;
🙇

2022-06-24 12:20 UTC, 0xDaedalus commented on background/redux-slices/dapp.ts
> +  allowed: {
Good catch and tyty - `allowedPages` was left over from the initial run through of the refactor when I was being extra careful about types.  Went ahead and renamed the method as well to be less confusing

2022-06-24 12:27 UTC, 0xDaedalus commented on background/redux-slices/dapp.ts
> +      // @TODO Re-key by origin-chainID-address
@greg-nagy @Shadowfiend What do you guys think about this deviation from the RFB? (in a downstream PR)

2022-06-24 13:03 UTC, greg-nagy commented on background/redux-slices/dapp.ts
> +      // @TODO Re-key by origin-chainID-address
I am good with it, but I will let @Shadowfiend have the final say here if he wants to.

2022-06-27 14:00 UTC, 0xDaedalus commented on background/redux-slices/dapp.ts
> +      // @TODO Re-key by origin-chainID-address
To be clear this is not something that should block this PR from being merged

2022-06-28 12:08 UTC, greg-nagy approved these changes
let's 🚢

2022-06-28 12:16 UTC, greg-nagy approved these changes
🚢 is delayed, let's 🚀

2022-06-28 12:20 UTC, merged