Check if address looks like a domain before validation
tallycash/extension pull request #1625
Opened 2022-06-15 10:57 UTC by jagodarybacka

Resolves https://github.com/tallycash/extension/issues/1356

### What
If the user is typing a string that looks like an ENS or UNS domain we should wait a bit and not show the error before the string really looks like a valid domain.

![image](https://user-images.githubusercontent.com/20949277/173811198-1fc39582-d7a8-4689-bda0-a832f2f3f2b0.png)

2022-06-15 19:32 UTC, henryboldi requested changes
Love this! However, I don't think it closes https://github.com/tallycash/extension/issues/1356 because

> I think we should hold off on domain resolution until an input value looks like a domain.

2022-06-15 21:08 UTC, 0xDaedalus commented on background/lib/utils/index.ts
> +export function isProbablyEVMAddress(str: string): boolean {
Why loosen our typesafety here?

2022-06-15 22:33 UTC, Shadowfiend commented
> I think we should hold off on domain resolution until an input value looks like a domain.

I can reply in the issue. This is a non-goal, the lookups will not necessarily just be for domains (eg address book entries).

2022-06-15 23:01 UTC, henryboldi approved these changes
> This is a non-goal, the lookups will not necessarily just be for domains (eg address book entries).

Then we're good to go here :)

2022-06-15 23:02 UTC, henryboldi commented on background/lib/utils/index.ts
> +export function isProbablyEVMAddress(str: string): boolean {
I thought that `boolean` is more correct here?

2022-06-15 23:05 UTC, merged

2022-06-16 08:49 UTC, jagodarybacka commented on background/lib/utils/index.ts
> +export function isProbablyEVMAddress(str: string): boolean {
@0xDaedalus because this function is returning `boolean` right? I've had type errors on the string passed as an argument to the function,