💯 Fix "0.00 ETH" spend when sending a low amount
tallycash/extension pull request #1663
Opened 2022-06-23 14:39 UTC by henryboldi

2022-06-23 16:03 UTC, Shadowfiend commented on ui/components/SignTransaction/SignTransactionTransferInfoProvider.tsx
> +    .toFixed(20)
Can you use the fixed-point stringification function here or is there something wonky it does? This approach will lose precision.

2022-06-29 13:27 UTC, greg-nagy requested changes
The `wonky massaging` is really wonky. :) 

Let's use a type guard instead!

2022-06-29 13:27 UTC, greg-nagy commented on ui/components/SignTransaction/SignTransactionTransferInfoProvider.tsx
> +  // @TODO Remove this wonky massaging
I think you need [isFungibleAssetAmount()](https://github.com/tallycash/extension/blob/a639aefcefb1bb52e242234e9e77867307aaa9e7/background/assets.ts#L199) and some error handling here. 

You can probably use this in the ternary below.

2022-06-29 14:29 UTC, henryboldi commented on ui/components/SignTransaction/SignTransactionTransferInfoProvider.tsx
> +  // @TODO Remove this wonky massaging
Updated, my co-author :)

2022-06-30 20:37 UTC, 0xDaedalus approved these changes
👨‍🍳 💋

2022-06-30 20:54 UTC, merged