Insufficient funds warning in network fees
tallycash/extension pull request #1689
Opened 2022-06-30 13:13 UTC by jagodarybacka

Resolves https://github.com/tallycash/extension/issues/858
Resolves https://github.com/tallycash/extension/issues/1432
Resolves #1109

### What
* show warning in network fees slide up on transaction approval screen
* block approve button if there is a user won't have enough funds to pay for transaction

![image](https://user-images.githubusercontent.com/20949277/176685248-8ca123f4-907a-4938-9f3a-36b3af649f79.png) ![image](https://user-images.githubusercontent.com/20949277/176685547-6b84daba-c816-4a0e-b4de-3753e1c61d99.png)

2022-06-30 22:05 UTC, 0xDaedalus requested changes
It looks like I am still able to sign when the warning displays

https://user-images.githubusercontent.com/94649004/176786659-e9a6c50c-f0c2-4051-97c9-45ab6f59da51.mov

2022-07-01 10:39 UTC, greg-nagy commented
@0xDaedalus this was working well for me. Would you mind giving this another look?

2022-07-01 10:51 UTC, greg-nagy requested changes
Small codewise notes.

2022-07-01 10:51 UTC, greg-nagy commented on ui/pages/PersonalSign.tsx
> +      warnings={[]}
This feels a bit strange. Could we use default prop values for the component?

2022-07-04 11:47 UTC, jagodarybacka commented on ui/components/SignTransaction/SignTransactionContainer.tsx
> +                    isOnDelayToSign || warnings.includes("insufficient-funds")
this string is specified by [Warning type](https://github.com/tallycash/extension/blob/main/background/services/enrichment/types.ts#L39)

2022-07-05 14:56 UTC, 0xDaedalus approved these changes
👍

2022-07-05 16:22 UTC, merged

2022-07-05 19:41 UTC, henryboldi commented
> show warning in network fees slide up on transaction approval screen

How can the warning be on this page if the transaction annotation isn't updated until saving the gas setting?

2022-07-06 15:38 UTC, henryboldi commented
Correct. I think that warning is meant to be based on the live edits you make to this settings page.