WIP: (refactor) better organize strings with i18next format
tallycash/extension pull request #1721
Opened 2022-07-03 03:40 UTC by gasolin

i18next has more features than chrome extension localization, one of that is the organize strings with domain

We used `view + String` directly for all strings, but its harder to recognize due to longer string name.
i18next allos us to organize strings like

{
  'overview': {
    'amount': '....'
  },
  'wallet': {
  },
  'settings': {
  }
}

and reference the string like `overview.amount` instead of `overviewAmount` in current json file

@jagodarybacka @henryboldi if you like it, I can finish this refractory

2022-07-03 05:02 UTC, henryboldi commented
Looks excellent! Likely will merge after I test this tomorrow  🙌

2022-07-03 09:38 UTC, gasolin commented
@henryboldi please wait until I fully refactored all existing strings

2022-07-03 20:33 UTC, Shadowfiend commented
@gasolin don't worry, we do not merge draft PRs, so as long as you're in draft mode you're good :)

2022-07-03 20:48 UTC, henryboldi commented
Oh right, it's a draft! Was feeling trigger happy 😅

2022-07-04 13:55 UTC, jagodarybacka requested changes
Awsome refactor ✨ 

just one more place has been omitted 😄 
![image](https://user-images.githubusercontent.com/20949277/177169264-e09c6a83-7896-4b84-b026-35cb9b662b33.png)

2022-07-04 13:55 UTC, jagodarybacka commented on ui/_locales/en/messages.json
> +    "errorNoSellAsset": "Attempting to approve transfer without a sell asset.",
maybe we can nest `error...` strings?

2022-07-05 12:46 UTC, jagodarybacka approved these changes
Works fine 🚢

2022-07-05 12:46 UTC, merged