Password strength bar
tallycash/extension pull request #1732
Opened 2022-07-05 11:10 UTC by jagodarybacka

Resolves https://github.com/tallycash/extension/issues/1329

### What

Create the password strength bar component and use it to evaluate how strong is the password that user wants to create.

https://user-images.githubusercontent.com/20949277/177314535-0c8de87d-565a-44bc-8819-6ef748229299.mov

2022-07-05 17:21 UTC, mhluongo requested changes
Works well locally. Left a couple thoughts on copy + naming!

2022-07-05 17:21 UTC, mhluongo commented on ui/components/Shared/SharedPasswordBar.tsx
> +export default function SharedPasswordBar(
A more descriptive name might be `SharedPasswordStrengthBar`

2022-07-05 17:21 UTC, mhluongo commented on ui/components/Shared/SharedPasswordBar.tsx
> +        For a strong password use a mix of: Lowecase, Uppercase, symbols and
I know this copy was in Figma, but let's tighten it up.

```
For a strong password, consider a mix of lower and uppercase characters, symbols, and numbers. Passwords should be over 8 characters.
```

Also wondering if we should be dropping new copy into our locales file rather than directly in JSX?

2022-07-06 11:18 UTC, Shadowfiend commented on ui/components/Shared/SharedPasswordBar.tsx
> +export default function SharedPasswordBar(
Should this be shared at all? Are we expecting it will be used anywhere other than that one page?

2022-07-06 11:19 UTC, jagodarybacka commented on ui/components/Shared/SharedPasswordBar.tsx
> +export default function SharedPasswordBar(
I think maybe on the "change password" page it should be used as well when we will create that page in the future

2022-07-06 12:05 UTC, Shadowfiend commented on ui/components/Shared/SharedPasswordBar.tsx
> +export default function SharedPasswordBar(
Not really looking to waste much time on it, but I think to me the Shared namespace implies sharing across fairly unrelated use cases. If we have a password creation and change flow I'd probably expect a `components/Password/PasswordCreate` and `components/Password/PasswordChange` type of structure that would allow the strength bar to live alongside both. 

All of that can be handled another time tbh, just sharing some of my thinking here.

2022-07-07 06:15 UTC, henryboldi commented on ui/components/Shared/SharedPasswordBar.tsx
> +export default function SharedPasswordBar(
> I think to me the Shared namespace implies sharing across fairly unrelated use cases. If we have a password creation and change flow I'd probably expect a components/Password/PasswordCreate and components/Password/PasswordChange type of structure that would allow the strength bar to live alongside both.

100%

2022-07-07 15:50 UTC, merged