Fix Quickswap Integration
tallycash/extension pull request #1792
Opened 2022-07-11 21:24 UTC by 0xDaedalus

Closes https://github.com/tallycash/extension/issues/1785

This PR:
- Explicitly attaches the jsonrpc version to messages we send through the provider-bridge
- Caches the window.ethereum walletrouter Proxy so we don't run into edge cases with strict equality and `window.ethereum`.

To Test:
- connect to quickswap.exchange
- Ensure you're using their new UI (you might need to clear cache)
- Connect and swap

2022-07-11 21:26 UTC, 0xDaedalus commented
For those testing - this is what the new UI looks like

<img width="937" alt="image" src="https://user-images.githubusercontent.com/94649004/178361335-f99f15fd-5f49-4cec-a5ef-8802fb43d2f8.png">

2022-07-12 10:10 UTC, jagodarybacka approved these changes
I can connect wallet with both old and new Quickswap 🎊 

I'm not sure about the changes in code, seems like we are introducing a lot of exceptions, maybe we can at least mark these places with a common comment so we know where they are if we decide to refactor it later?

2022-07-12 12:19 UTC, jagodarybacka commented
@0xDaedalus This PR probably can resolve #1713 because I think it is now working correctly, you can choose to change network and Quickswap will see Polygon assets.

2022-07-12 12:25 UTC, greg-nagy requested changes
I love this fix and that you managed to debug the problem! It's is truly a spectacular catc!

Blocker: There is a bug this introduces with the "use tally as default" toggle. See #1793 


Not blocker but needs to be fixed quickly: The other thing that makes me really itchy is the whitelisting in many places. I am trying to fix the problem properly withour whitelists. I feel it's really important to make sure that this doesn't stick with us for the long term.

2022-07-12 12:44 UTC, jagodarybacka commented
@0xDaedalus this PR fixes Meshswap too https://github.com/tallycash/extension/issues/1791 because now I can change selected network to Polygon from dapp and it can access my Polygon balance

2022-07-12 13:13 UTC, 0xDaedalus commented on background/services/provider-bridge/index.ts
> +      origin.includes("quickswap.exchange")
Metamask's security model here is better than what we currently have since they _do_ prompt the user to explicitly permit network changes.  

With the current model there's nothing stopping a dapp from switching networks before signing - but I think an overarching fix to that is out of the scope of this PR or our current roadmap goals.

I've gone ahead and created https://github.com/tallycash/extension/issues/1794 as a follow-on to alleviate this somewhat

2022-07-12 15:12 UTC, greg-nagy approved these changes
looks good, let's 🚢

2022-07-12 15:12 UTC, merged