🌠 NFTs prototype part one
tallycash/extension pull request #1850
Opened 2022-07-27 06:44 UTC by henryboldi

2022-07-27 09:15 UTC, jagodarybacka commented on background/redux-slices/nfts.ts
> +      immerState.evm[network.chainID][normalizedAddress] = NFTs
it's an override anyway so we probably can commit `??= []` and go straight to assignment. But I wonder if we want to override whole thing every time

2022-07-29 14:39 UTC, 0xDaedalus reviewed
Took a quick look at the code - none of my comments are blocking - this is so exciting!!! 🎉 🎉

2022-07-29 14:39 UTC, 0xDaedalus commented on background/constants/networks.ts
> +export const NETWORK_BY_CHAIN_ID = {
❤️

2022-07-29 14:39 UTC, 0xDaedalus commented on background/redux-slices/nfts.ts
> +    [chainID: string]: {
Want to inject some food-for-thought here for us all to think about.  I would the structure of evm => chainId => address => item very cumbersome to work with and requiring somewhat opaque selectors when implementing cross-chain dapp permissions.  Does that resonate with you at all?  I wonder if evm => address => chainId => item would be better (considering our whole application is address-centric).

2022-07-29 14:39 UTC, 0xDaedalus commented on background/redux-slices/nfts.ts
> +async function fetchNFTs(address: string, currentNetwork: EVMNetwork) {
Do you think that `fetchNFTsByNetwork` could be a more explicit name here?

2022-07-29 14:39 UTC, 0xDaedalus commented on background/redux-slices/nfts.ts
> +      NFTsSlice.actions.updateNFTs({
I think we can probably get rid of `NFTsSlice.actions.` here (just because I think thats the pattern we tend to favor in the other reducers)

2022-07-29 14:39 UTC, 0xDaedalus commented on background/redux-slices/selectors/nftsSelectors.ts
> +const selectNFTs = createSelector(
We might be well served by extending our type for NFTs and adding the `chainID` inside of the `fetchNFTs` function since at that point we know what network we're fetching them for.  If we do that we can just set-it-and-forget-it

2022-07-29 14:41 UTC, 0xDaedalus commented on background/redux-slices/selectors/accountsSelectors.ts
> +export const getAllNetworks = createSelector(
I'm a bit concerned about performance here and in `getAllAddresses` - if you find that there are some you might want to consider passing a custom memoization function to these selectors.

2022-07-29 14:51 UTC, jagodarybacka commented on background/redux-slices/selectors/accountsSelectors.ts
> +export const getAllNetworks = createSelector(
ah yes, that's the thing I was struggling with today - but I haven't found any good solutions, do you have some example how to make`createSelector` remember that array?

2022-07-29 14:59 UTC, henryboldi commented on background/redux-slices/nfts.ts
> +async function fetchNFTs(address: string, currentNetwork: EVMNetwork) {
100%

2022-07-29 15:07 UTC, henryboldi commented on background/redux-slices/selectors/nftsSelectors.ts
> +const selectNFTs = createSelector(
I'd be nervous about storing `chainID` in two places. What if the `chainID` on the NFT gets out of sync with the   `chainID` used as the key in the store?

2022-07-29 19:23 UTC, greg-nagy requested changes
Wonderful work ✨

The api error handling is an absolute must with user notification as well. (It can create really hard to catch bugs later and we should get error handling into our DNA) 

We should make a quick decision about the slice data structure as well. I can accept the current shape if that's the consensus, but feel that the proposed version would serve us better even at the cost of refactoring now.

2022-07-29 19:23 UTC, greg-nagy commented on background/redux-slices/nfts.ts
> +    [chainID: string]: {
I feel that we are moving back and forth between chainID or address focused. It feels to me that they craete a unique key together and it's probably not a good idea to put one above the other. See above comment.

2022-07-29 19:23 UTC, greg-nagy commented on background/redux-slices/nfts.ts
> +  media: { gateway?: string }[]
Partially the reason for this comment is that I think we should start shifting our mindset when we think about redux from something defined by "this is what's in the background" into "hey redux is actually a view model, let UI define the shape it needs"

2022-07-29 19:23 UTC, greg-nagy commented on ui/components/NFTs/NFTsOverview.tsx
> +    allAddresses.forEach((address) =>
I wanted alchemy to support batched requests sooooo much. But it doesn't ... :(

2022-07-29 19:23 UTC, greg-nagy commented on ui/components/NFTs/NFTsWallet.tsx
> +import React, { ReactElement, useEffect } from "react"
Love the separation ❤️

2022-07-29 19:56 UTC, henryboldi commented
> The api error handling is an absolute must with user notification as well. 

@greg-nagy, We're not flipping the feature flag yet, so I don't believe everything needs to be completed in this "part one" PR

2022-07-29 20:00 UTC, greg-nagy commented
>> The api error handling is an absolute must with user notification as well.
>  We're not flipping the feature flag yet, so I don't believe everything needs to be completed in this "part one" PR

Yes, you are correct and this thought changes the data structure issue from a blocker to a TBD and follow up PR. 

But I feel strongly about the api error handling and user notification. So much so, that I would like us to get to a point that if we write api call and not handle the errors we feel something is off. (The user notification can be a console.log, or simply an error message [like for the swaps](https://github.com/tallycash/extension/blob/860ce3a61af9f753a0bb64d74678f325c3c3152b/background/redux-slices/0x-swap.ts#L283))

2022-07-29 20:09 UTC, henryboldi commented on background/redux-slices/nfts.ts
> +  media: { gateway?: string }[]
Here are a few reasons this change shouldn't be blocking:

1. The data structure of NFTs here is simply following the pattern in the accounts slice. Changing the structure will create an inconsistency.

2. Until we stop fetching NFTs every time the tab is opened, there would be no need for a migration.

3. The goal of this iteration is to put a prototype in the hands of users asap. It's not clear that giving NFTs their own slice like this, separate from assets, is even ideal anyway.

2022-07-29 20:24 UTC, henryboldi commented
Proper error handling here is enough code to justify a separate PR/discussion. I totally agree that it's important, but this PR is already too big. We're aiming to make PRs more task oriented rather than feature by feature

2022-08-01 10:06 UTC, jagodarybacka commented on background/redux-slices/nfts.ts
> +  media: { gateway?: string }[]
Another problem I see with first suggested approach is that `contractID + tokenID` is not unique key (I've tried to use it as a React list item key and there were warnings).

I love flat structure but then why to we need `evm`? We won't have any other VM supported for a long time I guess.

Also we have to take into consideration tight deadline for this feature, I would love to upgrade our codebase but I feel like we don't have much room for innovation right now 😞

2022-08-01 10:17 UTC, jagodarybacka commented on background/redux-slices/nfts.ts
> +      }/getNFTs/?owner=${address}`
about pagination - in the next PR we have added lists virtualization so we can possibly implement endless scroll, paginated fetching NFTs could be nice but I think it can be done a little bit later 😄

2022-08-01 11:56 UTC, jagodarybacka commented
@greg-nagy's comments addressed in the https://github.com/tallycash/extension/pull/1866

2022-08-01 15:42 UTC, greg-nagy approved these changes
thank you all, this is beautiful ✨🙇‍♂️

2022-08-01 15:43 UTC, merged

2022-08-01 15:57 UTC, greg-nagy commented
A couple of thoughts here because there was tension around this.

@jagodarybacka 's solution was perfect. (I intended to do this myself, sorry for not getting to it.) 
I was looking for that 5 lines of code here. Nothing else. 

The reason I blocked this is that we tend to handle error handling as a separate task, and this is really dangerous, and not from an engineering perspective but from a product and user experience point. 

PR is big: that's true, but not related to the 5 lines of code for error handling. Let's split up PRs into smaller chunks next time so it won't cause extra tension if something needs to be changed. 

But at the same time, I do appreciate that this was an experiment that grow to be big, and you wanted to get it under control by merging the current state. I felt bad for hindering this effort but felt it was necessary. 

I also appreciate the fact that we haven't talked about error handling and this change in general beforehand. It wasn't the best communication on my part to do it by blocking this PR. But again, even though it was not ideal at all, I felt that it's better to start this sooner than wait for the ideal situation later. 

Anyhow, ty @henryboldi @jagodarybacka! You are truly the MVPs for this sprint 🚀