🗣️ Add language switch in Settings
tallycash/extension pull request #1883
Opened 2022-08-03 14:59 UTC by gasolin

- Add language select UI in Settings
- Add `SUPPORT_MULTIPLE_LANGUAGES=false` to env.default
- Use localStorage to store lang selection

~~Check the source and there's no existing menu selector element to use (the closest is the ShareAssetInput)~~

~~to make test multi lang easier, let developer able to switch languages by add `DEFAULT_LANGUAGE="zh_tw"` or `DEFAULT_LANGUAGE="pt_br"` in .env file~~

~~show current language in Settings when DEFAULT_LANGUAGE env is set~~

<img width="385" alt="截圖 2022-08-03 下午10 46 00" src="https://user-images.githubusercontent.com/748808/182640152-a1aa2222-8cb3-4c9e-b08a-d0b8aa342460.png">

2022-08-04 15:51 UTC, jagodarybacka commented
This is looking great so far! ✨ 

Don't you want to implement the whole dropdown as designed here: https://github.com/tallycash/extension/issues/1544#issuecomment-1147138639? So we can have it without the `DEFAULT_LANGUAGE` flag.

Or you can do it in another PR if you prefer 😄

2022-08-05 05:46 UTC, gasolin commented
@jagodarybacka as I mentioned there's no existing menu selector component and will take quite an effort to align with the design.

The possible approach is to distill the MenuSelector element from ShareAssetInput and reuse it for the language switch, but it will not include in this PR

2022-08-05 08:45 UTC, jagodarybacka commented
@gasolin It's `SharedSelect` 😄 
Here is snippet to start:
```javascript
      <SharedSelect
        width={194}
        options={[{ value: "en", label: "English" }]}
        onChange={() => {}}
      />
```
![image](https://user-images.githubusercontent.com/20949277/183039144-de5641e6-1950-401e-b3ca-8d7d0b24dee0.png)

2022-08-06 09:52 UTC, gasolin commented
@jagodarybacka thanks! 
Updated to the language select UI and add `SUPPORT_MULTIPLE_LANGUAGES=false` to env.default

What's missing is to get/store the user-select language to `tally-background/redux-slices/ui`
could be a separate patch before multi-lang goes to the production

2022-08-07 16:50 UTC, mhluongo commented
So excited for this :smile:

2022-08-08 12:42 UTC, jagodarybacka requested changes
Amazing progress, so excited to see this! 🔥 🔥 🔥 

Some things I've noticed:
1. Maybe we can rename folder `_locales` to `locales` as I don't see any reason why underscore is needed here
2. Can you try to fix this empty space that is visible on the open dropdown? It feels like styles are broken here
![image](https://user-images.githubusercontent.com/20949277/183419918-706aa7f6-65f0-48a9-8b70-08d1d96ef811.png)

2022-08-08 12:42 UTC, jagodarybacka commented on .env.defaults
> +SUPPORT_NFTS=false
```suggestion
SUPPORT_NFTS=true
```
😂

2022-08-08 12:42 UTC, jagodarybacka commented on ui/_locales/index.ts
> +interface ILang {
we are not really following that convention with prefixing interface names with `I` but it's up to you. And we are mostly using `type` instead of `interface` for simple types like `ILang` and `ILangOptions` here

2022-08-08 12:42 UTC, jagodarybacka commented on .env.defaults
> +SUPPORT_MULTIPLE_LANGUAGES=false
this feature flag is not working correctly because you have to add it to the https://github.com/tallycash/extension/blob/main/background/features.ts

2022-08-08 12:47 UTC, gasolin commented
> Amazing progress, so excited to see this! 🔥 🔥 🔥
> 
> Some things I've noticed:
> 
> 1. Maybe we can rename folder `_locales` to `locales` as I don't see any reason why underscore is needed here

was named after chrome localization convention, fine to rename the folder now (it will effect weblate setup though)

> 2. Can you try to fix this empty space that is visible on the open dropdown? It feels like styles are broken here
>    ![image](https://user-images.githubusercontent.com/20949277/183419918-706aa7f6-65f0-48a9-8b70-08d1d96ef811.png)

The switch UI could be fixed in a separate task since its a general issue

2022-08-08 12:56 UTC, jagodarybacka commented
> was named after chrome localization convention, fine to rename the folder now (it will effect weblate setup though)

if it will break weblate we can do it later if you want

> The switch UI could be fixed in a separate task since its a general issue

👍

2022-08-08 12:58 UTC, jagodarybacka commented
@gasolin Let me confirm with the rest of the team if we want to hide it behind the feature flag or not 😄

2022-08-08 13:32 UTC, gasolin commented
@jagodarybacka for a proper multi-lang release I think we still missed the translation of the onboarding/ledger support part, so I'd tend to hide it at this stage

2022-08-08 14:31 UTC, jagodarybacka commented
Good point but on the other hand we can use existing implementation to get more people involved in the translations 😃

2022-08-09 10:10 UTC, jagodarybacka approved these changes
@gasolin I've fixed dropdown placement and feature flag 😄 Thank you for this PR, it's awesome! 

Let's merge it with feature flag so I can create a QA build so others can take a look at this!

2022-08-09 10:12 UTC, merged