Shared Enrichment: Enrich addresses to protect users from malicious transactions
tallycash/extension pull request #1900
Opened 2022-08-08 03:30 UTC by mhluongo

Description incoming! 

Refs #1234 #509 #261 #262 #84

2022-08-08 21:47 UTC, Shadowfiend commented
High level approach looks real good---enriched address types, switching up fields accordingly, etc---don't expect I'll have time to go deep in review though.

2022-08-09 11:08 UTC, jagodarybacka commented on background/services/enrichment/addresses.ts
> +    ...addressOnNetwork,
Why do we need address and network on both levels - here and inside the annotation?

2022-08-09 11:31 UTC, Shadowfiend commented on background/services/enrichment/index.ts
> +        this.nameService,
Not necessarily convinced this is an improvement. May make more sense to pass the whole enrichment service instance to the enrichers rather than double the parameter list. The dependencies are clearer, but the outcome feels more brittle. Could easily be convinced otherwise though. 

Also wondering if we call these resolve* functions enrich* instead so anything that adds enrichment data is simply an enrichment.

2022-08-09 19:46 UTC, mhluongo commented on background/services/enrichment/index.ts
> +        this.nameService,
It's a pretty convoluted service otherwise... these functions have a lot of dense heuristics / knowledge that I think should be separated out for easier review. I do hate this though, and passing a single service arg does make sense.

Agreed on the `enrich*` name too. Just cargo-culted to get this together.

2022-08-09 19:47 UTC, mhluongo commented on background/services/enrichment/addresses.ts
> +    ...addressOnNetwork,
Hmm, no need to repeat that, taking a look

2022-08-09 19:55 UTC, mhluongo commented on background/services/enrichment/index.ts
> +        this.nameService,
Ehhhhh actually... man this ask is a bunch of rework of existing code. Not excited about it, and would rather tackle it in a separate PR / next time we touch this part of the codebase.

2022-08-09 20:02 UTC, mhluongo commented on background/services/enrichment/addresses.ts
> +    ...addressOnNetwork,
It doesn't appear to be repeated, what am I missing? There's no `AddressOnNetwork` in the annotation.

It is annoying that the `NameOnNetwork` is in the annotation, but I actually think that's the correct type relative to what could happen (resolving a mainnet ENS name for a Polygon address/network)

2022-08-09 20:10 UTC, Shadowfiend commented on background/services/enrichment/index.ts
> +        this.nameService,
That's fine, def not a blocking request. Also I was specifically referring to the explosion of parameters--factoring enrichment functions out as simple functions and pulling them into separate files is 💯💯💯 and already a huge improvement imo.

2022-08-09 20:12 UTC, Shadowfiend commented on background/services/enrichment/addresses.ts
> +    ...addressOnNetwork,
I think address and network are both at this level and in the annotation:

https://github.com/tallycash/extension/pull/1900/files#diff-f7c854a5832bd3939d021b1db87eaf2062a16e02da3e1bce4f832c9889cab854R40

https://github.com/tallycash/extension/pull/1900/files#diff-f7c854a5832bd3939d021b1db87eaf2062a16e02da3e1bce4f832c9889cab854R25

2022-08-10 14:31 UTC, mhluongo commented on background/services/enrichment/addresses.ts
> +    ...addressOnNetwork,
Oof, any way I can get the type system to have prevented that? Certainly not the intent

https://github.com/tallycash/extension/pull/1900/files#diff-8b87467ba85224abe33cbe9bc89de9060126857d46bd6f03ef71a7bdce3dba57R133

2022-08-10 14:32 UTC, mhluongo commented on background/services/enrichment/addresses.ts
> +    ...addressOnNetwork,
Fixing it in the meantime

2022-08-11 02:06 UTC, Shadowfiend commented on background/services/enrichment/addresses.ts
> +    ...addressOnNetwork,
Typescript is a minimal definition rather than a full one unless/until they implement exact types unfortunately. Excess property checks do happen in certain scenarios but not everywhere.

2022-08-11 20:44 UTC, mhluongo commented
This is ready for another look @jagodarybacka @Shadowfiend @0xDaedalus. Note that it will unblock a number of security features and proposed GitHub grants... I think we should merge it!

2022-08-12 00:28 UTC, Shadowfiend commented
PR author thinks PR should be merged... News at 11 😉

2022-08-12 19:40 UTC, mhluongo commented
It's okay, now there's a big ol' conflict from @0xDaedalus 's work :sob:

2022-08-12 21:29 UTC, 0xDaedalus requested changes
Looks like the activity screen is broken on this branch:

<img width="377" alt="image" src="https://user-images.githubusercontent.com/94649004/184446904-b762ffb8-9d55-4eed-8af1-a408dcf14f2f.png">

[Looks like](https://github.com/tallycash/extension/compare/shared-enrichment...shared-enrichment-patch) we're not always setting `recipient`, `contractInfo`, and `sender` despite our type system thinking that we do. 

The above patch fixes the error but I think its probably better to figure out the root cause.

2022-08-12 21:29 UTC, 0xDaedalus commented on background/services/enrichment/types.ts
> +  code: boolean
calling this property `hasCode` or `codeExists` might be a bit closer to what the comment is describing

2022-08-14 19:14 UTC, mhluongo commented
Pretty sure your patch is all we need @0xDaedalus? `sender` and `recipient` are only supposed to show up on `AssetTransfer`s and `contractInfo` is only supposed to show on `contractInteraction` after all

2022-08-15 02:25 UTC, Shadowfiend commented
> but I think its probably better to figure out the root cause

I believe this is the sticking point. Why did the types not catch this? Any thoughts?

2022-08-15 10:14 UTC, jagodarybacka commented on background/services/enrichment/transactions.ts
> +    ? transaction?.maxFeePerGas ?? 0n * (gasLimit ?? 0n)
`0n * (gasLimit ?? 0n)` isn't it always `0n`?

2022-08-15 10:19 UTC, jagodarybacka commented on background/services/enrichment/transactions.ts
> +    ? transaction?.maxFeePerGas ?? 0n * (gasLimit ?? 0n)
we want to do `maxFeePerGas * gasLimit` right? so to fix this calculation it should be:
```suggestion
    ? (transaction?.maxFeePerGas ?? 0n) * (gasLimit ?? 0n)
```

2022-08-15 10:21 UTC, jagodarybacka commented on background/services/enrichment/transactions.ts
> +    : (("gasPrice" in transaction && transaction?.gasPrice) || 0n) *
why not just:
```suggestion
    : (transaction?.gasPrice ?? 0n) *
```

2022-08-15 17:05 UTC, mhluongo commented on background/services/enrichment/transactions.ts
> +    ? transaction?.maxFeePerGas ?? 0n * (gasLimit ?? 0n)
Right you are!

2022-08-15 17:07 UTC, mhluongo commented on background/services/enrichment/transactions.ts
> +    : (("gasPrice" in transaction && transaction?.gasPrice) || 0n) *
Compiler error! `"gasPrice does not exist on..."`

2022-08-15 17:29 UTC, mhluongo commented
> I believe this is the sticking point. Why did the types not catch this? Any thoughts?

No idea. I'd expect that `EnrichedEVMTransaction["annotation"]` being a tagged union would cover this, but clearly it hasn't.

2022-08-15 19:34 UTC, mhluongo commented
I've found the offending code, but I can't for the life of me understand how the type system allowed this `undefined` through. Thoughts?

https://github.com/tallycash/extension/pull/1900/files#diff-0effdeeeba712d998d5baa16729996bd8cc9cc6815a2cb278994a6a76ffac716R92

2022-08-16 14:25 UTC, 0xDaedalus requested changes
Looks like there is an issue when sending ERC-20 tokens to an ENS name:

<img width="382" alt="image" src="https://user-images.githubusercontent.com/94649004/184904375-1a26d79b-d7d1-4d75-a34a-41829c5717a5.png">

Reference: https://polygonscan.com/tx/0x45bd67f5c15215e49b39614b9fdedd06bbef95ee1e360746c39f0687cb393a15

2022-08-16 15:55 UTC, mhluongo commented
It's worse than that @0xDaedalus → recipients aren't showing up when they should, regardless of the ENS name. Debugging

2022-08-16 16:48 UTC, mhluongo commented
It looks like the data issue comes from [`filterTransactionPropsFromUI`](https://github.com/tallycash/extension/blob/f023871299b9a75a84aefa5fe299c7ea2606e2fa/background/main.ts#L703) — maybe you understand the type ramifications better than I do here @Shadowfiend?

2022-08-16 16:54 UTC, mhluongo commented
Ah. So we have an `as` in `filterTransactionPropsFromUI` that's casting the picked-over object it returns as an `EnrichedEVMTransaction`.

Do we still want / need `filterTransactionPropsFromUI`? It's going to be an issue every time we add new enrichment data.

2022-08-16 17:10 UTC, mhluongo commented
I believe I've fixed the underlying issue, but the type info is still being swallowed. Happy to address is here if y'all have any ideas, otherwise this is ready for another look!

2022-08-16 20:05 UTC, 0xDaedalus commented
>Happy to address is here if y'all have any ideas

I am thinking the answer to our problems here is a new `TransactionForUI` type - hesitant to address it here though as this PR is already quite big

Took another look -

- sending ETH is still broken with `Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'toBigInt')
    at enrichTransactionWithReceipt (utils.ts:240:41)` showing up in the console
- sending ERC-20s works but now shows the address rather than the resolved name on the tx receipt.

2022-08-17 00:46 UTC, Shadowfiend commented
Yep. Thought about recommending that in the original filtering PR, don't remember if I had time to post the comment though. A dedicated type is the right move here, even though it will also be annoying to maintain. 

I believe we already have an ActivityItem type that can be adjusted to this.

2022-08-17 17:56 UTC, mhluongo commented
> sending ETH is still broken with [Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'toBigInt') at enrichTransactionWithReceipt (utils.ts:240:41)](https://github.com/tallycash/extension/blob/main/background/services/chain/utils/index.ts#L240) showing up in the console

I can't reproduce this, ETH sends appear to work fine on mainnet and as an ERC-20 on Polygon :thinking:

> now shows the address rather than the resolved name on the tx receipt.

Looking into this now.

2022-08-17 18:16 UTC, mhluongo commented
![Screenshot from 2022-08-17 14-14-55](https://user-images.githubusercontent.com/427505/185212854-7f151cd2-fb90-4a20-b76c-4f497efe486c.png)

Looks like that took care of the name display issue. Note this screenshot is sending ETH to myself with a Ledger on this branch @0xDaedalus — lmk if there are different reproduction steps I should be following.

Moving on to fix conflicts against `main`.

2022-08-17 18:29 UTC, mhluongo commented
Conflicts resolved if you want to give this another go @0xDaedalus. Note that I had to freehand merge the Optimism gas enrichment a bit — [this bit](https://github.com/tallycash/extension/pull/1900/commits/7af1096dccbad3ff72e1007888ae5749e1ba36a8#diff-0effdeeeba712d998d5baa16729996bd8cc9cc6815a2cb278994a6a76ffac716R172) deserves extra scrutiny.

2022-08-18 00:22 UTC, 0xDaedalus commented on background/services/enrichment/transactions.ts
> +    ? (transaction?.maxFeePerGas ?? 0n) * (gasLimit ?? 0n) + additionalL1Gas
no need for `+ additionalL1Gas` here since if its an EIP1559 tx we know its not an Optimism tx

2022-08-18 14:23 UTC, mhluongo commented on background/services/enrichment/transactions.ts
> +    ? (transaction?.maxFeePerGas ?? 0n) * (gasLimit ?? 0n) + additionalL1Gas
I 'd rather leave it in case we add other L2s that support EIP-1559, and the logic should be good regardless.

2022-08-19 20:44 UTC, 0xDaedalus approved these changes
Code looks good - tests pass - lets 🚢

2022-08-19 20:44 UTC, merged