Optimism - Live Transaction Fee Updates
tallycash/extension pull request #1973
Opened 2022-08-17 22:40 UTC by 0xDaedalus

Currently we only get a transactions estimated L1 Rollup fee when the transaction is [first added](https://github.com/tallycash/extension/blob/optimism-live-gas-updates/background/services/chain/index.ts#L383).  This means that if a user leaves the `Sign Transaction` window open for a while without interacting with it the fee preview displayed may become out-of-sync with the real fee.  This PR attempts to alleviate that.

### To Test
- [ ] Open up the sign transaction screen on Optimism (For example from a Uniswap swap)
- [ ] Make a note of what the $ amount of the fee is
- [ ] Wait 2 minutes (or less if you've set the GAS_PRICE_POLLING_FREQUENCY env var to lower than 120)
- [ ] See the $ amount of the fee change

Note: If gas prices are stable on Ethereum this may look like its not working despite in fact updating.

2022-08-17 22:42 UTC, 0xDaedalus commented on background/main.ts
> +            this.store.getState().transactionConstruction
I really do not like this but am not sure of a better way to figure out if a transactionRequest currently exists and if its on Optimism - any thoughts here?

2022-08-19 17:55 UTC, mhluongo requested changes
I think this is the wrong approach... I could be missing a resource constraint though

2022-08-19 17:55 UTC, mhluongo commented on background/main.ts
> +            this.store.getState().transactionConstruction
Maybe you don't need to know! Can't you just dispatch the action, and handle this in the reducer?

2022-08-19 17:55 UTC, mhluongo commented on background/main.ts
> +            this.store.getState().transactionConstruction
In other words: just push the information periodically from the background script. Don't discriminate on whether we need it right this second, just like any other gas information... we need it constantly.

One day we'll probably want to have a way to slow stuff like that down, but it's way easier than adding a full request/response cycle or having the background script awkwardly "look into" the redux store like this

2022-08-19 18:04 UTC, 0xDaedalus commented on background/main.ts
> +            this.store.getState().transactionConstruction
The issue is that in order to retrieve the information from the background script we need access to the transaction's `input` so we need to maintain that state somewhere and retrieve.  Right now I believe that the only place we maintain it is in redux - so its a choice between maintaining and mirroring tx state in a service - or doing this awkward pulling - both are not great tradeoffs tbh.

2022-08-21 21:29 UTC, mhluongo commented
@Shadowfiend ideas here? This solution is ikrsome... maybe we need some sort of tx request subscription from the frontend?

2022-08-24 11:20 UTC, jagodarybacka commented on background/main.ts
> +            !isEIP1559EnrichedTransactionSignatureRequest(
Do I get it right that this won't be true when they will ship bedrock release? https://help.optimism.io/hc/en-us/articles/8309198945179-What-will-change-in-bedrock-

2022-08-24 14:25 UTC, jagodarybacka commented on background/main.ts
> +            !isEIP1559EnrichedTransactionSignatureRequest(
so will we have to fix it in the future or will it fall back to EIP1559 compatible code and will work out of the box 😂 ?

2022-08-24 15:55 UTC, 0xDaedalus commented on background/main.ts
> +            !isEIP1559EnrichedTransactionSignatureRequest(
This particular line of code will need to be fixed in the future (we'll just need to remove it) - the rest of the EIP-1559 stuff _should_ more or less work out of the box but we will definitely need to do some testing to make sure that thats the case.

2022-08-29 16:20 UTC, Shadowfiend commented on background/main.ts
> +            !isEIP1559EnrichedTransactionSignatureRequest(
Not entirely clear on *why* we exclude EIP1559 here? Right now it can't be optimism AND EIP1559, right? Or is that me misunderstanding?

2022-08-29 16:36 UTC, Shadowfiend commented on background/main.ts
> +              )
It feels like we don't have to exit our current structure completely to handle this. In particular, we can change to:

```typescript
  estimatedFeesPerGas: {
    [ETHEREUM.chainID]: EstimatedGradedFeesPerGas | undefined
    [OPTIMISM.chainID]: EstimatedRollupFees | undefined
  }
```

And go from there in terms of structure.

In this scenario, the `estimatedFeesPerGas` action can become an async thunk that handles the L1 rollup fee lookup via a standard contract interaction through the internal provider.

2022-08-29 17:23 UTC, 0xDaedalus commented on background/main.ts
> +            !isEIP1559EnrichedTransactionSignatureRequest(
Good point - I think I had added it to satisfy the compiler at one point but looks like its no longer needed.

2022-08-29 17:28 UTC, mhluongo submitted a review, later dismissed

2022-08-29 17:28 UTC, mhluongo commented
Good with this as long as we're coming back to cover the tech debt later. Onward!

2022-08-29 17:42 UTC, merged