2011: complete draft of UI work for the change password feature
tallycash/extension pull request #2015
Opened 2022-08-24 21:59 UTC by rgdalessandro

This PR is a WIP (work-in-progress).
This is a draft of UI-only changes. Background changes are not yet part of this PR.

Closes #2011

**Before:**
![Screen Shot 2022-08-24 at 4 48 52 PM](https://user-images.githubusercontent.com/8944358/186529649-eef0823b-ef31-459e-a767-a798f97bb86d.png)

**After:**
![Screen Shot 2022-08-24 at 4 54 53 PM](https://user-images.githubusercontent.com/8944358/186530507-c6526fca-9fad-4937-b024-d4a8991a87c4.png)

![Screen Shot 2022-08-24 at 4 55 21 PM](https://user-images.githubusercontent.com/8944358/186530596-c8b83d7c-8395-4d57-bbfa-0e8ea404d7cb.png)

**To test:**
Set `ALLOW_CHANGE_PASSWORD = true` by adding the variable to your environment or editing the `features.ts` file.
Navigate to the Settings page and click the new link for "Change password" to see the Change Password page.

2022-08-24 22:01 UTC, rgdalessandro commented on .gitignore
> +.idea
add `.idea` folder to the `.gitignore` of users of JetBrains IDE's (such as WebStorm or IntelliJ)

2022-08-24 22:22 UTC, rgdalessandro commented on background/redux-slices/keyrings.ts
> +}
This is only a mock of the changePassword thunk which will be fleshed out in a subsequent commit.

2022-08-24 22:23 UTC, rgdalessandro commented on ui/components/Keyring/KeyringSetPassword.tsx
> +      changePassword(previousPassword, password)
This will change to `dispatch(changePassword(previousPassword, password))` once `changePassword` has been completed.

2022-08-25 13:26 UTC, 0xDaedalus commented on ui/routes/routes.tsx
> +    path: "/keyring/set-password/initial-password",
I think it might be cleaner to have these as `/keyring/set-password` and `/keyring/change-password`

2022-08-25 13:30 UTC, 0xDaedalus commented on ui/components/Keyring/KeyringSetPassword.tsx
> +              label="Previous Password"
Probably want `Current Password` here.

2022-08-25 13:40 UTC, 0xDaedalus commented on ui/components/Keyring/KeyringSetPassword.tsx
> +    ALLOW_CHANGE_PASSWORD && location.pathname.includes("change-password")
I don't think we need the feature flag here since there will be no way for users to get to this screen from settings if the ALLOW_CHANGE_PASSWORD flag is not on.

2022-08-25 21:04 UTC, mhluongo commented on background/redux-slices/keyrings.ts
> +}
Feel free to leave comments like this in commit messages, most of us read them as part of review!

2022-08-25 21:05 UTC, mhluongo commented
Nit: No need to include "WIP" anywhere when a PR is in draft!

2022-08-25 21:21 UTC, rgdalessandro commented on ui/components/Keyring/KeyringSetPassword.tsx
> +  const isInitialPassword = location.pathname.includes("initial-password")
Thank you for reviewing this PR. I do agree that simplifying the `&&` is better.

I went ahead and took care of the simplification in lines 107-120 of this file. I felt the HOC might increase complexity unnecessarily. Of course we may need to discuss this piece further.

2022-08-25 21:25 UTC, rgdalessandro commented on ui/components/Keyring/KeyringSetPassword.tsx
> +    ALLOW_CHANGE_PASSWORD && location.pathname.includes("change-password")
Good call, I have removed it from this file.

2022-08-25 21:57 UTC, 0xDaedalus reviewed
Excellent progress - really starting to take shape!

2022-08-25 21:57 UTC, 0xDaedalus commented on background/redux-slices/keyrings.ts
> +export const checkPassword = createBackgroundAsyncThunk(
I think we probably want this to be `changePassword`.  We can handle checking if the password is correct or not inside of a method we add to the keyring service.

2022-08-25 21:57 UTC, 0xDaedalus commented on background/services/keyring/index.ts
> +        this.#cachedKey = saltedKey
I don't think you'll want to overwrite the cached key when verifying a password

2022-08-25 21:57 UTC, 0xDaedalus commented on background/services/keyring/index.ts
> +  async verifyPassword(password: string): Promise<boolean> {
my spidey sense is telling me that we might want this to be a `private` method thats called from a sibling public`changePassword` method

2022-08-25 21:57 UTC, 0xDaedalus commented on ui/components/Keyring/KeyringSetPassword.tsx
> +      // TODO: how do we actually know if the current password is valid?
Take a look at https://github.com/tallycash/extension/blob/main/background/redux-slices/accounts.ts#L355:L364 for some inspiration

2022-08-26 15:52 UTC, rgdalessandro commented on background/redux-slices/keyrings.ts
> +export const checkPassword = createBackgroundAsyncThunk(
As suggested, I have renamed the action to `changePassword`

2022-08-26 15:53 UTC, rgdalessandro commented on background/services/keyring/index.ts
> +        this.#cachedKey = saltedKey
As suggested, I have removed the line of code `this.#cachedKey = saltedKey`

2022-08-26 15:54 UTC, rgdalessandro commented on background/services/keyring/index.ts
> +  async verifyPassword(password: string): Promise<boolean> {
As suggested, I have created a new class method in the keyrings service class called `changePassword` that now references `verifyPassword`. I have also made `verifiedPassword` a private class method.

2022-08-26 15:58 UTC, rgdalessandro commented on ui/components/Keyring/KeyringSetPassword.tsx
> +      // TODO: how do we actually know if the current password is valid?
I have taken a look at the link and still remain confused.

I think my main confusion here is that I see examples and understand how `background` can listen for emitter events generated by `background`, but I cannot find examples and do not understand how `ui` can listen for emitter events generated from `background`.

dispatchChangePassword() is part of `ui` but the action that generates the emitter event is in `background`. This is the problem I need to solve.

2022-08-29 12:06 UTC, jagodarybacka reviewed
Hey, nice to see your code 💖 Some comments 👇

2022-08-29 12:06 UTC, jagodarybacka commented on ui/components/Keyring/KeyringSetPassword.tsx
>  export default function KeyringSetPassword(): ReactElement {
I'm wondering if this is even a good idea to include setting and changing password within one component. A lot of additions to this file and overall logic is getting more complicated. I would rather have two components, `KeyringSetPassword` and `KeyringChangePassword` even if it means some lines will be the same in both files. This is not a change request yet, would love to hear your opinion and @0xDaedalus

2022-08-29 12:06 UTC, jagodarybacka commented on background/services/keyring/index.ts
> +  private static async verifyPassword(password: string): Promise<boolean> {
Do we need to make this method static? What is the reason? Can we make this change later if needed because right now we are only using `verifyPassword` inside its own class so it seems to me like it doesn't have to be static

2022-08-29 16:08 UTC, rgdalessandro commented on ui/pages/Settings.tsx
> +interface ISettingRow extends ReactElement {
Hello @jagodarybacka ! Thank you for reviewing this PR. You are correct, this interface is no longer needed -- nice catch!

A week ago when I started this task, it seemed to be necessary as my IDE was giving me TS errors without it. However, after several rounds of refactoring and also pulling in latest changes, it definitely seems it is not longer necessary. Thank you!

2022-08-29 16:09 UTC, rgdalessandro commented on background/main.ts
> +      }
Thank you, I have made the suggested simplification.

2022-08-29 16:13 UTC, rgdalessandro commented on background/services/keyring/index.ts
> +  private static async verifyPassword(password: string): Promise<boolean> {
My linter asked me to make this method static because there is an ESlint rule called `class-methods-use-this` which requires class methods to either use the `this` keyword somewhere in the body of the method definition or otherwise be `static`.

I seemed to have 2 options to satisfy the linter... either make the method static or add a `// eslint-disable-next-line class-methods-use-this` line. I opted to go making the method static. Totally open to discussion on this in case I should have used the `eslint-disable-next-line` approach or if there is a good way to use the `this` keyword within the body of the method definition.

2022-08-29 23:42 UTC, 0xDaedalus commented on ui/components/Keyring/KeyringSetPassword.tsx
>  export default function KeyringSetPassword(): ReactElement {
I'm inclined to agree here.  Initially I had thought we could get away with something like a `KeyringContainer` HOC but with how the useEffect is implemented I think there's a chance that could be a whole different sort of complicated.  With how absolutely application-critical the `KeyringSetPassword` component is I think in this case its worth it to be a bit less DRY and repeat some code.

2022-08-30 13:11 UTC, 0xDaedalus commented
Hey @rgdalessandro - if you can please avoid force-pushing once a PR is out of draft - makes it quite difficult for those of us who review commit-by-commit

2022-08-30 15:00 UTC, 0xDaedalus requested changes

2022-08-30 16:16 UTC, Shadowfiend commented on background/services/keyring/index.ts
> +        await this.persistKeyrings()
We will need to clear older versions of the vault out when there is a password change, or reencrypt them against the new password, otherwise the old password continues to be capable of unlocking key material. We should augment https://github.com/tallycash/extension/blob/491d9fb86e6dc26dba41b0b36ef23d11747d3c30/rfc/rfc-1-keyring-design.adoc with this information/requirement as well.

2022-08-30 16:26 UTC, Shadowfiend commented
Want to flag that it's going to be bad form in general to do security-critical background script changes (as with the keyring service) in the same PR as UI stuff. It makes it harder to review, for code that is particularly crucial to review carefully.

To that end, and I realize this is going to require a force-push in spite of @0xDaedalus's request 😅, can we please:
- Move the commits that update `background/services/keyring` to a separate PR (it can be targeted at `main` or at this branch, whichever is easiest).
- Keep this PR focused on the UI pieces.

I realize this is a bit disruptive to the workflow of actually building out the future, but I think it will be helpful to split the conversations and the review along this security boundary.

2022-08-31 15:39 UTC, rgdalessandro commented on ui/components/Keyring/KeyringSetPassword.tsx
>  export default function KeyringSetPassword(): ReactElement {
As suggested, I have split this into two separate components.

2022-08-31 15:43 UTC, rgdalessandro commented on ui/components/Keyring/KeyringSetPassword.tsx
> -          onClick={dispatchCreatePassword}
This `onClick` was removed because I found that `dispatchCreatePassword` was incorrectly firing twice. Once from the `onClick` and once from the `onSubmit` of the Form. By removing this `onClick` prop, then `dispatchCreatePassword` is now firing only once, as intended.

2022-08-31 17:41 UTC, rgdalessandro commented on ui/components/Keyring/KeyringSetPassword.tsx
> +    if (initialPasswordProvided || changePasswordSuccess) {
As suggested I have implemented `dispatch(setSnackbarMessage("Password successfully changed"))` on `changePasswordSuccess`

2022-08-31 17:43 UTC, rgdalessandro commented on ui/components/Keyring/KeyringSetPassword.tsx
> +          JSON.stringify({ currentPassword, newPassword: password })
I found the solution. I had to create a type `ChangePasswordPayload` and assign it to the `changePassword` property of  type `Event` in `keyrings.ts` to resolve this. I am no longer using any `JSON.stringified` values, only a simple JS object of type `ChangePasswordPayload`

2022-08-31 19:03 UTC, rgdalessandro commented on background/services/keyring/index.ts
> +  async changePassword(stringifiedPasswords: string): Promise<boolean> {
As requested, I have eliminated all uses of `JSON.stringify` and `JSON.parse`

2022-08-31 19:04 UTC, rgdalessandro commented on ui/components/Keyring/KeyringSetPassword.tsx
> +  }
As suggested, I have split up the UI into two separate components and have used i18n throughout.

2022-08-31 19:04 UTC, rgdalessandro commented on ui/components/Keyring/KeyringSetPassword.tsx
> +            Set Tally Ho as default wallet
Done

2022-09-02 00:13 UTC, rgdalessandro commented on ui/components/Keyring/KeyringChangePassword.tsx
> +        }
I tried to abstract these styles to a file called `styles.ts` and then referencing here them simply as `${styles}`.

However, I was unable to get `styled-jsx` to cooperate with this approach. After several attempts I decided to simply inline all these same styles in both `KeyringChangePassword.tsx` and `KeyringSetPassword.tsx`. It's not keeping the code quite as DRY but at least this approach cooperated with `styled-jsx` and the styles were applied correctly.

2022-09-05 20:38 UTC, rgdalessandro commented on background/services/keyring/index.ts
> +        await this.persistKeyrings()
As requested, `keepOnlyOneEncryptedVault()` was created to clear out all older versions of vaults and only keep the latest one after a password change.

2022-09-05 20:49 UTC, rgdalessandro commented on background/services/keyring/storage.ts
> +      version: 1,
I guessed at `version: 1` being the correct value here. Please correct me if I am wrong.

2022-09-05 21:17 UTC, rgdalessandro commented
> Want to flag that it's going to be bad form in general to do security-critical background script changes (as with the keyring service) in the same PR as UI stuff. It makes it harder to review, for code that is particularly crucial to review carefully.
> 
> To that end, and I realize this is going to require a force-push in spite of @0xDaedalus's request 😅, can we please:
> 
> * Move the commits that update `background/services/keyring` to a separate PR (it can be targeted at `main` or at this branch, whichever is easiest).
> * Keep this PR focused on the UI pieces.
> 
> I realize this is a bit disruptive to the workflow of actually building out the feature*, but I think it will be helpful to split the conversations and the review along this security boundary.

As requested, this PR has been split up into two PS's:
1) changes to the keyring service --> https://github.com/tallycash/extension/pull/2128

2) all other changes, including redux changes and `ui` changes

2022-12-07 16:13 UTC, closed without merging