Fix sending ETH on Optimism.
tallycash/extension pull request #2017
Opened 2022-08-24 23:23 UTC by 0xDaedalus

This PR allows users to send ETH to other addresses through the extension.

Things Learned:
- [ETH is an ERC-20 token on Optimism](https://optimistic.etherscan.io/token/0xDeadDeAddeAddEAddeadDEaDDEAdDeaDDeAD0000)
- We were doing rollup fee estimation incorrectly - which was causing us to overestimate gas fees and prevented transfer ETH transactions from going through once we correctly identified it as a baseAsset.

### To Test
- [ ] Attempt to send ETH to an address on Optimism.

2022-08-25 09:16 UTC, jagodarybacka commented on background/services/chain/index.ts
> +    transaction: UnsignedTransaction
is there any place that is using this function and doesn't need to run `unsignedTransactionFromEVMTransaction(transactionRequest)` before passing it as this argument? 
If there isn't - maybe it's worth moving this `unsignedTransactionFromEVMTransaction` transformation to this function?

2022-08-25 11:06 UTC, jagodarybacka requested changes

2022-08-25 11:06 UTC, jagodarybacka commented on background/constants/currencies.ts
> +  {
base asset needs homeNetwork field
https://github.com/tallycash/extension/blob/send-eth-optimism/background/services/indexing/db.ts#L67
<img width="687" alt="image" src="https://user-images.githubusercontent.com/20949277/186648042-ee84ec1a-fb6f-4013-b664-da9c3a712873.png">

2022-08-25 11:53 UTC, 0xDaedalus commented on background/constants/currencies.ts
> +  {
Hmmmmnn I was hoping to avoid changing the `NetworkBaseAsset` type any further - let me see if I find an alternative way to just adding it

2022-08-25 14:26 UTC, 0xDaedalus commented on background/services/indexing/db.ts
> +  if (!("contractAddress" in asset) || "coinType" in asset) {
@Shadowfiend curious for your take on this

2022-08-26 15:14 UTC, jagodarybacka approved these changes
Sending ETH on OP is fixed 👑

2022-08-26 15:15 UTC, merged