Add analytics settings page
tallycash/extension pull request #2058
Opened 2022-08-29 10:17 UTC by kkosiorowska

Closes #2006 

This PR displays the analytics page after clicking the button. PR includes only a visual layer, functionalities will be added in #2007 .

**Changes**
- add analytics settings page
- set back button and title is in the same line without "back" test for Analytics and Export Log page

**UI**

Analytics Settings page:
![Screenshot 2022-08-30 at 09 55 43](https://user-images.githubusercontent.com/23117945/187384453-bcc5b48e-5337-41f7-9485-2cd748e26b58.png)

Back buton and title in the same line for Export Logs page:
![Screenshot 2022-08-29 at 11 52 50](https://user-images.githubusercontent.com/23117945/187175882-afe3849a-a275-4b17-aa6e-423612af374b.png)

**To Test** 
- [ ]   Set up SUPPORT_ANALYTICS flag to true next click the analytics button on the settings page. The analytics page should open.
- [ ] Check that back button and title is in the same line without "back" text for Analytics and Export Log page

2022-08-29 11:19 UTC, jagodarybacka requested changes

2022-08-29 11:19 UTC, jagodarybacka commented on ui/_locales/en/messages.json
> +      "recordItem1": "Number of swaps / Sends",
```suggestion
      "recordItem1": "Number of swaps / sends",
```

2022-08-29 11:19 UTC, jagodarybacka commented on ui/_locales/en/messages.json
> +      "recordItem3": "Gas paied overall",
```suggestion
      "recordItem3": "Gas paid overall",
```

2022-08-29 11:19 UTC, jagodarybacka commented on ui/_locales/en/messages.json
> +      "noRecordItem1": "See/save your seed phrase",
```suggestion
      "noRecordItem1": "See / save your seed phrase",
```

2022-08-29 11:19 UTC, jagodarybacka commented on ui/_locales/en/messages.json
> +      "noRecordItem2": "Make your address and transaction",
This sentence doesn't make sense to me, why not "Your address and transactions you make" or something similar cc @VladUXUI

2022-08-29 11:19 UTC, jagodarybacka commented on ui/_locales/en/messages.json
> +      "noRecordItem2": "Make your address and transaction",
I think it's better to have more "descriptive" names for these strings without indexes

2022-08-29 13:06 UTC, kkosiorowska commented on ui/public/index.css
> +.text {
I moved this class to setting scope.

2022-08-29 13:53 UTC, jagodarybacka commented on ui/pages/Settings.tsx
> +          .text {
seems like this class is in a wrong file?

2022-08-29 13:57 UTC, kkosiorowska commented on ui/pages/Settings.tsx
> +          .text {
I moved this class to the Settings file because this class is also used by SettingsExportLogs

2022-08-29 14:12 UTC, jagodarybacka commented on ui/pages/Settings.tsx
> +          .text {
Are you sure it is still working? `styled-jsx` is not applying styles from parent component to child components by default (sometimes it is but it's a "bug") if I remember correctly

2022-08-29 20:32 UTC, 0xDaedalus commented on ui/_locales/en/messages.json
> +      "noRecordItem2": "Make your address and transaction",
I think we can get rid of the verbs here. so something like:

`Your seed phrase` 
and 
`Your address and transactions`

2022-08-30 07:06 UTC, kkosiorowska commented on ui/pages/Settings.tsx
> +          .text {
Good point. I'll move the styles to the global scope, but rename the class so that it doesn't conflict with the others.

2022-08-30 07:33 UTC, kkosiorowska commented on ui/_locales/en/messages.json
> +      "noRecordItem2": "Make your address and transaction",
One point.  What is the final decision and who should decide about this texts?

2022-08-30 07:45 UTC, VladUXUI commented on ui/_locales/en/messages.json
> +      "noRecordItem2": "Make your address and transaction",
Yeah, that was a slippage in text, don't think anybody really checked it ?:)
Let's go with what @0xDaedalus proposed, as that seems the shortest and ties in to the "title"

2022-08-30 07:49 UTC, VladUXUI commented on ui/_locales/en/messages.json
> +      "recordItem3": "Gas paied overall",
Here let's also write Swaps insted of swaps

2022-08-30 08:09 UTC, kkosiorowska commented on ui/_locales/en/messages.json
> +      "noRecordItem2": "Make your address and transaction",
Vlad approved the texts below:
![Screenshot 2022-08-30 at 09 55 43](https://user-images.githubusercontent.com/23117945/187384764-13696c6f-f10f-4b85-afdb-a8f028d82d1b.png)

2022-08-30 13:46 UTC, Shadowfiend commented on ui/components/Shared/SharedBackButton.tsx
> +  withoutBackText?: boolean
Wondering if in future work we should consider just using `children`, and making existing uses explicitly do `<SharedBackButton...>Back</SharedBackButton>`. It seems overall clearer to me, but could see arguments in either direction.

Anyway, obviously not blocking :)

2022-08-31 06:28 UTC, kkosiorowska commented on ui/components/Shared/SharedBackButton.tsx
> +  withoutBackText?: boolean
I think this is a good point. Maybe, we should create another task for this which should describe how this component should looks like for pages because this task was only about the analytics settings page.

2022-08-31 09:40 UTC, jagodarybacka approved these changes
Looks good 💖

2022-08-31 09:40 UTC, merged