Add all new accounts to all networks
tallycash/extension pull request #2090
Opened 2022-08-31 16:22 UTC by jagodarybacka

Resolves #1864

### What
- Add all types of accounts to all supported networks at once.
- Refactor add account methods to avoid code duplication.
### Testing
- add multiple accounts of all types - import, read only, Ledger - to the wallet and make sure they are visible on the accounts list no matter what chain is selected

![image](https://user-images.githubusercontent.com/20949277/187729083-82d5c5d8-d5b2-42c7-92a3-e9b303c029c6.png)

2022-08-31 16:26 UTC, mhluongo requested changes
I think you and @0xDaedalus need to get aligned here

2022-08-31 16:26 UTC, mhluongo commented on background/main.ts
> +        await this.chainService.addAccountToTrack(addressNetwork)
Left and right hands are fighting here @jagodarybacka. This is the opposite of what we want to do for performance.

2022-08-31 16:26 UTC, mhluongo commented on background/main.ts
> +        await this.chainService.addAccountToTrack(addressNetwork)
Instead, I recommend we add a layer of indirection in Redux... where we have all `addressNetworks` to select from, but only those chosen get added to `accountsToTrack` in the background script

2022-09-01 09:37 UTC, jagodarybacka commented on background/main.ts
> +        await this.chainService.addAccountToTrack(addressNetwork)
I'm aware that adding accounts to track to all supported chains at once means more performance problems. But what this PR is changing is only adding read-only accounts the same way we add imported and Ledger accounts. I agree we need a better way to optimize tracking accounts but I think having all types of accounts behave the same way will be a good first step. Then we can improve adding accounts to track.

2022-09-01 13:31 UTC, 0xDaedalus commented on background/main.ts
> +        await this.chainService.addAccountToTrack(addressNetwork)
I'm inclined to agree with Matt here.  While it would be nice to have all accounts behaving the same way what we want is a fix that doesn't impede our scaling and that we can extend to imported and ledger accounts in a subsequent PR.

2022-09-01 16:28 UTC, jagodarybacka commented
I'm merging my work from this PR with @0xDaedalus PR - https://github.com/tallycash/extension/pull/2100

2022-09-01 16:28 UTC, closed without merging