Reflective Ledgend: Add Ledger signing flow to new signing UI
tallycash/extension pull request #2253
Opened 2022-09-19 21:33 UTC by Shadowfiend

The Ledger signing UI is a bit closer to the original designs,
displaying an image corresponding to the current ledger connection
state throughout the signing flow. Once `Sign` is clicked, the
signing UI also displays something that is as close as possible to
what the Ledger will display for easier verification, instead of
another Tally-specific summary of the signing details.

2022-09-20 03:37 UTC, Shadowfiend commented
All righty folks I believe this one is ready to go!

2022-09-20 17:17 UTC, mhluongo commented
Without the flag

![Screenshot from 2022-09-20 12-21-49](https://user-images.githubusercontent.com/427505/191322591-b7490267-1aae-476f-8231-5fa43cf28fc0.png)
![Screenshot from 2022-09-20 12-22-01](https://user-images.githubusercontent.com/427505/191322605-c9b9c461-d9bf-45bf-a154-4fcbc3a4fe6b.png)

and with it

![Screenshot from 2022-09-20 12-19-10](https://user-images.githubusercontent.com/427505/191322647-be221e5a-7756-4400-be0f-c85d735dd499.png)

![Screenshot from 2022-09-20 12-20-31](https://user-images.githubusercontent.com/427505/191322661-cab2026d-2046-409c-b124-b2b9f0227932.png)

![Screenshot from 2022-09-20 12-20-45](https://user-images.githubusercontent.com/427505/191322676-1f723ff1-c52c-42ee-8adf-efd8e3a4910b.png)

In that last screen, I'd love to see the proper address component being used (linked and maybe ellided, etc) but otherwise it looks good.

2022-09-20 17:25 UTC, mhluongo requested changes
Really want to see the i18n land. Otherwise appears good to go!

2022-09-20 17:25 UTC, mhluongo commented on ui/components/Signing/Signer/SignerLedger/SignerLedgerConnectionStatus.tsx
> +            alt="Ledger is connected but cannot sign"
I'd like to see us lean in to i18n here → trying to move to only merging PRs that do it properly

2022-09-20 18:51 UTC, Shadowfiend commented
> In that last screen, I'd love to see the proper address component being used (linked and maybe ellided, etc) but otherwise it looks good.

We can add linking, but reusing that component is probably the wrong move. The goal of this screen is to be as close to the Ledger display as possible rather than facilitate understanding, and that will likely deviate from the goals of the shared address component that's meant to make addresses easier for the user to understand. Open to a different take though.

2022-09-20 20:01 UTC, mhluongo commented
> The goal of this screen is to be as close to the Ledger display as possible rather than facilitate understanding, and that will likely deviate from the goals of the shared address component that's meant to make addresses easier for the user to understand.


I agree with your rationale on wanting to show the full thing. Maybe the `SharedAddress` just needs a "no shortening" prop? I suspect this will come up elsewhere as well.

2022-09-21 11:55 UTC, Shadowfiend commented
I think the fundamental goals are different enough that it would need to be a different component, even if still a shared one. We've already seen how mixed goals can lead to extremely messy components with the SharedButton leviathan.

2022-09-21 21:14 UTC, Shadowfiend commented
I've unchecked all test checkboxes as the i18n requires rechecking everything :/ I also fixed a bug where SIWE messages in particular were being presented as hex on the Ledger signing confirmation screen and as normal UTF-8 text on the Ledger itself. This is fixed by carrying the original UTF-8 message alongside the parsed SIWE data when dealing with signing data, which is then used to feed the correct display for the Ledger signing confirmation.

The full Ledger flow should now be i18ned, with two keys moved from `signTransaction` to `ledger` in the messages JSON.

2022-09-22 19:01 UTC, mhluongo approved these changes
Very excited seeing this move along!

2022-09-22 19:03 UTC, merged