🧱 New activities redux slice
tallycash/extension pull request #2311
Opened 2022-09-27 15:50 UTC by jagodarybacka

2022-10-05 09:42 UTC, hyphenized reviewed
Amazing work! I really like the cleanup in `activities-utils` 👏.

For the issue with the UNS name resolution, we could increase the time [here](https://github.com/tallycash/extension/blob/6d855c4eabf95e609271561eaf9862a8222f0b7a/background/services/name/resolvers/uns.ts#L10) to a longer period, however, we might run into other issues with trying to enrich all 25 transactions at once.

2022-10-05 09:42 UTC, hyphenized commented on ui/components/Wallet/WalletActivityDetails.tsx
> -        <div className="value_detail">{valueDetail}</div>
Should be good to remove the unused classes too (unless we need them for some reason)

2022-10-05 09:42 UTC, hyphenized commented on ui/components/Wallet/WalletActivityDetails.tsx
> +  }, [activityItem.hash, dispatch])
Nice! I didn't know you could do this with Redux. Nevertheless, it feels a bit weird because we're only using Redux as a proxy to the main service 🤔 . Additionally, should we check if the activity comes from an enriched transaction here?

2022-10-05 13:39 UTC, jagodarybacka commented on background/main.ts
> +          this.enrichActivities(addressNetwork)
Unfortunately no it won't work, I see it is sometimes replacing enriched activities with not enriched - but now I think I'm triggering initialization from database for new accounts in the wrong place. Very tricky 😕

2022-10-05 13:44 UTC, jagodarybacka commented on ui/components/Wallet/WalletActivityDetails.tsx
> +  }, [activityItem.hash, dispatch])
This will be always enriched as this is included in the function in main.

Redux as a proxy - my first approach was to save it in the redux state but as we don't want to cache the result and we want to keep the redux state in a minimal required size - I think it is the best solution right now

2022-10-10 14:09 UTC, jagodarybacka commented on background/main.ts
> +          this.enrichActivities(addressNetwork)
As I made a little refactor I still think it's better to leave it here as `enrichAcitivities` shouldn't do any unnecessary work (it won't enrich activities twice)

2022-10-10 16:20 UTC, greg-nagy requested changes
This is a wonderful and mindbending PR 🤩

The blocking requests are the activity number and the memoization of hte tx enrichment.

2022-10-10 16:20 UTC, greg-nagy commented on background/main.ts
> +      const enrichedTransaction =
Hm, the memoization should probably happen inside the `enrichedTransaction` function so 
the caching works both here and for the detail view.

2022-10-10 16:20 UTC, greg-nagy commented on background/services/chain/db.ts
> +  async getAllTransactions(): Promise<Transaction[]> {
This might worth to be improved with a `transactionByChainLimit` parameter that's calculated by grouping by network then desc ordering by nonce and cut at the limit. 

Now it's a non issue.

2022-10-11 10:34 UTC, jagodarybacka commented on background/redux-slices/migrations/to-13.ts
> +export const transactionPropertiesForUI = [
but it is "to-13" - do I assume correctly that migrations will run one by one if some user is on 12th version of redux store? So in theory we still need this otherwise some users may be stuck on failed migrations?

2022-10-11 11:37 UTC, jagodarybacka commented on background/services/chain/db.ts
> +    return transactions.filter(
I just had the same code here and above in `getTransactionsForNetwork`. I needed `getTransactionsForNetwork` in the chain service [here](https://github.com/tallycash/extension/blob/new-activities-slice/background/services/chain/index.ts#L1500)

2022-10-11 11:42 UTC, jagodarybacka commented on background/services/chain/db.ts
> +  async getAllTransactions(): Promise<Transaction[]> {
Yeah but I don't see a clear advantage of sorting and cutting emitted transactions here + doing the same thing in the redux slice. 
I even think it is better to keep the logic of redux activities slice there and avoid leaking it to chain service if this is possible.

2022-10-11 12:23 UTC, greg-nagy commented on background/services/chain/db.ts
> +  async getAllTransactions(): Promise<Transaction[]> {
The advantage of limiting this is that we can avoid augmenting unseen transactions through the enrichment service on initialization. Eg if we have 1000 tx for every address on every network it will enrich 4000 txs at the moment on initialization. 

This probably won't be an issue for most of the wallets, but preparing for manifest v3 we need to be conscious about startup time. 

> Yeah but I don't see a clear advantage of sorting and cutting emitted transactions here + doing the same thing in the redux slice.

The reason for this is if we do it here we can optimize for startup time. 

We need to keep it in the redux slice because txs can come in in any order at wallet startup time and we need to sort them properly. 

Another approach is to limit the enrichment to happen only when the UI becomes visible.

Anyhow I don't see this as a blocker, but def want to pay attention to it during QA

2022-10-11 12:29 UTC, greg-nagy commented on background/services/chain/db.ts
> +    return transactions.filter(
What I meant to say is that doing the same in dexie query is probably more efficient than grabbing the data and doing the filtering in js. Another approach could have been to separate the query from the data fetching and reuse and extend the query here. 

```
  async getTransactionsForNetworkQuery(network: Network): Promise<Transaction[]> {
    return this.chainTransactions
      .where("network.name")
      .equals(network.name)
  }


  async getTransactionsForNetwork(network: Network): Promise<Transaction[]> {
    return this.getTransactionsForNetworkQuery(network)
      .toArray()
  }

 async getNetworkPendingTransactions(
    network: Network
  ): Promise<(AnyEVMTransaction & { firstSeen: UNIXTime })[]> {
    const transactions = await this.getTransactionsForNetwork(network)
      .filter(
              (transaction) =>
                !("status" in transaction) &&
                (transaction.blockHash === null || transaction.blockHeight === null)
            )
            .toArray()
...
```

2022-10-11 12:36 UTC, greg-nagy commented on background/main.ts
> +      const enrichedTransaction =
[An example for memoization](https://github.com/tallycash/extension/blob/901dc634e25c83bf88bc491d96b670da08a0bd0e/background/lib/token-lists.ts#L150-L157)

2022-10-11 12:44 UTC, jagodarybacka commented on background/services/chain/db.ts
> +  async getAllTransactions(): Promise<Transaction[]> {
> we have 1000 tx for every address on every network it will enrich 4000 txs at the moment on initialization

Desired behaviour is that only transaction saved in the redux slice will become enriched. If this is not the case then it's a bug. This [selector](https://github.com/tallycash/extension/blob/new-activities-slice/background/redux-slices/selectors/activitiesSelectors.ts#L14) should make sure it is not enriching transactions twice.

2022-10-11 12:47 UTC, jagodarybacka commented on background/redux-slices/migrations/to-13.ts
> +export const transactionPropertiesForUI = [
I think that regardless of the choice of leaving it here or not we should test migrations as deep as we can 😄

2022-10-11 14:08 UTC, greg-nagy commented on background/services/chain/db.ts
> +  async getAllTransactions(): Promise<Transaction[]> {
Ok, I have missed this part. And I am amazed 🤩

The only duplicated enrichment happens only when the user clicks an activity for details. I think that's acceptable.

2022-10-11 14:08 UTC, greg-nagy commented on background/redux-slices/migrations/to-13.ts
> +export const transactionPropertiesForUI = [
I don't have a strong opinion on what should happen here.

2022-10-11 16:31 UTC, greg-nagy commented on background/main.ts
> +      const enrichedTransaction =
Now that I am thinking about it, this is more a nice to have then a blocker.

2022-10-11 16:32 UTC, greg-nagy submitted a review, later dismissed

2022-10-12 14:12 UTC, greg-nagy approved these changes
This is lookin' good! 

Let's merge and pray for the QA gods 📿

2022-10-12 14:12 UTC, merged

2022-10-13 06:32 UTC, hyphenized commented on ui/components/Wallet/WalletActivityDetails.tsx
> +  }, [activityItem.hash, dispatch])
> Redux as a proxy - my first approach was to save it in the redux state but as we don't want to cache the result and we want to keep the redux state in a minimal required size - I think it is the best solution right now. We are already doing something like this with name resolution.

I agree, this made me rethink that maybe it would be easier for us to develop in the future if we had a way to grab the data we needed without having to go through the redux store, but I am still not 100% sure whether that will improve overall development experience or not.