LOD-ing: Add data signing details to new signing flow
tallycash/extension pull request #2312
Opened 2022-09-27 16:15 UTC by Shadowfiend

> [In computer graphics, **level of detail** (**LOD**) refers to the complexity of a 3D model representation.[1][2][3] LOD can be decreased as the model moves away from the viewer or according to other metrics such as object importance, viewpoint-relative speed or position. LOD techniques increase the efficiency of rendering by decreasing the workload on graphics pipeline stages, usually vertex transformations. The reduced visual quality of the model is often unnoticed because of the small effect on object appearance when distant or moving fast.](https://en.wikipedia.org/wiki/Level_of_detail_(computer_graphics))
> 
> [Although most of the time LOD is applied to geometry detail only, the basic concept can be generalized. Recently, LOD techniques also included shader management to keep control of pixel complexity. A form of level of detail management has been applied to texture maps for years, under the name of mipmapping, also providing higher rendering quality.](https://en.wikipedia.org/wiki/Level_of_detail_(computer_graphics))
>
> [It is commonplace to say that "an object has been LOD-ed" when the object is simplified by the underlying LOD-ing algorithm as well as a 3D modeler manually creating LOD models.](https://en.wikipedia.org/wiki/Level_of_detail_(computer_graphics))

This PR adds details for data (typed and not) signing to the new signing flow. Once again we reuse existing components where reasonable, with a few small tweaks to allow for the new structure around them. The framing is set up so that both types of data signing have a common frame, in line with the design's consistency between these, and internal usage of components is improved a bit.

A few other small improvements specific to the new signing flow:
- Addresses are displayed using the `SharedAddress` component.
- The external link icon aligns with the design color-wise, and uses the
  `SharedIcon` component.
- Padding, dividers, and other spacing details have been aligned to the
  existing design, and generally look better.

<details>
  <summary>Screenshots!</summary>

  <img width="496" alt="Sign In With Ethereum in the new signing flow" src="https://user-images.githubusercontent.com/8245/192578877-b48e606a-7e98-4c7c-8286-328b6ffd1728.png">
  <img width="496" alt="Regular message signing in the new signing flow" src="https://user-images.githubusercontent.com/8245/192579169-7a7fceea-6cee-41ad-b798-40783a14b4be.png">
  <img width="496" alt="Typed Data signing in the new signing flow" src="https://user-images.githubusercontent.com/8245/192578986-aa824b94-a636-4f6b-8694-e7fb8d1b6a59.png">
  <img width="496" alt="Sign In With Ethereum in the new signing flow with a Ledger account" src="https://user-images.githubusercontent.com/8245/192579593-1a0f21b0-1336-48c3-9050-5ca44dcc993b.png">
</details>

## Testing

- [ ] All of this should be behind a feature flag. Ensure signing data is unchanged with the feature flag disabled.
  - [ ] Check Sign In With Ethereum signatures still look visually consistent. Can be checked at https://login.xyz/ under Get Started.
  - [ ] Check regular message signing still looks visually consistent. Can be checked at https://mintkudos.xyz/ on Polygon by hitting Connect Wallet.
  - [ ] Check typed data signing still looks visually consistent. Can be checked at https://app.uniswap.org/#/swap trying to swap from USDC using the Tally test wallet by clicking “Allow the Uniswap Protocol to use your USDC”. Do not confirm this signature so that it remains a viable test path for below.
- [ ] Enabling the feature flag, ensure that each type of data signing has its summary data displayed correctly.
  - [ ] Sign In With Ethereum. Can be checked at https://login.xyz/ under Get Started. Spacing should be tighter (see above).
  - [ ] Check regular message signing still looks visually consistent. Can be checked at https://mintkudos.xyz/ on Polygon by hitting Connect Wallet.
  - [ ] Check typed data signing still looks visually consistent. Can be checked at https://app.uniswap.org/#/swap trying to swap from USDC using the Tally test wallet by clicking “Allow the Uniswap Protocol to use your USDC”. Do not confirm this signature so that it remains a viable test path for later.
  - [ ] Try all of the above with a Ledger account and ensure the Ledger connection status appears above.

2022-09-27 16:29 UTC, Shadowfiend commented
Btw, note the Unknown Network for typed data signing—this seems to be an issue in the current flow as well, and I haven't dug into it yet.

2022-09-27 17:21 UTC, 0xDaedalus requested changes
Looks good - the only think I'd want to block on is reworking the types a bit to get rid of the `as` typecasting.

2022-09-27 17:21 UTC, 0xDaedalus commented on ui/components/SignData/EIP4361Info.tsx
> +const EIP4361Info: React.FC<{
Should we stick to the pattern of `(): React Element => ...` here rather than using `React.FC`?

2022-09-27 17:21 UTC, 0xDaedalus commented on ui/components/Signing/SignatureDetails/DataSignatureDetails/MessageDataSignatureDetails.tsx
> +          requestingSource={(messageRequest.signingData as EIP4361Data).domain}
Can we make `SignDataRequest` into a union type of two newly defined types `EIP191SignDataRequest` and `EIP4361SignDataRequest`?  I think that lets us avoid the `as` here which has traditionally been a core source of bugs / regressions for us.

2022-09-27 17:21 UTC, 0xDaedalus commented on ui/components/Signing/SignatureDetails/DataSignatureDetails/TypedDataSignatureDetails.tsx
> +          ariaLabel="View Address on Etherscan"
I think this should be internationalized

2022-09-27 17:21 UTC, 0xDaedalus commented on ui/components/Signing/SignatureDetails/DataSignatureDetails/TypedDataSignatureDetails.tsx
> +              .open(`https://etherscan.io/address/${value}`, "_blank")
Does this need to be network aware?  I think the answer is right now is no b/c signing typed data is itself somewhat network agnostic - but maybe we want to respect whatever network the user currently has selected in the wallet?

2022-09-27 17:21 UTC, 0xDaedalus commented on ui/components/Signing/SignatureDetails/DataSignatureDetails/TypedDataSignatureDetails.tsx
> +
```suggestion
```

2022-09-27 17:21 UTC, 0xDaedalus commented on ui/components/Signing/SignatureDetails/DataSignatureDetails/index.tsx
> +          {excludeTitle ?? false ? (
might I suggest adding `excludeTitle = false` on line 13 and getting rid of `?? false` here?

2022-09-29 11:36 UTC, Shadowfiend commented on ui/components/SignData/EIP4361Info.tsx
> +const EIP4361Info: React.FC<{
This is existing code so I'm not touching it for now. 

And yes, it hurts me :)

2022-09-29 11:38 UTC, Shadowfiend commented on ui/components/Signing/SignatureDetails/DataSignatureDetails/MessageDataSignatureDetails.tsx
> +          requestingSource={(messageRequest.signingData as EIP4361Data).domain}
This pattern is existing and baked a little deeper than I wanted to go into for unrelated work. Changing it would involve changing the existing flow more than I was comfortable doing in order to move fast on finishing this. 

Deciding not to do this was also painful 😅

2022-09-29 11:42 UTC, Shadowfiend commented
> the only think I'd want to block on is reworking the types a bit to get rid of the as typecasting

Mentioned this in direct replies, but it you basically hit on the refactoring I considered big enough and not on the critical path for this feature. If you really want to block, I can fix them, but they're already on the existing code path and I don't think we gain in terms of delivering this feature by reworking the type structure here. 

They are, however, definitely on my hit list 😁

2022-09-29 16:36 UTC, Shadowfiend commented on ui/components/Signing/SignatureDetails/DataSignatureDetails/TypedDataSignatureDetails.tsx
> +
… Man I strongly disagree here but we've ignored any sort of functional grouping of CSS style parameters across the board, and we don't have stylelint or similar prettier plugin in the mix, so… Fine.

2022-09-29 16:40 UTC, Shadowfiend commented
Fixed the other tidbits.

2022-09-29 21:11 UTC, 0xDaedalus commented on ui/components/Signing/SignatureDetails/DataSignatureDetails/MessageDataSignatureDetails.tsx
> +          requestingSource={(messageRequest.signingData as EIP4361Data).domain}
In that case how would you feel about me adding a commit to this branch that addresses this comment?

I really _really_ do not want to add anymore `n as x` to the codebase.

Alternatively we can create an issue to address this that blocks us flipping the feature flag on until it is resolved

2022-09-29 21:39 UTC, Shadowfiend commented on ui/components/Signing/SignatureDetails/DataSignatureDetails/MessageDataSignatureDetails.tsx
> +          requestingSource={(messageRequest.signingData as EIP4361Data).domain}
Latter option with the blocking issue seems perfect.

2022-09-29 23:40 UTC, 0xDaedalus approved these changes
👑

2022-09-29 23:40 UTC, merged