Implemented all todo
tallycash/extension pull request #2317
Opened 2022-09-27 21:36 UTC by ManyRios

Please leave a feedback if a change is needed

2022-09-27 22:27 UTC, 0xDaedalus requested changes
This looks great!  Just a few things to tidy up here.

Also would you mind amending the commit name to "add chainService db integration tests"

2022-09-27 22:27 UTC, 0xDaedalus commented on background/services/chain/tests/db.integration.test.ts
> +      expect(getEthTransaction?.hash).toBeTruthy()
```suggestion
      expect(getEthTransaction?.hash).toEqual(addTransactionEth.hash)
```

2022-09-27 22:27 UTC, 0xDaedalus commented on background/services/chain/tests/db.integration.test.ts
> +      expect(getOptTransaction?.hash).toBeTruthy()
expect(getOptTransaction?.hash).toEqual(addTransactionOpt.hash)

2022-09-27 22:27 UTC, 0xDaedalus commented on background/services/chain/tests/db.integration.test.ts
> +      expect(updateOpt).toBeTruthy()
Can we assert here that `updateEth` and `updateOpt` have a different `gasPrice` than `getEthTransaction` and `getOptTransaction` - respectively?

2022-09-27 22:27 UTC, 0xDaedalus commented on background/services/chain/tests/db.integration.test.ts
> +      expect(allTransactions.map((tx) => tx)).toBeTruthy()
I think this is always going to be true since we're asserting the truthiness of what the `.map` function returns.

I think we can consolidate this assertion with the one above it into something like:

```
expect(allTransactions.filter(key => !!key)).toHaveLength(4)
```

2022-09-27 22:27 UTC, 0xDaedalus commented on background/services/chain/tests/db.integration.test.ts
> +    /* Creating two blocks. */
Duplicate comment

2022-09-27 22:27 UTC, 0xDaedalus commented on background/services/chain/tests/db.integration.test.ts
> +      const account = createAccountBalance()
I think it might make sense to call this variable `accountBalance`

2022-09-27 22:27 UTC, 0xDaedalus commented on background/services/chain/tests/db.integration.test.ts
> +      }
The assertion logic here does not make much sense to me - I think we want to check if if the timestamp is `less` than `86 seconds ago` and I don't expect the assertion of `epect(block).toBeNull()` to ever pass since we define `const block = createAnyEVMBlock()` on line 213

2022-09-27 22:27 UTC, 0xDaedalus commented on background/services/chain/tests/db.integration.test.ts
> +      }) // check for both hash and network mismatch
We can rm this comment

2022-09-27 22:27 UTC, 0xDaedalus commented on background/services/chain/tests/db.integration.test.ts
> +      const block2 = createAnyEVMBlock()
I think we can define these inside of their respective `it` clauses

2022-09-28 01:10 UTC, ManyRios commented on background/services/chain/tests/db.integration.test.ts
> +      }
I made another implementation, the database already filter with its query this. If I'm in a mistake please let me now

2022-09-28 17:29 UTC, ManyRios commented
All good here?

2022-09-29 08:22 UTC, ManyRios commented
😁

2022-09-29 18:16 UTC, 0xDaedalus commented
Looks good - we'll process the gitcoin bounty in a couple of days!

2022-09-29 18:16 UTC, 0xDaedalus approved these changes

2022-09-29 18:19 UTC, merged