Cache token lists assets lookups
tallycash/extension pull request #2319
Opened 2022-09-28 00:29 UTC by hyphenized

We had multiple indirect calls to `getCachedAssets` which was causing another bottleneck. Furthermore, these calls caused up to 130~ hits (per network) to indexed db for `tokenLists` and `customAssets`. This significantly increased average load during initialization and during updates to cached asset data from token lists.

One of the reasons this also affected initialization was that once the chain service starts it emits a `newAccountToTrack` event for each active network. This triggers an event handler in the index service to retrieve token balances which was also run at service initialization through `handleTokenAlarm`

The difference should be more noticeable the more active networks there are for a given account.

## Results
Before(2.4mins):
![pre](https://user-images.githubusercontent.com/28708889/192659388-4381a8bd-ecd8-4a79-a4a1-54a0f7737006.jpg)

After(2.6mins):
![post](https://user-images.githubusercontent.com/28708889/192659427-cc05c1fd-13a4-4aba-ab35-b72316811c3f.jpg)

`guardedCallback`/dexie blocking due to IDB lookups is almost gone entirely, garbage collector also gets breathing room 🚀 

These tests were done on the `test test test...` account with Ethereum as the only active network. 
## To Test:

- [ ] Pause script execution, start profiling and reload the background page
- [ ] Wait a couple of minutes to trigger `handleTokenAlarm` a few times
- [ ] Do the same without the changes introduced in this PR

2022-09-28 12:13 UTC, greg-nagy requested changes
This PR is wonderful, and I think overall this is the good direction!

The only blocker is the duplicate initialization step.

The rest is not strictly related to this PR 

The current state worries me. We have 3 caching layer in code/in db caching, memoization and now an in memory cache. Debugging caching is the hardest thing tbh. 

Eg. 

The indexingDB > `tokenList` won't change after initialization [see `fetchAndCacheTokenLists`](https://github.com/hyphenized/tally-cash/blob/eb647e96a75d337c4396293aa87ed32aad06401e/background/services/indexing/index.ts#L714) (more precisely if there is a token list with the same url in the db)

We either should start getting the fresh content from the token lists or we should simplify the flow. I think we should start getting the fresh content. 

We should really unify these caching layers and keep as few as possible. I am in favor of keeping only this in memory layer. 

A non-blocking/toughtprovoking question to @hyphenized 
This PR esentially caches the `customAssets` and the `tokenLists`, because the `memoizedMergeAssets` is already cached. 

```
    const customAssets = await this.db.getCustomAssetsByNetwork(network)
    const tokenListPrefs =
      await this.preferenceService.getTokenListPreferences()
    const tokenLists = await this.db.getLatestTokenLists(tokenListPrefs.urls)
```

Would it make sense/be less complex if we would store those 2 things in memory and refresh through the modifying methods?

It's a non-blocking question, because this is only about which level we want to cache.

2022-09-29 04:10 UTC, hyphenized commented on background/services/indexing/index.ts
> +        Promise.resolve([]),
My intent here was to not change the API for the other references and to force other asynchronous operations to wait for access to the cache entry if there's an update in progress (If my understanding is correct, between the awaits in the `cacheAssetsForNetwork` something could try to access a soon to be stale entry). However I've realized now that this a bit overkill so we can safely change this to not use promises 😄

2022-09-29 04:11 UTC, hyphenized commented on background/services/indexing/index.ts
> +      activeNetworks.forEach(async (network) => {
Yes, but there can be a significant amount of time until `fetchAndCacheTokenLists` starts to fills the cache. This just grabs whatever is already in the db and sends that for display. But, now that you mention it, this might be unnecessary if assets are already stored in the redux state cache 🤔

2022-09-29 04:13 UTC, hyphenized commented on background/services/indexing/index.ts
> +      const activeNetworks = await this.chainService.getActiveNetworks()
The goal of using `.once("serviceStarted")` was to prevent two calls in parallel to `getActiveNetworks` (which also activates networks), upon giving another look I think the last bit
```ts
      // ... and kick off token list fetching
      await this.fetchAndCacheTokenLists()
```
Would be better off without an await outside the block, to start fetching token lists in the background without blocking service initialization

2022-09-29 04:45 UTC, hyphenized commented
> A soft-blocker: We are in the process of improving our test coverage. It would be really fantastic if you would add at least some tests around these changes. Mostly because testing caching is hard.

For sure!

> The current state worries me. We have 3 caching layer in code/in db caching, memoization and now an in memory cache. Debugging caching is the hardest thing tbh.
> ...
> 🤔💭A non-blocking/toughtprovoking question to @hyphenized This PR esentially caches the `customAssets` and the `tokenLists`, because the `memoizedMergeAssets` is already cached.

I think it's safe to remove memoization from `memoizedMergeAssets` now given it's not running as much as before

> 
> ```
>     const customAssets = await this.db.getCustomAssetsByNetwork(network)
>     const tokenListPrefs =
>       await this.preferenceService.getTokenListPreferences()
>     const tokenLists = await this.db.getLatestTokenLists(tokenListPrefs.urls)
> ```
> 
> Would it make sense/be less complex if we would store those 2 things in memory and refresh through the modifying methods?
> 
> It's a non-blocking question, because this is only about which level we want to cache.

It could work but I fear it might add cognitive load for developers working on this through 6 new methods. If I'm correct, if we cached those two accesses alone we'd also need to cache `tokenListPrefs` too. Because most of the callers are interested in the result of this function it made more sense to cache the result in memory 👀

2022-09-29 16:13 UTC, greg-nagy approved these changes
this is looking good and want it to be in the next release 🤩

ty, let's 🚢

2022-09-29 16:16 UTC, greg-nagy commented on background/services/indexing/index.ts
> +      activeNetworks.forEach(async (network) => {
The redux cache will probably change soon because that's another bottleneck for us. 
I think this approach is good here

2022-09-29 16:16 UTC, merged

2022-09-29 16:17 UTC, greg-nagy commented on background/services/indexing/index.ts
> +        Promise.resolve([]),
Now I see the meaning behind this, which is definitely a good thing to consider. I also agree with your conclusion.

2022-09-29 16:24 UTC, greg-nagy commented
> It could work but I fear it might add cognitive load for developers working on this through 6 new methods. If I'm correct, if we cached those two accesses alone we'd also need to cache tokenListPrefs too. Because most of the callers are interested in the result of this function it made more sense to cache the result in memory 👀

`tokenListPrefs` wouldn't have been necessary because the `tokenList` is what we really care about and it's derived from that. 

The solution I would have done if we choose that path is to have those 2 variables in memory, update the memory cache on modification through method calls — just like you did — and memoize the `getCachedAssets` and use the in-memory variables for cache invalidation logic. This would have saved us from needing to implement the in-memory caching ourselves. Otoh, it's a lower level caching with more input than your solution, which has a higher maintenance cost. 

I really love the solution you have implemented!
And I also appreciate the thoughts in this review :)