Add path to query ERC-20 balances on any evm compatible chain.
tallycash/extension pull request #2423
Opened 2022-10-13 13:22 UTC by 0xDaedalus

This PR adds the ability to query up to 500 erc-20 token balances via one `eth_call` rpc request.  This is much more resource and cost-effective than sending many individual calls to a given contract's `getBalance` function and should allow us to add additional providers that do not support [alchemy_getTokenBalances](https://docs.alchemy.com/reference/alchemy-gettokenbalances)

Highlights:
- New dependency: [`ethereum-multicall`](https://www.npmjs.com/package/ethereum-multicall)
- SerialFallbackProvider now accepts a JsonRPCProvider as its primary provider.
- Added an additional fallback provider for polygon.
- Added a method to get all known (via tokenlist) tokens for a given network.
- The code paths added here do not exist any existing functionality since all of our currently supported networks are also supported by alchemy.

### To Test
- [ ] replace the code at the top of `makeSerialFallbackProvider` with:
```
  if (network.chainID === POLYGON.chainID) {
    return new SerialFallbackProvider(
      network,
      () => new JsonRpcProvider("https://polygon-rpc.com")
    )
  }
  ```
- [ ] Reinstall wallet
- [ ] Import an account
- [ ] Select Polygon chain
- [ ] ERC-20 balances should load
- [ ] Inspect the network tab in devtools - you should see http requests going out to `https://polygon-rpc.com`

2022-10-13 15:36 UTC, mhluongo commented
:fire:

2022-10-13 15:54 UTC, mhluongo reviewed
Love the approach. Will review more deeply soon, but wanted to kick off the discussion around whether we can avoid the `ethereum-multicall` lib

2022-10-13 15:54 UTC, mhluongo commented on background/package.json
> +    "ethereum-multicall": "^2.15.0",
.... why? This has to be something we can do with `ethers`, right?

2022-10-13 22:10 UTC, Shadowfiend commented on background/package.json
> +    "ethereum-multicall": "^2.15.0",
I think the main thing we get from the library is the set of deployed multicall addresses on various networks. Feels like something we can pull in directly, not unlike the decision around #1576's [SLIP-0044 data](https://github.com/tallycash/extension/pull/1576/files#diff-c39bd52887c7de83c4578b1121b894b6f51d906022e3ce80244cee62d02af941R1). Multicall is quite flexible and the package provides a lot of the infrastructural types to enable that flexibility, but because we're just calling a specific ERC20 function, I *think* we can do a lot of that work directly with Ethers with relatively little code.

2022-10-16 21:57 UTC, 0xDaedalus commented on background/package.json
> +    "ethereum-multicall": "^2.15.0",
Should be good for another look 👍

2022-10-19 17:50 UTC, greg-nagy requested changes
I love this PR, love this solution and we definitely should use this! But I feel this is not the correct place for that and we also should have a convo about some essential things before we decide we go down this path 

I think we should explore the `getLogs` + event filter method first, then if needed tie into this solution after proper considerations.

- I would like to steer us toward a solution that relies on user's tokens first and tokenlists for decision making 
- with the `getLogs` method we would probably be able to calculate the balances without any external dependency — still need to test if this approach is feasible. If not, then we can use this method to get the actual balances for the tokens that we got from that

My questions for this solution
- Should we rely on the already deployed contracts? If so what's our threat model? 
- Or should we deploy the contracts on our own? 
- What are the limitations that this method has? 

I would like this PR moved back to `Draft` until we clear the above points. This is a fantastic POC to showcase how this works and we should definitely rely on this in the future.

2022-10-20 02:01 UTC, 0xDaedalus commented
Happy to move back to draft - would love to see a poc of the `getLogs` solution sooner rather than later though so we can discuss the tradeoffs offered by each.

Responses to some of your thoughts here:
> I would like to steer us toward a solution that relies on user's tokens first and tokenlists for decision making

This solution does in fact rely on tokenlists (its what we feed into the multicall) - and I think that if we couple it with @mhluongo's open spam-token PR we'll have token discovery (on chains that support alchemy).

> Should we rely on the already deployed contracts? If so what's our threat model?

I think we can rely on the already deployed contracts for a few reasons:
1. The contract is not upgradeable.
2. It is created via `CREATE2` so we know that if the address is the same on a given EVM chain the contract's bytecode must also be the same.

> Or should we deploy the contracts on our own?

We certainly can if we want to be extra security-conscious (which is perhaps a good idea) but we would need to deploy it across dozens of chains and then deploy again for every new chain we want to support.

> What are the limitations that this method has?

One clear limitation is we need to have knowledge of a token either through token-lists or through user-addition in order to query its balance (this update does not deal with discoverability).

2022-10-22 11:50 UTC, mhluongo commented
> with the `getLogs` method we would probably be able to calculate the balances without any external dependency 

Log filtering can't get token balances, as per [ERC-20](https://eips.ethereum.org/EIPS/eip-20)... unless you replay the whole chain.

This is the correct approach to token balance checking without an indexing shortcut like Alchemy.

We shouldn't let experimental asset discovery get in the way of this functional, immediate improvement to the codebase and our goal of going cross-provider.

2022-10-23 15:00 UTC, greg-nagy approved these changes
I think this is a wonderful PR. Let's 🚢

2022-10-23 15:00 UTC, greg-nagy commented on background/services/indexing/index.ts
> +        if (isAlchemyProvider) {
The itch is so real to remove this :)

2022-10-23 15:00 UTC, greg-nagy commented on background/lib/erc20.ts
> +      false,
Some hints as to what the parameters are would be helpful.

2022-10-23 15:00 UTC, greg-nagy commented on background/lib/erc20.ts
> +  } catch (e) {
I think this catch will be with us longer than we expect.

2022-10-23 15:21 UTC, merged

2022-10-23 19:04 UTC, Shadowfiend reviewed
Couple of minor nits I wanted to mention.

2022-10-23 19:04 UTC, Shadowfiend commented on background/lib/erc20.ts
> +  // eslint-disable-next-line no-useless-catch
Not sure the value of having the try catch and a lint ignore just for the todo here, versus just having the todo without the extra line noise 🤔

2022-10-23 19:04 UTC, Shadowfiend commented on background/services/chain/asset-data-helper.ts
> +      return await getTokenBalances(
The original thinking here was not to check the provider type, but rather to use the thrown exception to feature-detect the absence of the alchemy call and fall back, fwiw.