Fix setting spend approval amount
tallycash/extension pull request #2446
Opened 2022-10-17 15:36 UTC by jagodarybacka

Resolves #2408

### What
Allow to force reload transaction annotations.
Reload transaction annotation when user changes the spend limit. Add a loader to indicate that it is reloading.

### Testing

- [ ] allow asset spend on uniswap or in-wallet swap (example - USDT on OP)
- [ ] allow asset spend screen should show up
- [ ] click change limit and set a new limit
- [ ] limit should be reloaded and displayed on the screen

![image](https://user-images.githubusercontent.com/20949277/196220470-e706e9c2-a96c-4bef-babe-1afa4a4639fb.png)

2022-10-18 10:17 UTC, hyphenized commented on ui/components/SignTransaction/SignTransactionSpendAssetInfoProvider.tsx
> +    setIsLoading(false)
Does it not work if you set loading to false after awaiting the dispatch? 🤔

2022-10-19 18:19 UTC, Shadowfiend commented
Was this only an issue on in-wallet swaps? Wondering what they're doing differently if so, given that this has historically worked.

2022-10-19 22:07 UTC, 0xDaedalus commented on ui/components/SignTransaction/SignTransactionSpendAssetInfoProvider.tsx
> +          input: updatedInput,
Not blocking and i know its a bit out of scope of the immediate bugfix but I wonder if we can clean up the `handleSaveClick` function a little bit.  As far as I can tell in ~20 lines we make the following hops: 
`approvalLimitInput` => `decimalAmount` => `bigintAmount` => `updatedInput`
which is just quite difficult to read inline and is further complicated by checking for falsy values after just about every conversion.

2022-10-19 22:53 UTC, Shadowfiend requested changes
Going to block this.

The breakage here is from #2331, where we stopped passing transactions that were already annotated to enrichment. This was a temporary hack for prepopulated swap annotations, whose side effects we unfortunately missed when testing the PR. This is fixed in #2461. We should either wait to merge that work, or apply the relevant change now (https://github.com/tallycash/extension/commit/65422590fbd021f8773c46dc9cb5cc8f3a638abc#diff-bb2ba232569016c28a3e1afeb301ce20420881034e715b0c87f88c6fd5db410cL674-R678), break the asset swap annotations that we ignore in the current flow, and re-fix them once that PR lands.

2022-10-19 22:54 UTC, Shadowfiend commented on ui/components/SignTransaction/SignTransactionSpendAssetInfoProvider.tsx
> +          input: updatedInput,
Going to request we hold on this so that we can fix it in the new signing flow, see #2331.

2022-10-20 13:19 UTC, jagodarybacka commented
> Was this only an issue on in-wallet swaps

@Shadowfiend no, every asset spend approval had this issue

>  either wait to merge that work, or apply the relevant change

Both options are fine with me. Would like to avoid duplicated work so idk which direction would you prefer @greg-nagy @0xDaedalus

2022-10-20 14:03 UTC, greg-nagy commented
> Both options are fine with me. Would like to avoid duplicated work so idk which direction would you prefer @greg-nagy @0xDaedalus

In this case please include the changes @jagodarybacka. The other PR is said to be ready for review but is still in Draft. Doesn't sound like a lot of effort and it could mean that this lands in the next release we cut on Friday.

2022-10-21 10:17 UTC, greg-nagy approved these changes
warms my heart 🔥

2022-10-21 10:21 UTC, merged