Arbitrum Odyssey banners
tallycash/extension pull request #2455
Opened 2022-10-18 16:03 UTC by jagodarybacka

2022-10-24 13:11 UTC, jagodarybacka commented
#### Thumbnail issues

I don't really like how this banner is working with thumbnail and fetching data from Galxe just for thumbnail feels like a lot.

Cons:
- it takes a while to show the image as we are fetching Arbitrum campaigns and then the image - thumbnail will need a loader as it is a visible delay
- pic it very small 
- the text on the banner is not taken from the Galxe so we have no way to know if pic and text will match (we don't know if future galxe campaigns will be following the rules we are expecting)

So idk but I would feel better with our custom thumbnail (we will need it anyway to be safe in case Galxe API will go down)
cc @VladUXUI @mr-michael

2022-10-24 14:45 UTC, 0xDaedalus reviewed
Some initial comments,
Wasn't able to get the banner to show up via your instructions though - tried changing date to various dates in November.

2022-10-24 14:45 UTC, 0xDaedalus commented on ui/components/Wallet/Banner/useBannerCampaigns.ts
> +        campaign.startDate <= currentDate &&
Just want to point out that a local date comparison like this will cause SEA users to see that week 2 has started well before US users - and perhaps even before week 2 officially starts.

If we know the exact time that the campaigns will switch over - we should use that.  Not a blocker for sure but could be a nice improvement if the information is available.

2022-10-24 14:48 UTC, VladUXUI commented
Didn't test it out yet, but based on screens i would say:
- Let's pin the image to the top (in line with title) and not be centred to the banner
- I sent you this via DM, but here it a placeholder image
<img width="58" alt="No_Image_banner" src="https://user-images.githubusercontent.com/80846886/197555452-04e8c602-6f30-42cd-8e3b-d0e2063fba6b.png">

If we aren't fetching any data from Galxe, i can definitely send you the images for the 2/3 odyssey banners

2022-10-24 15:20 UTC, jagodarybacka commented on ui/components/Wallet/Banner/WalletBanner.tsx
> +  const [dismissedCampaignId, setDismissedCampaignId] = useLocalStorage(
Hmm, I can move it to the redux store if you prefer, I thought it is data that is only temporary (looking at its importance) so wanted to avoid adding unimportant redux fields.

2022-10-24 15:20 UTC, jagodarybacka commented on ui/components/Wallet/Banner/useBannerCampaigns.ts
> +    startDate: new Date("11.07.2022"),
good point, will take a look

2022-10-25 15:26 UTC, jagodarybacka commented on ui/components/Wallet/Banner/useBannerCampaigns.ts
> +        campaign.startDate <= currentDate &&
Changed - each week should end/start on 4AM UTC

2022-10-25 16:00 UTC, jagodarybacka commented on ui/components/Wallet/Banner/useBannerCampaigns.ts
> +    startDate: new Date("11.07.2022"),
changed to UTC and with specific time

2022-10-27 12:28 UTC, jagodarybacka commented on ui/components/Wallet/Banner/useBannerCampaigns.ts
> +        campaign.startDate <= currentDate &&
Resolving as approach changed

2022-10-27 12:28 UTC, jagodarybacka commented on ui/components/Wallet/Banner/useBannerCampaigns.ts
> +    startDate: new Date("11.07.2022"),
Resolving as approach changed

2022-11-02 02:15 UTC, hyphenized requested changes
Looks good! Left some comments and questions 😁

2022-11-02 02:15 UTC, hyphenized commented on ui/components/Wallet/Banner/useArbitrumCampaigns.ts
> +  const [campaigns, setCampaigns] = useState<Campaign[] | null | undefined>(
We can avoid having to deal with null/undefined here if we define separate states for error / loading and passed them down to the hook consumer. Something like:

```ts
export default function useArbitrumCampaigns(): {
  campaigns: Campaign[]
  loading: boolean
  error: boolean
} {
  const [campaigns, setCampaigns] = useState<Campaign[]>([])
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState(false)

  useEffect(() => {
    const fetchCampaign = async () => {
      const active = await getLatestCampaigns()
      setCampaigns(active.slice(0, 2))
    }
    setLoading(true)

    fetchCampaign()
      .catch(() => setError(true))
      .finally(() => setLoading(false))
  }, [])

  return { campaigns, loading, error }
}
```

2022-11-02 09:42 UTC, jagodarybacka commented on ui/components/Wallet/Banner/WalletBanner.tsx
> +        setThumbnails(["./images/banner_thumbnail.png"])
Yes, it should never be needed but included as a backup

2022-11-02 09:44 UTC, jagodarybacka commented on ui/components/Wallet/Banner/WalletBanner.tsx
> +              })}
they are hidden so later when they are loaded there is a nice animation. But I can make sure there is no `/undefined` request

2022-11-02 12:58 UTC, hyphenized approved these changes
Looks good to me

2022-11-03 21:33 UTC, 0xDaedalus approved these changes
Fantastic work 📈📈📈📈📈

2022-11-03 21:38 UTC, merged