Display `Tally Ho` as a connection option on GMX and Uniswap
tallycash/extension pull request #2460
Opened 2022-10-19 21:58 UTC by 0xDaedalus

https://user-images.githubusercontent.com/94649004/196811459-2e9c8b09-3a0f-43c2-a36f-22ce91534d21.mov

This PR is a first step towards increasing the number of dapps that display `Tally Ho` as a connection option for users of the wallet.  It introduces two bespoke handlers and introduces a pattern through which integrations for additional dapps can be made.

#### Highlights:
- Minimal overhead (handlers exit early and often - and only run on their given origin)
- An origin <> handler mapping through which future handlers can easily be added
- a new `tallySetAsDefault` property on `window.ethereum` which is a bit more idiomatic way of inferring that the user has set tally as default (as opposed to checking for `window.ethereum.isMetaMask`)

### To Test
- When Tally is the only wallet installed
  - [ ] Connecting to Uniswap should display `Tally Ho` as a connection option.
  - [ ] Connecting to gmx.io should display `Tally Ho` as a connection option.
- When both Metamask and Tally are installed
  - If the `Use Tally Ho as your default wallet` setting is not toggled
    - [ ] Connecting to Uniswap should display `Metamask` as a connection option.
    - [ ] Connecting to gmx.io should display `Metamask as a connection option.
  - If `Use Tally Ho as your default wallet` setting is toggled
    - [ ] Connecting to Uniswap should display `Tally Ho` as a connection option.
    - [ ] Connecting to gmx.io should display `Tally Ho` as a connection option.

2022-10-20 13:41 UTC, jagodarybacka commented on window-provider/wallet-connection-handlers.ts
> +  const maybeButton = addedNode?.childNodes?.[2]?.childNodes?.[0]
is it possible to do it with querySelector?

2022-10-20 13:42 UTC, jagodarybacka commented
hmm, it is working the first time you open the connect modal on Uniswap but if you close it and open it again it shows injected for me :(

2022-10-20 13:53 UTC, greg-nagy requested changes
This is amazing 🤩

The checks for the `providers` array is a blocker, the rest is more of a discussion on the approach.

2022-10-20 13:53 UTC, greg-nagy commented on window-provider/wallet-connection-handlers.ts
> +    const observer = new MutationObserver(function monitorMutations(mutations) {
I didn't see any perf hit, but running the observer on every DOM change feels a bit strong handed. 

Could we select the `Connect` element and listen to a click event? 
This would miss the eager loading scenario, but that could be handled with checking for the element on page load.

Not sure if this worth the effort though, if we don't generate any significant overhead.

2022-10-20 13:53 UTC, greg-nagy commented on window-provider/wallet-connection-handlers.ts
> +    if (!window.ethereum.tallySetAsDefault) {
We probably should expand this check filter the users who hasn't finished the onboarding. 
Or redirect to onboarding in the popup.

2022-10-20 13:53 UTC, greg-nagy commented on window-provider/wallet-connection-handlers.ts
> +    Array.isArray(window.ethereum.providers) &&
This check should be refactored because [for some pages we remove the `providers` array alltogether](https://github.com/tallycash/extension/blob/784d3a55243ca5ee9c30567d3ad54fc2573f716c/src/window-provider.ts#L127).

We need to do that, because web3-react would search for MM in the providers array and use that as a connector, instead of `window.ethereum`. 
Which is 'meh', but it is what it is.

2022-10-20 13:53 UTC, greg-nagy commented on window-provider/wallet-connection-handlers.ts
> +  const maybeButton = addedNode?.childNodes?.[2]?.childNodes?.[0]
maybeButton ❤️

2022-10-20 13:53 UTC, greg-nagy commented on window-provider/wallet-connection-handlers.ts
> +    const observer = new MutationObserver(function monitorMutations(mutations) {
```
const connectButton = document.querySelectorAll("button[data-testid='navbar-connect-wallet']")[0]
connectButton.addEventListener('click', (event) => {console.log("hey we are here")})
```

2022-10-20 13:53 UTC, greg-nagy commented on window-provider/wallet-connection-handlers.ts
> +    ?.childNodes?.[0]?.childNodes?.[0] as Element
We could use `document.getElementById("injected")`.
Not sure how these 2 approaches compare though.

2022-10-20 13:53 UTC, greg-nagy commented on window-provider/wallet-connection-handlers.ts
> +    // a change related to web3-react.  It never hurts to double check.
Is this a web3-react specific thing or uniswap?

2022-10-21 13:59 UTC, 0xDaedalus commented on window-provider/wallet-connection-handlers.ts
> +  const maybeButton = addedNode?.childNodes?.[2]?.childNodes?.[0]
Unfortunattely querySelector is O(N) where N is _all_ of the elements in a given element's tree.  This is uglier but much more efficient as it will stop traversing as soon as an expected leaf is not found.

2022-10-21 13:59 UTC, 0xDaedalus commented on window-provider/wallet-connection-handlers.ts
> +    const observer = new MutationObserver(function monitorMutations(mutations) {
There are two issues with adding a listener that I encountered:

1) There are at least 3 "Connect" buttons on the main uniswap app screen - one of which has no id (of course we can grab a parent element and iterate through children - but still its a bit messy)
2) When using an `onClick` handler - the dom element we want to change may not be on the screen at the time the handler is called (especially if you emulate as a slower computer) - so we end up with a race condition we need to manage.

2022-10-21 14:00 UTC, 0xDaedalus commented on window-provider/wallet-connection-handlers.ts
> +    if (!window.ethereum.tallySetAsDefault) {
This is a good point and should I'd like to address it before we merge

2022-10-21 14:34 UTC, 0xDaedalus commented on window-provider/wallet-connection-handlers.ts
> +    Array.isArray(window.ethereum.providers) &&
Looks like this check was not even needed in uniswap's specific case (I think probably because of whats happening in the code you linked).  Will have to think about how to do this on other sites so that Tally does not override MetaMask when its not set as default - but we can cross that bridge when we get there.

2022-10-21 14:42 UTC, 0xDaedalus commented on window-provider/wallet-connection-handlers.ts
> +    ?.childNodes?.[0]?.childNodes?.[0] as Element
Alright - I've been won over.

Both approaches are brittle - but the additional check for truthyness `iconAndTextDiv` makes me feel better about not accidentally grabbing the wrong element (since it is not unreasonable for another element to accidentally be added with an `id` of `injected`).  Also we'll get O(1) lookup time with `getElementById` - so thats a nice plus.

2022-10-21 14:57 UTC, 0xDaedalus commented on window-provider/wallet-connection-handlers.ts
> +    if (!window.ethereum.tallySetAsDefault) {
On second thought lets follow this up in a separate PR - proving to be a more involved change than I'd like it to be for a spike.

2022-10-21 14:57 UTC, 0xDaedalus commented on window-provider/wallet-connection-handlers.ts
> +    // a change related to web3-react.  It never hurts to double check.
uniswap - comment has been updated

2022-10-21 14:58 UTC, 0xDaedalus commented
@greg-nagy This should be good for another look ✅

2022-10-24 11:09 UTC, greg-nagy commented on window-provider/wallet-connection-handlers.ts
> +    if (!window.ethereum.tallySetAsDefault) {
The issue for this: https://github.com/tallycash/extension/issues/2487

Added to next sprint for us to not forget about it, but this might be ok do move into this sprint.

2022-10-24 11:14 UTC, merged