❤️‍🩹 Nonces vs Mempool: Separate nonce behavior between chains with and without mempool
tallycash/extension pull request #2516
Opened 2022-10-27 13:03 UTC by greg-nagy

## What 

If a chain doesn't have mempool then
the tx is either picked up or dropped immediately. Eg, on optimism
and arbitrum. This means that we should rely on the nonce that
we got from the chain, and no need for us to track lasSeenNonce.

The same distinction should also happen when releasing nonces.

Note: more robust nonce management that take into account
the nonces in the mempool and the fact that they might not be
linear will be a follow-up work.

## Future work 
- update eip-1559 nonce handling to consider pending txs 
- use `SerialFallbackProvider` when broadcasting tx

## Test
- [ ] send and swap on mainnet, polygon, optimism and arbitrum and they should work
- [ ] swap multiple times on Velodrome
- [ ] buy multiple NFTs on looksrare

Closes #2434

2022-10-27 14:21 UTC, Shadowfiend commented on background/services/chain/index.ts
> +    if (EIP_1559_COMPLIANT_CHAIN_IDS.has(chainID)) {
This is a different thing, right? A chain can have a mempool and not be EIP-1559 compliant.

2022-10-27 14:23 UTC, Shadowfiend commented on background/services/chain/index.ts
> -            this.releaseEVMTransactionNonce(transaction)
May want to leave a comment here that returning `Promise.reject` should release the associated nonce in the `catch` below.

2022-10-27 14:25 UTC, Shadowfiend commented on background/services/chain/index.ts
> +    let knownNextNonce = await provider.getTransactionCount(
This rename isn't really accurate. This isn't the known next nonce at this stage, it's speculative and depends on network.

I would suggest using `const chainTransactionCount` here, and keeping the naming below.

2022-10-27 14:57 UTC, greg-nagy commented on background/services/chain/index.ts
> +    if (EIP_1559_COMPLIANT_CHAIN_IDS.has(chainID)) {
https://github.com/tallycash/extension/pull/2516/commits/8e7ee962d8342cb7bd8204a5c819facc9cd7ead2

2022-10-27 14:57 UTC, greg-nagy commented on background/services/chain/index.ts
> +    let knownNextNonce = await provider.getTransactionCount(
https://github.com/tallycash/extension/pull/2516/commits/b533d1adbdd1f226143fa7c582cb0428ac50594f

2022-10-27 14:57 UTC, greg-nagy commented on background/services/chain/index.ts
> -            this.releaseEVMTransactionNonce(transaction)
https://github.com/tallycash/extension/pull/2516/commits/d7afd22bd4c0c51f20a902e24fdae4cd4bf47b57

2022-10-28 11:53 UTC, jagodarybacka commented on background/services/chain/index.ts
> +    // mempool or in other words implements EIP-1559.
`chain has mempool or in other words implements EIP-1559.` - is this correct? From @Shadowfiend comment - not every chain with mempool implements EIP1559. 
Does it work the other way around and do we have examples of such chains?

2022-10-31 01:51 UTC, 0xDaedalus requested changes
Looks fantastic - only blocker from me is the test comment - I think the way its currently written we're decreasing our test coverage slightly since the test is no longer testing tx persistance.

2022-10-31 01:51 UTC, 0xDaedalus commented on background/services/chain/index.ts
> +    const chainTransactionCount = await provider.getTransactionCount(
Would it make sense to add the # of transactions returned from a call to [`alchemy_getPendingTransactions`](https://docs.alchemy.com/reference/alchemy-pendingtransactions) with a `fromAddress` of `transactionRequest.from` to get the `chainTransactionCount`?  (Assuming they are submitted with valid increasing nonces)

2022-10-31 01:51 UTC, 0xDaedalus commented on background/services/chain/tests/index.integration.test.ts
> +    if (!CHAINS_WITH_MEMPOOL.has(chainID)) {
I believe this will always return early and the `expect`'s following it will never be called - since the chainID will always be 10 - right?  I believe we'll still want to check that we persist the tx in the db - and we should definitely write a second test for nonce management on EIP-1559 chains (should mostly be the same as this one).

2022-10-31 08:13 UTC, greg-nagy commented on background/services/chain/index.ts
> +    const chainTransactionCount = await provider.getTransactionCount(
The plan is similar but in a follow-up PR and without binding this to websockets. 

TL;DR: it's seems possible with `eth_getTransactionCount` / `provider.getTransactionCount()` but either ethers.js typing is lying to us or we need to update the version. 

https://github.com/ethers-io/ethers.js/discussions/3470 - the idea is similar to this, but this is not perfect either.
[`eth_getTransactionCount` on alchemy](https://docs.alchemy.com/reference/eth-gettransactioncount-astar) does support this. See `2. String - Integer block number, or the string 'latest', 'earliest' or 'pending'.` 

This has a chance to be the next heterodox idea of mine, so I definitely want to separate this from the current PR.

2022-10-31 20:20 UTC, 0xDaedalus commented on background/services/chain/index.ts
> +    const chainTransactionCount = await provider.getTransactionCount(
Seems like the `eth_getTransactionCount` with `pending` is just strictly a better solution here since it does not couple us to alchemy.

2022-11-01 12:26 UTC, greg-nagy commented on background/services/chain/tests/index.integration.test.ts
> +    if (!CHAINS_WITH_MEMPOOL.has(chainID)) {
[7cc1d5a](https://github.com/tallycash/extension/pull/2516/commits/7cc1d5afc2228a3ddb0f019bffc9b1c5a66df171)

2022-11-01 12:28 UTC, greg-nagy commented on background/services/chain/tests/index.integration.test.ts
> +    if (!CHAINS_WITH_MEMPOOL.has(chainID)) {
The original idea was to update tests after the pending changes are in place. But appreciate the pushback. Focusing on tests is always worth it.

2022-11-01 13:00 UTC, merged