Allow renaming account sections
tallycash/extension pull request #2523
Opened 2022-10-29 20:28 UTC by hyphenized

<img title="I Need Your Clothes, Your Boots and Your Motorcycle" width="400" src="https://user-images.githubusercontent.com/28708889/198851129-d02afd74-2f8f-4c26-88da-ecc5301986e9.gif">

Closes #2239

## To Test:
- [ ] Import an account, a ledger account and add a read-only account
- [ ] Go to the accounts panel, try to change the name for each section

2022-10-30 00:28 UTC, 0xDaedalus requested changes
This looks awesome!  Took a quick look at the code but haven't had a chance to dive in and test yet.

One thing I did notice in the video is we probably want the cursor to change to a `pointer` when hovering over the settings cog.

Can-not-wait to get this in!

2022-10-30 00:28 UTC, 0xDaedalus commented on background/services/name/resolvers/uns.ts
> +      ".blockchain",
📈

2022-10-30 00:28 UTC, 0xDaedalus commented on ui/components/AccountItem/AccountItemOptionsMenu.tsx
> +import { DropdownMenu } from "../Shared/SharedDropDown"
I think we have a more-or-less consistent pattern of calling using filename in component names of components from the `/Shared` directory.  So maybe `SharedDropDown`?

2022-10-30 00:28 UTC, 0xDaedalus commented on ui/components/AccountItem/AccountItemOptionsMenu.tsx
> +            label: "Edit name",
`t('editName')`

2022-10-30 00:28 UTC, 0xDaedalus commented on ui/components/AccountsNotificationPanel/AccountsNotificationPanelAccounts.tsx
> +import { DropdownMenu } from "../Shared/SharedDropDown"
`SharedDropDown`

2022-10-30 00:28 UTC, 0xDaedalus commented on ui/components/AccountsNotificationPanel/AccountsNotificationPanelAccounts.tsx
> +const EditSectionForm = ({
I think this can probably be in its own file.

2022-10-30 00:28 UTC, 0xDaedalus commented on ui/components/AccountsNotificationPanel/AccountsNotificationPanelAccounts.tsx
> +const EditSectionForm = ({
We also prefer to enforce the `function EditSectionForm() {}` syntax over the `const EditSectionForm = () => {}` syntax.

2022-10-30 00:28 UTC, 0xDaedalus commented on ui/components/AccountsNotificationPanel/AccountsNotificationPanelAccounts.tsx
> +      if (error) {
This won't catch an error set on line 113 since the `onSubmit` function will finish executing before the changes from `setError` are applied.

2022-10-30 00:28 UTC, 0xDaedalus commented on ui/components/AccountsNotificationPanel/AccountsNotificationPanelAccounts.tsx
> +            onSubmitCallback(null)
It doesn't feel right to me that we're calling a function called `onSubmitCallback` on an action that is not a submission (clicking cancel).  Do you think it might make sense to just pass a separate `onCancelCallback` to this component instead?

2022-10-30 00:28 UTC, 0xDaedalus commented on ui/components/Shared/SharedDropDown.tsx
> +                {(options.filter(Boolean) as DropdownOption[]).map(
If we enforce correct options through types (`options: Array<DropdownOption>`) we don't have to filter here.  I'd like to avoid `x as y` whenever possible - its historically been a big source of bugs for us.

2022-10-30 00:28 UTC, 0xDaedalus commented on ui/components/Shared/SharedDropDown.tsx
> +const DropdownContext = React.createContext<DropdownContextValue>(null!)
Is there any way around the non-null assertion here?  If not lets make sure to comment exactly why we're disabling the eslint rule

2022-10-30 03:41 UTC, hyphenized commented on ui/components/Shared/SharedDropDown.tsx
> +                {(options.filter(Boolean) as DropdownOption[]).map(
Excellent catch! Replaced with a type guard

2022-10-30 03:59 UTC, hyphenized commented on ui/components/AccountsNotificationPanel/AccountsNotificationPanelAccounts.tsx
> +      if (error) {
Thanks, good catch. By the way, is the error supposed to look like this?: cc @VladUXUI 


![image](https://user-images.githubusercontent.com/28708889/198861878-0a8f9541-f82d-452c-972b-7689415d5da1.png)

2022-10-30 04:00 UTC, hyphenized commented on ui/components/AccountsNotificationPanel/AccountsNotificationPanelAccounts.tsx
> +            onSubmitCallback(null)
You're right, this might also end up confusing devs working on this

2022-10-30 04:29 UTC, hyphenized commented on ui/components/Shared/SharedDropDown.tsx
> +const DropdownContext = React.createContext<DropdownContextValue>(null!)
This was an exception because the context is only accessed from within the Dropdown components and these only function when they have a non null context value. I've added a null safe check to the access hook so we don't have to disable a rule here.

2022-10-31 02:11 UTC, 0xDaedalus commented
Spent a bit of time testing - some things I found:
- Importing a new keyring after naming a previously imported keyring resets all names
- Adding an address to a named keyring resets all keyring names.
- Should we enforce unique keyring names?  Currently its possible for me to name all of my accounts the same name e.g. `WALLET1` (cc @VladUXUI)

Also a general note about commit messages - in general we strive to write commit messages that are expressive as possible (after all we are an open source project) and tend to avoid labels like feat/chore/fix/ etc...  @Shadowfiend's PRs are by far the best example of this (I myself am still constantly working to improve the quality of my commit messages) and I encourage you to take a look at them ([for example this one](https://github.com/tallycash/extension/pull/2312/commits)).

2022-10-31 07:07 UTC, VladUXUI commented on ui/components/AccountsNotificationPanel/AccountsNotificationPanelAccounts.tsx
> +      if (error) {
Hey hey, overall is looking awesome! 
But no, the error is under the input field

2022-10-31 07:10 UTC, VladUXUI commented
> * Should we enforce unique keyring names?  Currently its possible for me to name all of my accounts the same name e.g. `WALLET1` (cc @VladUXUI)

We aren't using this data to do anything really, so from a users perspective it isn't important to do so.
If it somehow helps code wise, that is up to you. but UX wise it's not a plus or a minus :)

2022-10-31 10:59 UTC, jagodarybacka commented on ui/components/Shared/SharedDropDown.tsx
> +  const styles: React.CSSProperties = {
I'm not sure about using another type of styles. I don't like `styled-jsx` package but I would rather use it consistently where it is possible.

2022-10-31 10:59 UTC, jagodarybacka commented on ui/components/Shared/SharedDropDown.tsx
> +                aria-label="Close"
Do we want to add aria label to translations?

2022-10-31 10:59 UTC, jagodarybacka commented on ui/components/Shared/SharedDropDown.tsx
> +             .icon_close {
Can we use `SharedIcon` component here?

2022-10-31 10:59 UTC, jagodarybacka commented on ui/components/AccountsNotificationPanel/AccountsNotificationPanelAccounts.tsx
> +    ? keyringMetadata[keyringId].customName
Let's make sure it won't throw when keyringMetadata will be undefined for some reason
```suggestion
    ? keyringMetadata[keyringId]?.customName
```

2022-10-31 23:14 UTC, Shadowfiend reviewed
I'm extremely nervous that the preferences service isn't showing up here. That's where this stuff should get persisted, because redux isn't meant to be the core persistence mechanism for the extension, indexeddb is 😬 This is why account names are ultimately persisted there (and why default names also should be---something I skimped on for time reasons a while ago but which is already biting us in local name resolution).

2022-10-31 23:26 UTC, hyphenized commented
> I'm extremely nervous that the preferences service isn't showing up here. That's where this stuff should get persisted, because redux isn't meant to be the core persistence mechanism for the extension, indexeddb is 😬 This is why account names are ultimately persisted there (and why default names also should be---something I skimped on for time reasons a while ago but which is already biting us in local name resolution).

I see, I chose to store this on Redux because I didn't consider this data to be important enough to save it inside idb... 😕

2022-11-01 00:50 UTC, Shadowfiend commented
I think the current approach a reasonable starting point and probably worth merging, maybe behind a feature flag or maybe not. But ultimately all data in the system should either able to be looked up from a service or from IDB, by design. As an example of why we've approached things with this model in mind despite a lot of stuff living untouched in redux right now,  imagine a world where we only load account group metadata when the drop-down is displayed to minimize redux store size, or to accelerate time to first render.  Another version of this, of course, is the redux store only existing in the popup script (though there are a bunch of additional complications with that approach). The rule of thumb though is that anything we expect to persist between browser restarts ultimately should live in IDB. 

Like I mentioned, we've cut some corners here in the past---and if we're in a hurry to get this out it may be reasonable to cut this corner here too---but I wanted to make sure to articulate the underlying reasoning and what might be an ideal way to approach the solution here, so there's a sense that there is room for further improvement to the solution as it currently stands.

2022-11-01 05:33 UTC, hyphenized commented on ui/components/AccountsNotificationPanel/AccountsNotificationPanelAccounts.tsx
> +      if (error) {
I'll follow up with a fix for this in a different issue since I might have to check other places where this input is being used to make sure it's good

2022-11-01 05:52 UTC, hyphenized commented on ui/components/Shared/SharedDropDown.tsx
> +  const styles: React.CSSProperties = {
> Spent a bit of time testing - some things I found:
> 
>     * Importing a new keyring after naming a previously imported keyring resets all names
> 
>     * Adding an address to a named keyring resets all keyring names.
> 
>     * Should we enforce unique keyring names?  Currently its possible for me to name all of my accounts the same name e.g. `WALLET1` (cc @VladUXUI)
> 
> 
> Also a general note about commit messages - in general we strive to write commit messages that are as expressive as possible (after all we are an open source project) and tend to avoid labels like feat/chore/fix/ etc... @Shadowfiend's PRs are by far the best example of this (I myself am still constantly working to improve the quality of my commit messages) and I encourage you to take a look at them ([for example this one](https://github.com/tallycash/extension/pull/2312/commits)).

Sorry for the late response, I agree, these commits are not really giving any context at all and are actually making it more difficult to review and understand the changes being made.  Looking back at [this comment](https://github.com/tallycash/extension/pull/2220#discussion_r972971856) I think I should have realized this sooner, thank you for the feedback!

2022-11-01 06:22 UTC, hyphenized commented
@0xDaedalus Sorry for the late response, I agree, these commits are not really giving any context at all and are actually making it more difficult to review and understand the changes being made. Looking back at this https://github.com/tallycash/extension/pull/2220#discussion_r972971856, I think I should have realized this sooner, thank you for the feedback!

@Shadowfiend Thanks for taking the time to explain, I think this was a bad assumption on my end because we are also trying to reduce the size of the Redux store. I've moved the metadata to the preferences db, but, there's still a piece of data in the Redux store that updates as a response to changes in the db. I feel like this is probable not the best approach to pass data down to the UI and have it react to changes, but, it's the most straightforward way I found to do it. 

> imagine a world where we only load account group metadata when the drop-down is displayed to minimize redux store size, or to accelerate time to first render

I do hope we can see something like this in the future

2022-11-01 06:23 UTC, hyphenized commented on ui/components/Shared/SharedDropDown.tsx
> +  const styles: React.CSSProperties = {
Me neither, the idea here was to pass different styles based on some positioning prop but that ended up not being necessary

2022-11-01 06:23 UTC, hyphenized commented on ui/components/Shared/SharedDropDown.tsx
> +                aria-label="Close"
Si

2022-11-01 06:23 UTC, hyphenized commented on ui/components/Shared/SharedDropDown.tsx
> +             .icon_close {
We can!

2022-11-01 15:20 UTC, 0xDaedalus reviewed
Looks great and is certainly mergeable but curious to hear your thoughts on possibly creating a new table for the settings.

2022-11-01 15:20 UTC, 0xDaedalus commented on background/redux-slices/ui.ts
> +      Exclude<AccountSigner, typeof ReadOnlyAccountSigner>,
Wonder if this should be extracted into its own type since its used in quite a few files

2022-11-01 15:20 UTC, 0xDaedalus commented on background/services/preferences/db.ts
> +  async updateSignerSettings(
The function signature here suggests that we might want to call this function `updateSignerTitle`

2022-11-01 15:20 UTC, 0xDaedalus commented on background/services/preferences/db.ts
> +      ({ signer: storedSigner }) => isEqual(storedSigner, signer)
I'm admittedly not the biggest fan of lodash - but I do wonder if checking `keyringId` or `ledgerId` is enough of an equality comparison to where we can avoid using `isEqual` (assuming we keep `accountSignerSettings` as a property in the `preferences` table.

2022-11-01 15:20 UTC, 0xDaedalus commented on background/services/preferences/db.ts
> +        preferences: "++id",
I think we might be better served by defining a separate `accountSignerSettings` table here rather than appending another property into the `preferences` table.  Reasoning is:

- We can use the ledger/keyring id of a signer as a unique primary key to have a stronger guarantee we won't have duplicate accountSignerSettings.
- We can query / update / delete by that id - this should greatly simplify the `delete` logic.
- We won't need to stringify the entire preferences object and then query further in memory to access the account signer setting that we want.
- Much easier to observe / debug in devtools

2022-11-01 19:43 UTC, hyphenized commented on background/services/preferences/db.ts
> +      ({ signer: storedSigner }) => isEqual(storedSigner, signer)
Yes we can, I added a check without `isEqual` on the Header component, I'll refactor that out to `utils`

2022-11-01 19:43 UTC, hyphenized commented on background/redux-slices/ui.ts
> +      Exclude<AccountSigner, typeof ReadOnlyAccountSigner>,
It is! Refactored into its own type!

2022-11-01 19:44 UTC, hyphenized commented on background/services/preferences/db.ts
> +  async updateSignerSettings(
Future proofing too much 😅

2022-11-01 20:58 UTC, hyphenized commented on background/services/preferences/db.ts
> +        preferences: "++id",
These are valid points, I don't believe we'll see a performance improvement here but it has definitely simplified the flow a lot. Great suggestion!

2022-11-01 23:41 UTC, 0xDaedalus approved these changes
👑 👑 👑 👑 👑 👑 👑 👑 

Amazing work!

Lets ship this bad boy.

2022-11-01 23:41 UTC, 0xDaedalus commented on background/services/preferences/db.ts
> +const getSignerRecordId = (
Not sure if we need this because i _believe_ we already prefix the ledger id with something like LEDGER_NANO_X_${id} but definitely better safe than sorry

2022-11-01 23:45 UTC, merged