Redirect to onboarding if user has no accounts
tallycash/extension pull request #2545
Opened 2022-11-02 18:38 UTC by hyphenized

Previously this check was only performed in the main wallet page, leaving users who removed their last account stranded on the other pages until they went back to the wallet page.

Removed Location internal type in favour of the one provided by react router as well
<img width="380" title="WILSOOOOOOON" src="https://user-images.githubusercontent.com/28708889/199573612-93d084ce-e34b-4f36-bc7b-2ddceb2a9ede.gif" />

To Test: 
----
- [ ] Remove any type of account on the swap page, you should be redirected to onboarding

2022-11-03 14:18 UTC, jagodarybacka commented on ui/pages/Popup.tsx
> +                        // If an account doesn't exist, display onboarding
```suggestion
                        // If there are no existing accounts, display onboarding
```

Because if there are accounts loaded then it should switch to another address, not display onboarding

2022-11-03 14:26 UTC, jagodarybacka commented on background/redux-slices/selectors/signingSelectors.ts
> +    const readOnlyEntries: [string, typeof ReadOnlyAccountSigner][] =
I think now you can refactor this selector too https://github.com/tallycash/extension/blob/main/background/redux-slices/selectors/signingSelectors.ts#L54

2022-11-03 14:28 UTC, jagodarybacka commented on background/redux-slices/selectors/accountsSelectors.ts
> +export { default as getAllAddresses } from "./accounts/getAllAddresses"
I think this is a good direction, I hate these huge files 😂  but can we either refactor whole `accountsSelector` file at once or make a task to not forget about it?

2022-11-03 19:29 UTC, mhluongo commented
Not sure this is a good solution considering we're moving to tabbed onboarding.

2022-11-03 21:51 UTC, hyphenized commented on ui/pages/Popup.tsx
> +                        // If an account doesn't exist, display onboarding
Good catch, I'll update the comment

2022-11-03 21:52 UTC, hyphenized commented on background/redux-slices/selectors/signingSelectors.ts
> +    const readOnlyEntries: [string, typeof ReadOnlyAccountSigner][] =
Nice call, found a few other places to refactor this as well 🚀

2022-11-03 21:53 UTC, hyphenized commented on background/redux-slices/selectors/accountsSelectors.ts
> +export { default as getAllAddresses } from "./accounts/getAllAddresses"
We can include that in this PR, though, I wanted to check if the team had anything to say about this before making the change. cc: @tallycash/extension-devs

2022-11-04 14:41 UTC, jagodarybacka commented
@mhluongo @VladUXUI so we plan to not include any popup onboarding at all? We have to handle situations like this anyway - the user can either remove all addresses or skip onboarding and open the wallet. I think full onboarding with introduction slides is not necessary, only the "select type of account to add" screen is needed here.

2022-11-04 20:09 UTC, mhluongo commented
>  so we plan to not include any popup onboarding at all?

From Element, that's the plan... we can open the tabbed onboarding whenever a wallet is in a non-onboarded state.

That's actually what my feature-flagged implementation does already, though it requires the extension button to be hit. Here, I think we should do the same thing, but it will need an additional trigger when the last account is removed.

2022-11-04 20:09 UTC, mhluongo commented
Also generally.... the existing in-extension onboarding code is pretty rough. I very much vote for removing the tech debt and snipping the code once tabbed onboarding is flipped on.

2022-11-04 20:50 UTC, mhluongo commented on ui/pages/Popup.tsx
> +                        // TODO: FeatureFlags.SUPPORT_TABBED_ONBOARDING
@hyphenized maybe you can support `SUPPORT_TABBED_ONBOARDING` now with a `window.open()` to get this to merge-able?

2022-11-04 21:28 UTC, hyphenized commented on ui/pages/Popup.tsx
> +                        // TODO: FeatureFlags.SUPPORT_TABBED_ONBOARDING
Sure, onboarding tab now opens after the last account is removed

2022-11-07 11:57 UTC, greg-nagy reviewed
This PR is lookin' good and fancy :) 

I think the selector restructure should be in a separate PR/proposal/discussion. 

Not sure about the selector input refactor either, but I might not have the full picture.

2022-11-07 11:57 UTC, greg-nagy commented on background/redux-slices/selectors/accountsSelectors.ts
> +export { default as getAllAddresses } from "./accounts/getAllAddresses"
## Thought for this change to be in this PR:
This change and this discussion should happen outside of this PR. I think the tension is valid and we should discuss this but in a separate conversation. I recommend opening a PR/issue dedicated for the introduction of this pattern and using the [light RFC/propsal style](https://coda.io/d/Engineering-Thesis_duruoW1C74B/RFC-Process_su2dT#_luU0q). For an example [generic RPC](https://github.com/tallycash/extension/pull/2547) or the [CI refactor](https://github.com/tallycash/extension/pull/2477)

## Thoughts for the discussion/idea:
I have felt the pain of putting everything into a separate file in angular land. That can become unwidely very quickly. Breaking up big files can be a good idea if we find the right separations based on a well-defined concern/domain. 

If you/team feels strongly about putting everything into its file, I think we can give it a try. But I feel strongly about not using the default exports for this. I prefer named exports because otherwise, manual renaming will be necessary, and that's error-prone and makes the code harder to follow.  

Another thought: I have seen the domain-based separation working well, which groups code together based on what concern it belongs to and not what type it is. Eg `redux-slices/accounts/` and inside that folder would be the `account.slice.ts`, `account.selectors.ts`, `account.utils.ts`. Note: The duplication in the dir name and file name feels unnecessary at first, but I have found that useful.

2022-11-07 11:57 UTC, greg-nagy commented on background/redux-slices/selectors/accountsSelectors.ts
> +  (state: RootState) => state,
Does this change not break the selector memoization/caching? 
https://redux.js.org/usage/deriving-data-selectors#passing-input-parameters

2022-11-07 17:51 UTC, greg-nagy commented
This breaks the dApp connection window — which was broken already :) See #2545 

The change this PR introduces is that we see a green screen without any error now when the user hasn't finished the onboarding OR removed his/her last account. 

![CleanShot 2022-11-07 at 18 50 20](https://user-images.githubusercontent.com/7690112/200380007-23bb291e-dc4c-4b88-8ed4-7d2bf278b884.png)

Not sure if this is a blocker for this PR, because that screen was already really bad.

2022-11-08 06:27 UTC, hyphenized commented on background/redux-slices/selectors/accountsSelectors.ts
> +  (state: RootState) => state,
Unfortunately both of these are bad because some of the input selectors return non primitives and the default equality check for selectors memoization is `===` over the output selector params. The previous selector is a bit better because it's dependencies are passed directly to `createSelector`, but it does not make a significant difference in performance 😕

2022-11-08 06:29 UTC, hyphenized commented
Nice catch @greg-nagy! I've added that route to the redirect exception list

2022-11-08 11:55 UTC, jagodarybacka requested changes
We are not switching tabbed onboarding flag yet right? Because it is not working correctly with `SUPPORT_TABBED_ONBOARDING=false`

https://user-images.githubusercontent.com/20949277/200557646-2eb0c4c0-6d37-46f3-99f2-4479fdcca4d6.mov

2022-11-08 12:51 UTC, hyphenized commented
@jagodarybacka Ahhh, looks like I missed the new password route. Should be good now, thanks!

2022-11-08 13:04 UTC, jagodarybacka commented
@hyphenized found another thing:
setup:
![image](https://user-images.githubusercontent.com/20949277/200572145-a0dc3efd-899d-46be-9137-833f60d38a9d.png)
remove account: 
![image](https://user-images.githubusercontent.com/20949277/200572204-7c72770a-6ef4-4763-85c7-eca0d4b47aae.png)

2022-11-08 16:03 UTC, jagodarybacka approved these changes
Looks good, would be nice to get it merged as I'm building https://github.com/tallycash/extension/pull/2578 on top of this. 
I'll let @greg-nagy take another look before merging.

2022-11-08 17:22 UTC, greg-nagy commented on background/redux-slices/selectors/accountsSelectors.ts
> +  (state: RootState) => state,
https://github.com/reduxjs/reselect#createselectorcreatormemoize-memoizeoptions that behavior can be changed 

I don't think that this is a blocker now, but [we have random reloads without store changes](https://github.com/tallycash/extension/issues/2550) probably partially because of selector memoization is not working properly.

2022-11-08 17:49 UTC, hyphenized commented on background/redux-slices/selectors/accountsSelectors.ts
> +  (state: RootState) => state,
Hmmm yeah it does sound like that could be the cause, thanks for sharing that issue

2022-11-09 12:15 UTC, merged