Animation improvements for dApp info window
tallycash/extension pull request #2562
Opened 2022-11-07 08:35 UTC by kkosiorowska

Closes #2524 

This PR makes the animations for dApp info window more friendly for users.

UI

https://user-images.githubusercontent.com/23117945/200262240-32f044c5-065f-4a47-a1e2-86813f94ed2d.mov

https://user-images.githubusercontent.com/23117945/200260276-7bc506c3-cc8a-45a9-b683-df5f4a89ab0a.mov

https://user-images.githubusercontent.com/23117945/200260287-c47f66c4-cd95-4490-a1fd-fb076274a31b.mov

To Test
- [ ] check how the transition looks when the user opened the window
- [ ] check how the transition looks when the user disconnected the app  
- [ ] check how the transition looks when the user closed/opened the accordion. Make sure the tooltip for the default wallet is displayed correctly.

2022-11-07 12:05 UTC, jagodarybacka requested changes

2022-11-07 12:05 UTC, jagodarybacka commented on ui/components/Shared/SharedAccordion.tsx
> +      setTimeout(() => {
if you are using timeouts then you have to make sure you destroy them before the component is unmounted

2022-11-07 14:16 UTC, greg-nagy approved these changes
code looks good, works well

waiting for a @VladUXUI sign off before merge

2022-11-07 16:19 UTC, hyphenized approved these changes
Looks much better, nice work!

2022-11-07 16:19 UTC, hyphenized commented on ui/components/Shared/SharedAccordion.tsx
>    const [height, setHeight] = useState(0)
We probably want to initialize this to `contentHeight` if it's available and `isInitiallyOpen` is truthy

2022-11-08 10:43 UTC, jagodarybacka approved these changes
Looks very nice ✨

2022-11-08 10:44 UTC, merged