Normalize token lists contract addresses
tallycash/extension pull request #2580
Opened 2022-11-09 07:36 UTC by hyphenized

Closes #1898

2022-11-10 00:43 UTC, mhluongo commented
So excited for this one! Likely also an opportunity to use a nominal typing technique @Shadowfiend brought up recently... reviewing now

2022-11-11 18:49 UTC, 0xDaedalus commented on background/services/indexing/db.ts
> +          typeof record.chainId !== "undefined" &&
Should this be `typeof record.chainId === "undefined" || typeof record.address === "undefined"`?

I would expect that either one of those missing would mean the given record is invalid - no?

2022-11-11 18:49 UTC, 0xDaedalus commented on background/services/indexing/index.ts
> -    return found as SmartContractFungibleAsset
`as` strikes again.

2022-11-11 18:49 UTC, 0xDaedalus commented on background/services/indexing/index.ts
> +    const normalizedAddress = normalizeEVMAddress(contractAddress)
Love the explicit variable naming

2022-11-11 18:49 UTC, 0xDaedalus commented on background/services/indexing/index.ts
> -      forceBalance: {
rather than removing this - I think it makes more sense to change `runAtStart` to false.

The code written as is erroneously checks for balance updates at start - but also forces balance updates every 12 hours after start.  Wether we need the latter functionality or not is definitely debatable - but lets wait until we have some analytics data before getting rid of it entirely.

2022-11-11 18:49 UTC, 0xDaedalus commented on background/services/indexing/index.ts
> +            this.cachedAssets[addressOnNetwork.network.chainID].filter(
Lets use the `getCachedAssets` method here to stay consistent with the rest of the codebase

2022-11-11 18:49 UTC, 0xDaedalus commented on background/services/indexing/db.ts
> +        Object.assign(record, {
Spicy 🌶️

2022-11-13 22:22 UTC, mhluongo commented on background/services/indexing/db.ts
> +          typeof record.chainId !== "undefined" &&
I can confirm that `chainId` is often `undefined` / missing in the wild, and in that case should be defaulted to mainnet

2022-11-15 00:14 UTC, hyphenized commented on background/services/indexing/db.ts
> +          typeof record.chainId !== "undefined" &&
> I would expect that either one of those missing would mean the given record is invalid - no?
Yeah I was just being safe here. I was not aware of `chainId` possibly being `undefined` in some cases 👀

2022-11-16 19:48 UTC, mhluongo commented on background/services/indexing/db.ts
> +          typeof record.chainId !== "undefined" &&
It could be in an older version of the schema, perhaps? Just confident I've seen it in real-world token lists :upside_down_face:

2022-11-17 13:29 UTC, greg-nagy commented on background/services/indexing/db.ts
> +          typeof record.chainId !== "undefined" &&
paranoid is good

2022-11-17 13:33 UTC, greg-nagy commented on background/services/indexing/index.ts
> +      tokenListLoad.then(() => this.handleBalanceAlarm())
Why mixing await and then? `await tokenListLoad; this.handleBalanceAlarm()` should also work here, right?

2022-11-17 13:34 UTC, greg-nagy commented on background/services/indexing/index.ts
> +  getKnownSmartContractAsset(
I am always torn with this, but in the end I think this the right path.

2022-11-17 13:51 UTC, greg-nagy reviewed
Love this PR and the fix!

I was testing the migrations:
- checkout main 
- yarn start
- import seed
- click all networks to activiate them 
- checkout branch
- restart build 
- reload extension 

I would like to get another set of eyes on this before merge. 

The code looks good. 

The PR description would be good to have the `what, how, why, test` structure.

Love the clean commit history 🙇‍♂️

2022-11-17 13:51 UTC, greg-nagy commented on background/services/indexing/db.ts
> +        Object.assign(record, {
and no need for eslint disable ... :)

2022-11-17 15:58 UTC, 0xDaedalus commented on background/services/indexing/index.ts
> +      tokenListLoad.then(() => this.handleBalanceAlarm())
I think this implementation is correct - we don't want loading the token list to block initializing the indexing service

2022-11-17 18:44 UTC, 0xDaedalus commented on background/services/indexing/db.ts
> +          typeof record.chainId !== "undefined" &&
My point here is that a record with a `chainId` of `1` and an address of `0x2d...` would be marked as invalid with the current boolean logic right?

```
typeof 1 !== "undefined" // type is number, true
&&
typeof "0x2d..." !== "undefined" // type is string, true
```

2022-11-17 18:47 UTC, 0xDaedalus requested changes
Tested - functionality looks good!  I think we need to change the boolean logic (or variable naming) mentioned above though in order to avoid confusion down the line.  Lets make sure to re-test after we do.

2022-11-17 19:19 UTC, hyphenized commented on background/services/indexing/db.ts
> +          typeof record.chainId !== "undefined" &&
Ahh I think I get where you're going, it would be marked as invalid but that should be the case for every token list asset that hasn't been transformed through [`tokenListToFungibleAssetsForNetwork`](https://github.com/tallycash/extension/blob/8ffb7c969efd8cedb826d803b28b4f7df46fa2ef/background/lib/token-lists.ts#L61) right?

2022-11-18 09:56 UTC, jagodarybacka commented on background/constants/currencies.ts
> +  contractAddress: "0xdeaddeaddeaddeaddeaddeaddeaddeaddead0000",
shouldn't the contract address be normalized?

2022-11-18 14:56 UTC, hyphenized commented on background/constants/currencies.ts
> +  contractAddress: "0xdeaddeaddeaddeaddeaddeaddeaddeaddead0000",
Yes, I normalized it to be consistent with the new token list changes

2022-11-18 14:58 UTC, 0xDaedalus approved these changes
📈

2022-11-18 14:58 UTC, merged