Component tests for keyring behavior
tallycash/extension pull request #2621
Opened 2022-11-14 19:12 UTC by kkosiorowska

Closes #2231 

This PR adds component tests for keyring behavior at the UI level. 

Changes:
- tests for Signing Button component
- tests for Keyring Unlock component
- tests for  Shared Current Account Information component
- add test utils

2022-11-14 21:50 UTC, 0xDaedalus requested changes
Looks great - largely non blocking comments but I do want to maintain as much separation between our test code and our application code as possible - so I think we need to move `initializeStoreForTest` out of our main application code.

2022-11-14 21:50 UTC, 0xDaedalus commented on background/main.ts
> +export const initializeStoreForTest = (
This feels like it should be in the test-utils file

2022-11-14 21:50 UTC, 0xDaedalus commented on ui/components/AccountsNotificationPanel/__tests__/SigningButton.test.tsx
> +  test("should go to the unlocking page after clicking when the wallet is locked", async () => {
`after being clicked`

2022-11-14 21:50 UTC, 0xDaedalus commented on ui/components/AccountsNotificationPanel/__tests__/SigningButton.test.tsx
> +  test("should go to the root page after clicking when the wallet is unlocked", async () => {
`after being clicked`

2022-11-14 21:50 UTC, 0xDaedalus commented on ui/components/Keyring/__tests__/KeyringUnlock.test.tsx
> +  test("should not unlock the wallet", async () => {
We want to be extra descriptive with these test names so that in case they fail the developer looking at the failures has the maximum reasonable amount of context we can give them.  Maybe `should not unlock the wallet when an incorrect password is submitted`

2022-11-14 21:50 UTC, 0xDaedalus commented on ui/components/Keyring/__tests__/KeyringUnlock.test.tsx
> +const password = "password"
```suggestion
const password = "an_invalid_password"
```

2022-11-14 21:50 UTC, 0xDaedalus commented on ui/components/Shared/__tests__/SharedCurrentAccountInformation.test.tsx
> +const shortenedAddress = "Shortened Address"
```suggestion
const shortenedAddress = "0x208e…090cd"
```

2022-11-14 21:50 UTC, 0xDaedalus commented on ui/utils/test-utils.tsx
> +import React, { PropsWithChildren } from "react"
What do you think about creating a `/ui/tests` folder and putting this file in there?

2022-11-15 07:25 UTC, kkosiorowska commented on ui/utils/test-utils.tsx
> +import React, { PropsWithChildren } from "react"
I think it's a great idea. Let's do it.

2022-11-15 17:40 UTC, 0xDaedalus approved these changes
👑

2022-11-15 17:43 UTC, merged