Add NFTs page to the wallet
tallycash/extension pull request #2640
Opened 2022-11-17 08:05 UTC by kkosiorowska

Closes #2595 

This PR adds an NFTs page to the wallet.

Changes:
- create a new feature flag `HIDE_NFTS`
- add a new NFTs tab to the bottom ribbon
- move the swap page to the Wallet page

**UI**

Before
<img width="240" alt="Screenshot 2022-11-17 at 09 02 20" src="https://user-images.githubusercontent.com/23117945/202389906-a5910bb7-d7c9-4332-8943-dbc9c74bf1a5.png">

After
<img width="240" alt="Screenshot 2022-11-17 at 09 03 40" src="https://user-images.githubusercontent.com/23117945/202390382-19018e28-3286-4d10-8449-37101f6fbc59.png">

**To test**
Set up `HIDE_NFTS` to `false`.
- [ ] check that the NFTs tab is added to the bottom ribbon
- [ ]  check if the swap tab is removed from the bottom ribbon
- [ ] check that the swap page is moved to the Wallet page

2022-11-17 14:38 UTC, mhluongo commented on .env.defaults
> +HIDE_NFTS=true
We should prefer "SHOW_NFTS=false" as the default, or alternatively something like "SUPPORT_NFT_TAB".

2022-11-22 09:04 UTC, greg-nagy commented on ui/components/Wallet/WalletAccountBalanceControl.tsx
> +                <div className="actions_button_wrap">
This should also depend on the feature flag.

2022-11-22 14:02 UTC, jagodarybacka approved these changes
Non-blocking comment, I think it is fine :)

Will wait for @VladUXUI to take a look too

2022-11-22 16:13 UTC, jagodarybacka approved these changes
✅

2022-11-22 18:58 UTC, greg-nagy requested changes
This looks good, and works well! 

Nice job here 🚀

After blockers are fixed this is good to merge.

2022-11-22 19:36 UTC, hyphenized requested changes
Great work! Left some comments.

2022-11-22 19:36 UTC, hyphenized commented on ui/components/Shared/SharedSquareButton.tsx
> +  }
We can let the parent component handle navigation through the `onClick` prop

e.g.
```tsx
function BiggerComponent(){
  ...
  const history = useHistory();
  ...
  return <...>
    <SharedSquareButton onClick={()=> history.push("/somewhere") }>somewhere</SharedSquareButton>
  </...>
}

2022-11-22 19:36 UTC, hyphenized commented on ui/components/Wallet/WalletAccountBalanceControl.tsx
> +                  <div className="button_wrap">
I think these buttons should only change if the feature flag is enabled

2022-11-22 19:40 UTC, mhluongo commented
@VladUXUI @mr-michael this is the sort of change that could grow or shrink swap volume significantly. Wanted to make sure you both were sure that's where we want the swap page, and that we're keeping track of rough per-install swap volume so we can revert if it's negative.

2022-11-23 06:27 UTC, VladUXUI commented
> Non-blocking comment, I think it is fine :)
> 
> Will wait for @VladUXUI to take a look too

Looking good! yes the button on the asset cards can remain

2022-11-23 06:31 UTC, VladUXUI commented
> @VladUXUI @mr-michael this is the sort of change that could grow or shrink swap volume significantly. Wanted to make sure you both were sure that's where we want the swap page, and that we're keeping track of rough per-install swap volume so we can revert if it's negative.

Swaps had a very different account/network context than the rest of the pages, so imo had to be moved. The placement is one that users are very familiar with as this is a pattern employed by most extensions or application wallets.
I don't think it's more difficult to find there then it would be in our main menu. We also have swaps button in more places than your usual extension/app.
Fairly confident it won't negatively affect our swaps volume, but good point about tracking! Will do that and see if we need to revert

2022-11-23 06:33 UTC, VladUXUI approved these changes

2022-11-23 08:42 UTC, kkosiorowska commented on ui/components/Shared/SharedSquareButton.tsx
> +      <div className="content_wrap">
Let's make it simple.

2022-11-23 14:58 UTC, greg-nagy approved these changes
looks good, let's 🚢

2022-11-23 14:59 UTC, merged