Create NFTs components
tallycash/extension pull request #2667
Opened 2022-11-23 14:44 UTC by jagodarybacka

In progress....

2022-11-28 06:41 UTC, hyphenized commented
Nice work, it's looking good! Some initial comments: 
- Some of the NFT previews are very heavy (30Mb~), we should use simple hash sized previews when available to limit the amount of bandwidth we're using to load thumbnails/media and the resources used by the browser to render them.
- The [API response](https://api.simplehash.com/api/v0/nfts/owners?chains=ethereum&wallet_addresses=0xd8da6bf26964af9d7eed9e03e53415d37aa96045&collection_id=003b5a188936918e8015ee07068738c2) for some NFTs does not contain name/description/media properties. I think this might be the case for a lot of spam tokens so we should probably add a fallback for these cases or filter them out altogether
- I'm seeing some performance issues when scrolling/expanding collections that we might be able to solve with virtual lists, since, they are most likely coming from rendering a large number of items.

2022-11-28 14:10 UTC, jagodarybacka commented
@hyphenized 

> NFT previews are very heavy
> performance issues when scrolling/expanding collections

Performance issues are waiting to be done later this sprint, let's not block this PR. I will probably need your help with it 😊 

> this might be the case for a lot of spam tokens

Lack of name or any other props is not the signal that this NFT is a spam, SH is indexing NFTs with a delay (after they are minted) so for example a lot of Galxe NFTs don't have image or title right after the user mints them. But they are visible in the wallet immediately and user can open them on Galxe. 
Follow up PR will fallback to "no title" and correct "no preview" img.

2022-11-29 07:35 UTC, hyphenized requested changes
Looks amazing 💯! Can't wait to ship this to our users! 

>Lack of name or any other props is not the signal that this NFT is a spam, SH is indexing NFTs with a delay (after they are minted) so for example a lot of Galxe NFTs don't have image or title right after the user mints them. But they are visible in the wallet immediately and user can open them on Galxe.

I see, appreciate the explanation. Left some comments and questions

2022-11-29 09:06 UTC, kkosiorowska reviewed
It's looking amazing! :fire: Just some non-blocking comments.

2022-11-29 14:04 UTC, jagodarybacka commented on ui/_locales/en/messages.json
> +      "view": "view details"
yup, that's the design in Figma
<img width="188" alt="image" src="https://user-images.githubusercontent.com/20949277/204549857-375a6e2d-1776-42be-974b-5a976cc0f207.png">

2022-11-29 14:42 UTC, jagodarybacka commented on ui/components/Shared/SharedNetworkIcon.tsx
> +        .icon_network_wrapper {
yeah as we have a version with and without a transparent background

2022-11-29 14:44 UTC, jagodarybacka commented on background/redux-slices/nfts_update.ts
> +    nfts: [],
from redux point of view - NFTs should be added to collection and removed as needed - basically I want to treat redux as a cache. Removing NFTs no longer owned is not yet implemented. To be improved in this sprint

2022-11-29 14:44 UTC, jagodarybacka commented on ui/components/Shared/SharedSlideUpMenu.tsx
> +            z-index: 2;
we are not using them often but I agree :)

2022-11-29 14:47 UTC, jagodarybacka commented on ui/components/NFTS_update/NFTItem.tsx
> +          isCollection={isCollection}
but then we would need whole icons object from NFTHover in the component above (NFTItem) as this is both icon but also label, background, size etc

2022-11-29 14:48 UTC, jagodarybacka commented on ui/components/NFTS_update/NFTItem.tsx
> +    "floorPrice" in item && item.floorPrice?.value && item.floorPrice
will add a function when I will write this 3th time :P

2022-11-29 14:53 UTC, jagodarybacka commented on ui/components/NFTS_update/NFTList.tsx
> +    collection: NFTCollectionCached
good catch!

2022-11-29 15:43 UTC, hyphenized approved these changes
Looks good!

2022-11-29 15:43 UTC, merged