Add NFTs empty state
tallycash/extension pull request #2669
Opened 2022-11-23 21:22 UTC by hyphenized

<img width="368" title="fancygradient" src="https://user-images.githubusercontent.com/28708889/203647778-240a84dc-dd1b-411a-89d4-aa650d85df62.png"/>

## Testing Env

```
SUPPORT_NFT_TAB=true
```

## To Test
- [ ] Remove all accounts, the header with the empty state should be visible

2022-11-23 21:36 UTC, hyphenized commented
@VladUXUI please check the design, ignore the casing in the tab's title, it's related to a bug being addressed in #2664

2022-11-24 07:49 UTC, jagodarybacka commented
@VladUXUI I think buttons should be "OpenSea" and "LooksRare" as that's how they have it on their logos

2022-11-24 08:02 UTC, jagodarybacka requested changes
Very nice ✨ Couple things I noticed + can we get marketplace icons in about the same size? it doesn't matter that much here probably as they are very small anyway but would be nice

2022-11-24 16:08 UTC, VladUXUI commented
> @VladUXUI please check the design, ignore the casing in the tab's title, it's related to a bug being addressed in #2664

looks good! need to separate them into tabs though.

2022-11-24 16:08 UTC, VladUXUI commented
> @VladUXUI I think buttons should be "OpenSea" and "LooksRare" as that's how they have it on their logos

agreed! thanks for noticing

2022-11-24 16:10 UTC, VladUXUI commented on ui/components/NFTS_update/NFTsExploreBanner.tsx
> +function ExploreLink({
For this instance, let's not use a button style. As the CTA's become tangled a bit.
But i'm ok if we use current design with icon on the right side and no border.

My bad for not being consistent with placement of icon/logo

2022-11-25 09:30 UTC, greg-nagy commented on ui/components/NFTS_update/ExploreMarketLink.tsx
> +type ExporeMarketLinkProps = {
typo

2022-11-25 11:05 UTC, greg-nagy requested changes
this is looking really good 🤩

The topbar should not be visible here. I think the #2664 broke [its hidden mechanism](https://github.com/tallycash/extension/blob/e4a46d75b7490073f64b54d460672cbffbb8bc7f/ui/pages/Popup.tsx#L211), but haven't played it out fully. 

![CleanShot 2022-11-25 at 10 49 22](https://user-images.githubusercontent.com/7690112/203952968-f6af81a7-f5e2-4753-abb8-66cf5ee810df.png)

The other blocker is the has no nft vs has no account change.

2022-11-25 12:55 UTC, hyphenized commented on ui/pages/NFTs.tsx
> +  const hasAccounts = useBackgroundSelector(getHasAccounts)
Ooops! You're right! Thanks for catching that!

2022-11-25 12:56 UTC, hyphenized commented on ui/components/NFTS_update/ExploreMarketLink.tsx
> +type ExporeMarketLinkProps = {
Thanks! Nice extension 👀

2022-11-25 13:04 UTC, hyphenized commented
> this is looking really good 🤩
> 
> The topbar should not be visible here. I think the #2664 broke [its hidden mechanism](https://github.com/tallycash/extension/blob/e4a46d75b7490073f64b54d460672cbffbb8bc7f/ui/pages/Popup.tsx#L211), but haven't played it out fully.
> 
> ![CleanShot 2022-11-25 at 10 49 22](https://user-images.githubusercontent.com/7690112/203952968-f6af81a7-f5e2-4753-abb8-66cf5ee810df.png)
> 
> The other blocker is the has no nft vs has no account change.

Hmmm I can't get the topbar to appear, can you try switching between tabs and see if that clears the bug 🤔 ?

2022-11-25 13:50 UTC, greg-nagy commented
> > this is looking really good 🤩
> > The topbar should not be visible here. I think the #2664 broke [its hidden mechanism](https://github.com/tallycash/extension/blob/e4a46d75b7490073f64b54d460672cbffbb8bc7f/ui/pages/Popup.tsx#L211), but haven't played it out fully.
> > ![CleanShot 2022-11-25 at 10 49 22](https://user-images.githubusercontent.com/7690112/203952968-f6af81a7-f5e2-4753-abb8-66cf5ee810df.png)
> > The other blocker is the has no nft vs has no account change.
> 
> Hmmm I can't get the topbar to appear, can you try switching between tabs and see if that clears the bug 🤔 ?

hm, it was a really weird behavior on my end — couple of restarts and reinstalls has fixed the issue

2022-11-25 13:52 UTC, greg-nagy approved these changes
this is ready to be merged ⚒

2022-11-25 13:52 UTC, merged