🛑Add Stats to NFT header
tallycash/extension pull request #2670
Opened 2022-11-23 21:32 UTC by hyphenized

<img width="368" title="nftstats" src="https://user-images.githubusercontent.com/28708889/203649108-a3578ab3-83c4-4248-9589-fabf6549d903.png"/>

## Testing Env

```
SUPPORT_NFT_TAB=true
```

## To Test
- [ ] Import an account
- [ ] Go to the new NFTs page, after loading, counts and estimates should show up for that account

2022-11-24 08:08 UTC, kkosiorowska commented
The NFT header overlaps the account information.

![Screenshot 2022-11-24 at 09 06 28](https://user-images.githubusercontent.com/23117945/203727451-5eae1a22-29ee-4ddb-86ac-405b32632e8e.png)

2022-11-24 08:17 UTC, kkosiorowska commented on ui/components/NFTS_update/NFTsHeader.tsx
> +          <strong>{collections}</strong>{" "}
```suggestion
          <strong>{collections}</strong> {t("units.collection", { count: collections })}
```

2022-11-24 08:34 UTC, kkosiorowska reviewed
This looks good! Left some comments

2022-11-24 08:39 UTC, jagodarybacka commented on ui/components/Shared/SharedLoadingSpinner.tsx
> +  const { size, variant = "dark-gold" } = props
Is there any advantage to using `defaultProps`? I prefer destructuring version because that way I can see the default value as I'm reading the code top-to-bottom while default props are below the component code

2022-11-24 08:51 UTC, kkosiorowska commented on ui/components/Shared/SharedLoadingSpinner.tsx
> +  const { size, variant = "dark-gold" } = props
From my perspective, it's just clearer for shared components because some of them are using `defaultProps`.

2022-11-24 15:10 UTC, hyphenized commented on ui/components/NFTS_update/NFTsHeader.tsx
> +          <strong>{collections}</strong>{" "}
Nice catch! Fixing this through CSS also improved the display for big amounts:


<img width="368" src="https://user-images.githubusercontent.com/28708889/203816313-1fa071db-bc6f-4f5e-ba45-28637a2216d7.png" />

2022-11-24 15:12 UTC, hyphenized commented on ui/components/Shared/SharedLoadingSpinner.tsx
> +  const { size, variant = "dark-gold" } = props
I prefer destructuring too, `defaultProps` also makes it a bit trickier to forward refs and, it looks like it's still on track to [get deprecated](https://github.com/facebook/react/blob/2655c9354d8e1c54ba888444220f63e836925caa/packages/react-dom/src/__tests__/ReactFunctionComponent-test.js#L370) 👀

2022-11-24 15:31 UTC, VladUXUI requested changes
Looking good!
Couple of small notes:

Estimated total NFT value & eth value should be var-green-20 (looks like they are, or my eyes are deceiving me?)

$ sign should be aligned top with Amount

2022-11-24 16:03 UTC, hyphenized commented
@VladUXUI Fixed `Estimated value...` color and the sign's alignment

2022-11-24 16:03 UTC, VladUXUI approved these changes

2022-11-25 11:09 UTC, jagodarybacka commented
Are you sure about base branch change? https://github.com/tallycash/extension/pull/2669 is in review so basically this PR is blocked right?

2022-11-25 13:54 UTC, greg-nagy commented
c'mon github, don't be like that

2022-11-25 14:27 UTC, greg-nagy approved these changes
🚀

2022-11-25 14:27 UTC, merged