Per-message queueing and Failover
tallycash/extension pull request #2696
Opened 2022-11-29 23:48 UTC by 0xDaedalus

2022-11-30 01:15 UTC, 0xDaedalus commented on background/services/chain/serial-fallback-provider.ts
> +const ALCHEMY_RPC_CALL_PERCENTAGE = 0
Important change here to take note of.

2022-12-01 09:41 UTC, jagodarybacka commented on background/services/chain/tests/serial-fallback-provider.integration.test.ts
> +      expect((fallbackProvider as any).currentProviderIndex).toEqual(0)
Can we fix these lint errors as they will come up with every PR otherwise?

2022-12-01 09:41 UTC, jagodarybacka commented on background/services/chain/serial-fallback-provider.ts
>  // Wait 15 seconds between primary provider reconnect attempts.
```suggestion
// Wait 10 seconds between primary provider reconnect attempts.
```

2022-12-01 12:48 UTC, 0xDaedalus commented on background/services/chain/tests/serial-fallback-provider.integration.test.ts
> +      expect((fallbackProvider as any).currentProviderIndex).toEqual(0)
Yup of course - will fix with clarifying comment

2022-12-05 16:10 UTC, greg-nagy requested changes
Wow, this has been the heaviest PR for a while now ... 

I think there are multiple issues that should be fixed, but wow ...

The blocker problems 
- `shouldSendMessageOnNextProvider` logic fix
- fixing the tests to fail properly first
- I am not sure if the fallback logic is faulty or the test mocking but it might be both

2022-12-05 16:10 UTC, greg-nagy commented on background/services/chain/serial-fallback-provider.ts
> +    if (backoffCount && backoffCount < MAX_RETRIES_PER_PROVIDER) {
`backoffCount` is initialised with 0 > this will result false for the first time — which is correct just a bit misleading

2022-12-05 23:36 UTC, 0xDaedalus commented on background/services/chain/tests/serial-fallback-provider.integration.test.ts
> +      genericSendStub.onCall(0).throws("bad response")
This is because its succeeding on the 4th call of `genericSendStub` when you change the test code as you have in your example

When you mock the response of `eth_chainId` as `bad response` ethers attempts to get the chainid by requesting `net_version` - so you need to make the 4th call throw as well.

You can see the test fail either by using

```
      genericSendStub.onCall(0).throws("bad response")
      genericSendStub.onCall(1).throws("bad response")
      genericSendStub.onCall(2).throws("bad response")
      genericSendStub.onCall(3).throws("bad response")
      alchemySendStub.onCall(0).throws("bad response")
      alchemySendStub.onCall(1).throws("bad response")
      alchemySendStub.onCall(2).throws("bad response")
      alchemySendStub.onCall(3).throws("bad response")
```
or
```
genericSendStub.throws("bad response")
alchemySendStub.throws("bad response")
```

2022-12-05 23:48 UTC, 0xDaedalus commented on background/services/chain/tests/serial-fallback-provider.integration.test.ts
> +      // eth_chainId is called once in the constructor
Despite our eth_chainId cacheing we do not actually cache the chainId on a per-provider basis - and ethers [does request eth_chainId](detectNetwork) through our `super` call in the SerialFallbackProvider constructor.

I think the reason you're seeing a callCount of `0` before the `send` is ethers need to do some async things in the background before it is "ready" - I suspect if you wait a promise for 10ms before calling send you'll see the `callCount` be 1 rather than 0

2022-12-05 23:49 UTC, 0xDaedalus commented on background/services/chain/serial-fallback-provider.ts
> +          /WebSocket is already in CLOSING|bad response|missing response|we can't execute this request/
I think it might but that felt like a big change to tack on to this already big PR (debugging / QA surface increases significantly with this I think)

2022-12-06 00:00 UTC, 0xDaedalus commented on background/services/chain/serial-fallback-provider.ts
> +    if (method === "eth_getBalance" && (params as string[])[1] === "latest") {
You're totally right although this is already existing functionality.  I bet this might be the reason why Nax has been seeing OOM errors when using Tally lately.  Let me see if I can come up with an elegant solution in another PR.

2022-12-06 00:02 UTC, 0xDaedalus commented on background/services/chain/serial-fallback-provider.ts
> +        Math.random() < ALCHEMY_RPC_CALL_PERCENTAGE / 100
I think we still want a dial we can tune in case of emergencies - leaving this code in will give us an easily changeable dial.

2022-12-06 00:18 UTC, 0xDaedalus commented on background/services/chain/serial-fallback-provider.ts
> +    if (backoffCount && backoffCount < MAX_RETRIES_PER_PROVIDER) {
Great catch - and that initialization with `0` is why the tests were seemingly passing.

I've gone ahead and fixed the issue and changed the related tests a bit so we are explicitly checking for how many times we're calling `send` with `eth_getBalance`.  Should be less brittle than strictly asserting on call count and more readable as well.

2022-12-06 00:19 UTC, 0xDaedalus commented on background/services/chain/serial-fallback-provider.ts
> +          if (this.currentProviderIndex + 1 < this.providerCreators.length) {
I don't know if we should cycle - we risk getting stuck in a loop and draining the users machine of resources constantly making http requests.  To me it feel like if we want better redundancy a relatively straightforward way we can go about it is to add more providers to our list of providers of providerCreators

2022-12-06 11:27 UTC, greg-nagy approved these changes
let's 🚀

2022-12-06 11:30 UTC, merged