Add NFTs list to the assets selector
tallycash/extension pull request #2699
Opened 2022-11-30 15:48 UTC by hyphenized

https://user-images.githubusercontent.com/28708889/204843967-eee6c8fc-2a05-4d61-b884-063810307b24.mov

Closes #2644

2022-12-01 10:58 UTC, jagodarybacka requested changes
This PR is so awesome 💖 A lot of improvements that I will reuse 🙇 

I don't want you to spend a lot more time on this right now as Send is not the first prio so let's make some quick improvements

- [x] please fix padding here 
![image](https://user-images.githubusercontent.com/20949277/205034200-4d26e88b-f321-4ed1-8764-1d39d6dab0c1.png)

- [x] max button doesn't make sense for nfts 
![image](https://user-images.githubusercontent.com/20949277/205034478-e41520b2-f97a-463b-b013-aced2df0cc41.png)

2022-12-01 10:58 UTC, jagodarybacka commented on background/nfts.ts
> +  previewURL?: string
I think we can make `thumbnail` and `previewURL` follow the same rules so default to either `undefined` or empty string.

And make `thumbnail` -> `thumbnailURL`

2022-12-01 10:58 UTC, jagodarybacka commented on ui/components/Send/NFTCollectionAccordion.tsx
> +                      `}
```suggestion
          customStyles="margin: 12px 0 auto;"
```

2022-12-01 10:58 UTC, jagodarybacka commented on ui/components/Send/NFTCollectionAccordion.tsx
> +          .nft_collection :global(img) {
Can we add `styles`/`customStyles` prop to the component instead of these global styles?

2022-12-01 10:58 UTC, jagodarybacka commented on ui/components/Send/NFTCollectionListItem.tsx
> +        div :global(img) {
Same here - I feel safer with passing styles than using styled-jsx globals as we had some weird buggy styles conflicts in the past

2022-12-01 10:58 UTC, jagodarybacka commented on ui/pages/Send.tsx
> +                isEnabled(FeatureFlags.SUPPORT_NFT_TAB)
It should be `SUPPORT_NFT_SEND` but I will change it when my PR with this flag will be merged :)

2022-12-01 10:58 UTC, jagodarybacka commented on background/lib/simple-hash_update.ts
> +    (previews?.image_medium_url || previews?.image_large_url || fullsizeURL) ??
I think in the worst case we can fallback to small instead of undefined

2022-12-01 10:58 UTC, jagodarybacka commented on ui/components/Send/NFTCollectionAccordion.tsx
> +              const { contract } = collection.nfts[0] ?? {}
If SH doesn't include contract on collection level then it maybe means we shouldn't show it here. Is contract always the same for every nft in collection? 

For now can we visually disable this icon if it is not clickable?

2022-12-02 17:19 UTC, hyphenized commented on ui/components/Send/NFTCollectionAccordion.tsx
> +              const { contract } = collection.nfts[0] ?? {}
> Is contract always the same for every nft in collection
Yes, a contract may have multiple collections too. It might be different in other networks 🤔

2022-12-02 17:20 UTC, hyphenized commented on background/lib/simple-hash_update.ts
> +    (previews?.image_medium_url || previews?.image_large_url || fullsizeURL) ??
I agree but if we don't receive the `fullsizeURL` then I think we won't have a small size preview either

2022-12-02 17:21 UTC, hyphenized commented on ui/components/Send/NFTCollectionListItem.tsx
> +        div :global(img) {
Yeah that sounds like a much better idea, these global styles could also be easily missed

2022-12-02 17:23 UTC, hyphenized commented on background/nfts.ts
> +  previewURL?: string
Good call, I've made both `undefined` and refactored `thumbnail` in `NFTCollection` to be consistent with this.

2022-12-05 09:30 UTC, jagodarybacka requested changes
Please test it with `SUPPORT_NFT_TAB=false` as this is the default for now - if you will reinstall the extension with this flag off then the `Send` page is throwing an error because it tries reading from the new NFTs Redux slice which is not yet created

2022-12-05 09:33 UTC, jagodarybacka commented on ui/components/Send/NFTCollectionAccordion.tsx
> +              const { contract } = collection.nfts[0] ?? {}
Will investigate it later, let's leave it like that for now

2022-12-06 09:33 UTC, hyphenized commented
> Please test it with `SUPPORT_NFT_TAB=false` as this is the default for now - if you will reinstall the extension with this flag off then the `Send` page is throwing an error because it tries reading from the new NFTs Redux slice which is not yet created

Thanks for catching this! Feature flagged the selector code to retrieve NFTs within the Send page

2022-12-06 11:24 UTC, jagodarybacka approved these changes
All good now, let's 🚢 
(let's not bother @VladUXUI for now as this is not finished, we can do one big feature's design review later)

2022-12-06 11:24 UTC, merged