Signing transactions
tallycash/extension pull request #471
Opened 2021-11-24 16:02 UTC by wojciech-turek

Created a selector for getting a gasFee from transaction-construction slice. New slide-up modal for
selecting network fee and updated to Send page UI as per design.

2021-11-24 16:24 UTC, Shadowfiend reviewed
Quick thoughts!

2021-11-24 16:24 UTC, Shadowfiend commented on background/services/chain/index.ts
> +      // browser.alarms.onAlarm.addListener(pollBlockPrices)
You can do this with the `super` call in the constructor[^1], just add an entry there that calls this function. This function can then focus on just doing the check instead of scheduling, and can be renamed to reflect that it's doing the action rather than setting up the polling. 

Also looked a little deeper and saw that `Main` is the one that currently sets this off. `internalStartService` here is the one that should call this polling function once to get the party started instead, at which point Main's call can be removed. 

[^1]: https://github.com/tallycash/tally-extension/blob/19ad0b15cf5b99d2af0671805b5382e5b557b59b/background/services/chain/index.ts#L131-L149

2021-11-24 16:24 UTC, Shadowfiend commented on ui/components/Shared/SharedAssetInput.tsx
> +              onChange={(e) => onAmountChanged(e.target.value)}
Why not `useCallback`?

2021-11-24 16:24 UTC, Shadowfiend commented on ui/components/Shared/SharedSlideUpMenu.tsx
> +    menuHeight = customSize || "600px"
Not blocking, but are these real sizes or are they all just "be tall enough to contain your contents"? If the latter, can we let the browser do the math for us somehow?

2021-11-24 16:24 UTC, Shadowfiend commented on ui/pages/Send.tsx
> +          .networkfee__settings {
I don't think we've been using this kind of class name structure fwiw. We *have* been using underscores for eg network_feee.

2021-11-24 18:51 UTC, henryboldi commented on ui/components/Shared/SharedSlideUpMenu.tsx
> +    menuHeight = customSize || "600px"
cc @VladUXUI

2021-11-25 11:00 UTC, wojciech-turek commented on ui/components/Shared/SharedSlideUpMenu.tsx
> +    menuHeight = customSize || "600px"
We could add "auto" for the height but we would need to change the animation, currently it breaks.

2021-11-25 11:01 UTC, wojciech-turek commented on ui/pages/Send.tsx
> +          .networkfee__settings {
Understood, I will correct it and follow same in the future.

2021-11-25 11:01 UTC, wojciech-turek commented on background/services/chain/index.ts
> +      // browser.alarms.onAlarm.addListener(pollBlockPrices)
I think I got it, will be in my new commit :)

2021-11-25 11:21 UTC, wojciech-turek commented on ui/components/Shared/SharedAssetInput.tsx
> +              onChange={(e) => onAmountChanged(e.target.value)}
I think there is no benefit of using `useCallback` here, the input of the address onChange function does not use it as well, so the second reason was consistency.

2021-11-25 12:51 UTC, Shadowfiend commented on ui/pages/Send.tsx
> +          .networkfee__settings {
Worth noting here that styled-jsx ensures the selectors are scoped to their containing component, which also reduces the arguments for some of the heavier CSS naming strategies as well.

2021-12-01 16:47 UTC, Shadowfiend requested changes
Left a lot of notes, but I think the only one that can't be handled in a new PR is the `hasSavedSeed` override, which we need to fix before merging to `main`.

2021-12-01 16:47 UTC, Shadowfiend commented on background/redux-slices/transaction-construction.ts
> +  "transaction/options",
Let's make this `update-options`. I would like to stay closely aligned between the action name and thunk variable.

Similarly, we should update the thunk prefix to be `transaction-construction` rather than just `transaction`.

2021-12-01 16:47 UTC, Shadowfiend commented on background/redux-slices/transaction-construction.ts
> +export const selectGasEstimates = createSelector(
One thing I'll flag is that we should probably update all our stuff about “gas estimates” to specifically say “gas price estimates” or “per gas fee estimates”, because transactions care both about *gas* (the compute units expended, for which we can set the `gasLimit`) and the gas *price* (expressed as `*FeePerGas` in EIP1559 and `gasPrice` in legacy transactions).

I would suggest we explore a naming that follows EIP1559, where we do something like `estimateFeePerGas`, `estimatedFeePerGas`, `selectEstimatedFeePerGas`, etc.

2021-12-01 16:47 UTC, Shadowfiend commented on background/services/chain/index.ts
> +          periodInMinutes: 2,
We may still want to use `process.env.BLOCKNATIVE_POLLING_FREQUENCY` to allow for customization here, though it needs to be in minutes.

2021-12-01 16:47 UTC, Shadowfiend commented on background/services/chain/index.ts
> +          this.handleBlockPricesAlarm()
This can directly call `this.pollBlockPrices()` rather than indirecting through a handler function, IMO. I think the handler functions only make sense if there's some additional work to do specific to the alarm, but here we're just calling the method.

2021-12-01 16:47 UTC, Shadowfiend commented on ui/components/Shared/SharedAssetInput.tsx
> +              type="number"
Bravissimo!

2021-12-01 16:47 UTC, Shadowfiend commented on ui/components/Shared/SharedSlideUpMenu.tsx
> +      }`}
Let's use `classNames` here:
```suggestion
      className={classNames("slide_up_menu", { large: size === "large", closed: !isOpen })`}
```

(Plus run `prettier` :grin:)

2021-12-01 16:47 UTC, Shadowfiend commented on ui/components/Wallet/WalletAccountBalanceControl.tsx
> +  const hasSavedSeed = true
:wave:

In general I would suggest pulling this from an env variable OR using the build mode (`process.env.NODE_ENV === "development"`) if you want to approach something in an interim way, otherwise we risk putting something in a public build that we don't want.

Another approach, which is still error-prone, is to make the change but never commit it (by using `git add`/`git add -i`/`git add -p` to ensure only other changes land).

2021-12-01 16:47 UTC, Shadowfiend commented on ui/pages/SignTransaction.tsx
> +import { useDispatch, useSelector } from "react-redux"
You should pretty much always be using `useBackgroundDispatch` and `useBackgroundSelector` in the UI, as they enrich the pipeline with typing from our slices.

2021-12-01 16:47 UTC, Shadowfiend commented on ui/pages/SignTransaction.tsx
> +      signContent[signType].confirmButtonText === "Sign" &&
Hmmm… Why are we keying off of the button text here instead of just the `SignType`?

2021-12-01 16:47 UTC, Shadowfiend commented on ui/pages/Send.tsx
> +  }
We should really be using the term `asset`, and `name` here is actually `symbol`. This should align better with naming across the stack.

`ETH` is not a token, for example :)

If we're only tracking the symbol, it feels reasonable to just have `assetSymbol` rather than an object structure with one property though?

2021-12-01 16:47 UTC, Shadowfiend commented on ui/pages/Send.tsx
> +interface GasOption {
This is something we've been sluggish to do but are finally zeroing in on: prefer using `type` over `interface`:

```suggestion
type GasOption = {
```

2021-12-01 16:47 UTC, Shadowfiend commented on ui/pages/Send.tsx
> +  )
What do you think about pulling this whole thing out to its own component that emits a single event, e.g. `onPerGasFeeSelected`, with the appropriate fee information? The `Send` component would directly track `maxFeePerGas` and `maxPriorityFeePerGas` in that scenario, and that's what would get updated with `onPerGasFeeSelected`.

2021-12-01 16:47 UTC, Shadowfiend commented on ui/pages/Send.tsx
> +                } ${token}`}</div>
Is this denominated in the asset being transferred, or is it the total main currency (= USD) spend from sending the token + fees?

2021-12-01 16:47 UTC, Shadowfiend commented on ui/pages/Send.tsx
> +          .network_fee__settings {
Again, we've been relying on the styled-jsx scoping to keep our selectors simple here. Let's use `.network_fee_settings`, `.network_fee > .settings` or just `.settings`, as makes the most sense.

2021-12-02 08:38 UTC, wojciech-turek commented on background/main.ts
>          // We need to convert the transaction to a EIP1559TransactionRequest before we can estimate the gas limit
Its gone

2021-12-02 08:40 UTC, wojciech-turek commented on background/main.ts
> +      "signRequest",
Changed as suggested.

2021-12-02 08:52 UTC, wojciech-turek commented on background/redux-slices/transaction-construction.ts
> +  signedTx: Partial<SignedEVMTransaction>
Correct and I am not sure if we need to keep the signed transaction in the state at all. I think not, I will remove it.

2021-12-02 08:54 UTC, wojciech-turek commented on background/redux-slices/transaction-construction.ts
> +  gasEstimates: BlockPrices
We're not, got rid of it.

2021-12-02 08:56 UTC, wojciech-turek commented on background/redux-slices/transaction-construction.ts
> +  "transaction/options",
100%

2021-12-02 09:18 UTC, wojciech-turek commented on background/redux-slices/transaction-construction.ts
> +export const selectGasEstimates = createSelector(
I have changed that but since we get multiple options I have uses plural form of fee, thought its even more descriptive.

2021-12-02 09:25 UTC, wojciech-turek commented on background/redux-slices/transaction-construction.ts
> +      { payload: options }: { payload: EIP1559TransactionRequest }
Absolutely

2021-12-02 09:28 UTC, wojciech-turek commented on background/redux-slices/transaction-construction.ts
> +  (status) => status === "signed"
I find it very clear that I fetch a true/false value from redux rather than getting a status and then comparing inside the component if it matches desired state. If we use `selectIsTransactionLoaded ` in more than one place in the future we reduce the code size. My vote is on keeping it this way.

2021-12-02 09:34 UTC, wojciech-turek commented on background/services/chain/index.ts
> +          this.handleBlockPricesAlarm()
Oh, very good catch. Sometimes I blindly follow what was used before and miss obvious choices I'd normally make. 🙇🏻

2021-12-02 09:41 UTC, wojciech-turek commented on ui/components/Shared/SharedSlideUpMenu.tsx
> +      }`}
Oh, neat, I was not using `classNames` before!

2021-12-02 09:48 UTC, wojciech-turek commented on ui/pages/SignTransaction.tsx
> +import { useDispatch, useSelector } from "react-redux"
Copy that

2021-12-02 09:59 UTC, wojciech-turek commented on ui/pages/SignTransaction.tsx
> +      signContent[signType].confirmButtonText === "Sign" &&
Hmmm good question, changed to `SignType.Sign === signType`

2021-12-02 10:02 UTC, wojciech-turek commented on ui/pages/SignTransaction.tsx
> +          onClick={handleConfirm}
Agree, once we have the loader designed from @VladUXUI we can base the loading status based on status from transaction-construction slice.

2021-12-02 10:08 UTC, wojciech-turek commented on ui/pages/Send.tsx
> +  )
I have moved that out in another PR but without setting an event, rather than that I just pass required items and use local state for handling selected gas. Works well but we can talk about a restructure if needed.

2021-12-02 10:10 UTC, wojciech-turek commented on ui/pages/Send.tsx
> +                  ).toFixed()}%)`,
I have made an assumption, that its a kind of a progress bar to show the current gas and max in a visual way, @VladUXUI please let me know how do you see it work.

2021-12-02 10:16 UTC, wojciech-turek commented on ui/pages/Send.tsx
> +                  amount || 0
I would incline towards leaving it as `||` as if amount ever happens to be an empty string I would prefer it to show 0 rather than nothing. What do you think?

2021-12-02 10:16 UTC, wojciech-turek commented on ui/pages/Send.tsx
> +                } ${token}`}</div>
Should be transfer amount + fees. That will land in a new PR.

2021-12-02 10:24 UTC, wojciech-turek commented on ui/pages/Send.tsx
> +          .network_fee__settings {
Got it, moving out of habits is not so easy haha

2021-12-02 15:24 UTC, Shadowfiend commented on background/services/chain/index.ts
> +            Number(process.env.BLOCKNATIVE_POLLING_FREQUENCY) / 60,
We should probably ` ?? 120` or something of the sort in case it's unset, otherwise we'll get a period of 0 (which I'm pretty sure still works and gets us a fixed 1-minute period, but…).

2021-12-02 15:30 UTC, Shadowfiend commented on background/redux-slices/transaction-construction.ts
> +    setTransactionRequest: (
So, what we've done elsewhere is not have the `set` prefix for the actions. I'm ambivalent about that approach and haven't had a chance to see if there's a preferred path suggested by redux-toolkit or a go-to approach in the community, but we're doing it in all slices right now… So I'm tempted to stick with that here.

2021-12-02 15:31 UTC, Shadowfiend commented on background/redux-slices/transaction-construction.ts
> +  (status) => status === "signed"
:thumbsup: I'm comfortable with keeping this for now. There's something about it that bugs me, but… I can't quite put my finger on it, so won't be pushing until I get a better feel for what I'm worried about.

2021-12-02 15:33 UTC, Shadowfiend commented on ui/components/Wallet/WalletAccountBalanceControl.tsx
> +  const hasSavedSeed = true
Haha I don't think you should, fwiw—feature flags are a great strategy, and this is basically a feature flag, we can just avoid hard-coding them and use the existing env mechanism :muscle:

2021-12-02 15:44 UTC, Shadowfiend commented on ui/pages/Send.tsx
> +                  amount || 0
I actually didn't realize this was a string, my bad.

I'm not that worried due to the fact that we're reworking this anyway to be the proper total, at which point this will look very different.

2021-12-02 15:48 UTC, Shadowfiend commented on ui/pages/Send.tsx
> +          .network_fee__settings {
This also applies to settings__image -> again, either `.settings_image` or `.settings > img`. Basically avoid double underscores :grin:

2021-12-02 15:48 UTC, Shadowfiend approved these changes
Left some tiny notes, but the main thing is fixed and almost everything else got hit, too! 🎊 

Let's get this sucker in :sunglasses:

2021-12-02 16:24 UTC, wojciech-turek commented on background/services/chain/index.ts
> +            Number(process.env.BLOCKNATIVE_POLLING_FREQUENCY) / 60,
Changed added, `?? 2`

2021-12-02 16:25 UTC, wojciech-turek commented on ui/pages/Send.tsx
> +      const instant = estimatedFeesPerGas.estimatedPrices.find(
Noted for future PR

2021-12-02 16:27 UTC, wojciech-turek commented on ui/pages/Send.tsx
> +          .network_fee__settings {
Changed that particular one, but theres more places like `fees__option__subtext` that needs to be changed, I will address that in a new PR.

2021-12-02 16:37 UTC, wojciech-turek commented on background/redux-slices/transaction-construction.ts
> +    setTransactionRequest: (
`set` no more :)

2021-12-02 17:02 UTC, Shadowfiend commented on background/services/chain/index.ts
> +            Number(process.env.BLOCKNATIVE_POLLING_FREQUENCY) / 60 ?? 2,
I don't think this will have the desired effect, as the `??` binds to the result of `Number(process.env.BLOCKNATIVE_POLLING_FREQUENCY) / 60`, which will never be `undefined`. Instead, I think we want this:

```suggestion
            Number(process.env.BLOCKNATIVE_POLLING_FREQUENCY ?? "2") / 60,
```

2021-12-02 17:02 UTC, Shadowfiend approved these changes
One minor nit, but since env defaults include the blocknative polling frequency I'm not worried about it. Let's land this now and handle after :rocket:

2021-12-02 17:20 UTC, Shadowfiend approved these changes
This is the part where I approve my own merge so when things are broken we all know it's my fault.

2021-12-02 17:20 UTC, merged

2021-12-03 11:06 UTC, wojciech-turek commented on background/services/chain/index.ts
> +            Number(process.env.BLOCKNATIVE_POLLING_FREQUENCY) / 60 ?? 2,
True that, I have corrected that in network fees PR. Thanks!