Fix Fairy: Fix a few nits and bugs in current main
tallycash/extension pull request #493
Opened 2021-12-01 04:06 UTC by Shadowfiend

During testing, we realized the asset price point conversions landed
in #490 weren't working quite as expected. This PR fixes that issue, as
well as a handful of others:
- All remaining React warnings in common paths are gone.
- Certain lookups that were waiting 1 minute to run due to being hooked up
  as alarms now run immediately.
- Initial balance checks for a new account are immediately followed by price
  checks for those assets.

2021-12-01 04:07 UTC, Shadowfiend commented on background/services/indexing/index.ts
> +        await this.handlePriceAlarm()
@mhluongo want your eyes on this specific change. It's overall fairly small, but want to make sure there aren't any concerns about rate limiting that I've missed.

2021-12-01 04:27 UTC, mhluongo commented on background/services/indexing/index.ts
> +        await this.handlePriceAlarm()
I'm not a huge fan without that `FIXME` getting `FIXED`... but I don't think this specifically will be a rate limiting issue. Accounts aren't added frequently enough.

More general rate limiting concerns are price checks are still a thing, of course.

2021-12-01 21:54 UTC, henryboldi requested changes
Great changes! The home tab loads everything in much faster!

However, after testing this locally, it looks like there's now an issue displaying the price in the overview tab,

<img width="300" alt="Loading" src="https://user-images.githubusercontent.com/1918798/144319957-f31a5b50-e24e-4396-95f3-8e81a1b61051.png">
<img width="300" alt="Timeout" src="https://user-images.githubusercontent.com/1918798/144319986-9b376917-fbb5-44e8-8187-65dec7796b46.png">

2021-12-02 03:28 UTC, Shadowfiend commented
Heh I was trying to figure this out and then realized it's because the enrichment functions didn't include unit price 😅 Oh well, good opportunity to move another field name away from the term “token” :grimacing:

2021-12-02 12:45 UTC, Shadowfiend commented
This should be fixed now.

2021-12-02 16:13 UTC, henryboldi approved these changes
Beautiful!

2021-12-02 16:14 UTC, merged