Wen Account Selector: Fill in the rest of the account selector data, adjust the wallet tab to only display current account
tallycash/extension pull request #502
Opened 2021-12-02 03:54 UTC by Shadowfiend

Still need to do some commit cleanup and a proper description here, but the code should remain steady. Some pretty big refactors here, but the real fun is in the last two commits. The accounts slice is (very) slowly trending towards what it should be.

Draft until I can finish writing things up here.

2021-12-03 04:31 UTC, Shadowfiend commented
There's an issue remaining with the back button on the single asset page, but it's present on main due to the onboarding flow changes that made it `position: fixed`. I should have flagged that, `position: fixed` in a shared component is always a recipe for disaster down the line haha.

I tried to fix it up but ran into some walls… @henryboldi could use some help with it, maybe as a separate PR?

2021-12-03 04:57 UTC, henryboldi commented
> I should have flagged that, position: fixed in a shared component is always a recipe for disaster down the line haha. I tried to fix it up but ran into some walls… @henryboldi could use some help with it, maybe as a separate PR?

Totally my bad! Yes, I'll open up a separate PR with a fix @Shadowfiend

2021-12-03 22:16 UTC, henryboldi requested changes
This is *chef's kiss*! A few questions and comments though,
1) After adding a new account, the wallet should probably switch to it by default

2) The avatar border should be rounded
<img width="156" alt="Avatar" src="https://user-images.githubusercontent.com/1918798/144679594-7b5ecb28-0bd3-49b7-a9bf-50d9f7e66540.png">

3) How about hiding this "add address" button? It could be confusing 
<img width="378" alt="add address" src="https://user-images.githubusercontent.com/1918798/144679688-1e309d1e-f5dd-4c74-b7e8-d7b7050ad468.png">

4) How do we feel about hiding the notifications tab in this PR?

2021-12-03 22:16 UTC, henryboldi commented on background/redux-slices/selectors/accountsSelectors.ts
> +export type AccountTotal = {
The `AccountTotal` naming is a tad confusing to me. To someone unfamiliar with the codebase, it might give the impression that it's some sort of total amount

2021-12-04 01:36 UTC, Shadowfiend commented
1. Yes 2. Yes but not doing it for this release in the interest of time 3. Yes 4. Yes.

2021-12-04 01:38 UTC, Shadowfiend commented on background/redux-slices/selectors/accountsSelectors.ts
> +export type AccountTotal = {
It's the account info + it's total balance, which is in line with how we've done eg AccountNetwork.

Would love a better name though--I don't love that pattern, but I couldn't come up with anything great after giving it some thought. 

Either way a jsdoc couldn't hurt.

2021-12-04 03:19 UTC, Shadowfiend commented
Ended up doing all of them + fixing a React console error. Notably, wanting to select the newly-added account led to also removing some hacky code that was in use for initial wallet startup :tada:

2021-12-04 04:39 UTC, mhluongo approved these changes
Non-controversial, LGTM!

2021-12-04 04:39 UTC, merged

2021-12-04 13:03 UTC, Shadowfiend commented on background/redux-slices/index.ts
> +export type RootState = ReturnType<typeof mainReducer>
It's overall better, otherwise we'd have to update every time we added a slice 🤷 DRY and all.

2021-12-06 19:09 UTC, henryboldi commented
Should this close #363?

2021-12-07 12:50 UTC, Shadowfiend commented
I'm interested in your take on that. I didn't set out to refactor the accounts slice as a goal, so there may still be some work to do if it's considered from that perspective.