Move fee selection logic to NetworkFeesChooser
tallycash/extension pull request #518
Opened 2021-12-06 11:13 UTC by wojciech-turek

Since we want network fees chooser component to be reusable
in different parts of the app, this PR makes the chooser
handle most of the logic internally so it doesn't have to be passed
in every time.

Chooser now tracks its own active index and remembers after being dismissed.

2021-12-06 11:15 UTC, wojciech-turek commented on background/redux-slices/transaction-construction.ts
> +    | {
Forced by prettier, not sure why.

2021-12-06 11:16 UTC, wojciech-turek commented on background/services/chain/utils.ts
> +    type: tx.type,
Not related in the context of this PR description, its for the transaction type being passed correctly.

2021-12-06 15:45 UTC, Shadowfiend commented on background/redux-slices/transaction-construction.ts
> +    | {
We need not understand why, that's the beauty of letting the code formatter worry about formatting :grin:

2021-12-06 16:56 UTC, Shadowfiend requested changes
Big realization that we're doing a lot of unnecessary type fiddling. I think if we remove all of that it'll clean this PR up a bit.

Also a few other notes on the interface for the fees chooser.

2021-12-06 16:56 UTC, Shadowfiend commented on background/redux-slices/transaction-construction.ts
> +      gasData.baseFeePerGas
Actually… These are maybe already always `bigint`??

I think we can drop the `number |` in the `BlockPrices` type and remove all of this type fiddling.

2021-12-06 16:56 UTC, Shadowfiend commented on ui/components/NetworkFees/NetworkFeesChooser.tsx
> +  }, [updateGasOptions])
Why not just update the gas options in line, without any callback/effect intermediaries? It feels like a very cheap operation.

2021-12-06 16:56 UTC, Shadowfiend commented on ui/components/NetworkFees/NetworkFeesChooser.tsx
> +            maxPriorityFeePerGas: regular.maxPriorityFeePerGas,
Why don't we extract this to a function, since we're doing the same thing for each option?

2021-12-06 16:56 UTC, Shadowfiend commented on ui/components/NetworkFees/NetworkFeesChooser.tsx
> +            ),
We should either use a `BigInt` or stick to a string here, tbh.

2021-12-06 16:56 UTC, Shadowfiend commented on ui/pages/Send.tsx
> +            setSelectedGas={setSelectedGas}
Feels like these should be events (`onSave`, `onEstimatedFeePerGasSelected`), maybe?

2021-12-06 16:56 UTC, Shadowfiend commented on ui/pages/Send.tsx
> +            selectedGas={selectedGas}
Let's continue to use the right terminology here, e.g. `selectedEstimatedFeePerGas`.

2021-12-06 16:56 UTC, Shadowfiend commented on ui/components/NetworkFees/NetworkFeesChooser.tsx
> +  estimatedFeesPerGas: {
Maybe we can name the estimated fees type (`type EstimatedFeesPerGas = { baseFeePerGas: bigint, ... }`) in `transaction-construction` and reference it here?

2021-12-06 16:56 UTC, Shadowfiend commented on ui/components/NetworkFees/NetworkFeesChooser.tsx
> +  selectedGas?: GasOption
If we name the `EstimatedFeesPerGas` type, what about using `Omit<"baseFeePerGas", keyof EstimatedFeesPerGas>` here? That is, for the selected option to be `instant`/`express`/`regular` instead of a full object? The caller doesn't know anything about `GasOption`, nor really should they. They should deal in `EstimatedFeesPerGas` and its sub types, IMO.

2021-12-07 09:21 UTC, wojciech-turek commented on background/redux-slices/transaction-construction.ts
> +      gasData.baseFeePerGas
I think they are always `bigint`, true! I will make necessary changes.

2021-12-07 10:50 UTC, wojciech-turek commented on ui/components/NetworkFees/NetworkFeesChooser.tsx
> +  }, [updateGasOptions])
I was thinking it would save us some calculation on re-render since this component is re-rendering a lot due to the moving of fees timeout. If you think the performance won't be affected I am happy to remove it.

2021-12-07 11:41 UTC, wojciech-turek commented on ui/components/NetworkFees/NetworkFeesChooser.tsx
> +            maxPriorityFeePerGas: regular.maxPriorityFeePerGas,
Done, in my next commit you will see the result.

2021-12-07 11:59 UTC, wojciech-turek commented on ui/components/NetworkFees/NetworkFeesChooser.tsx
> +            ),
Modified gwei to be a string, `formatUnits` return value with 2 decimals so I had to slice them off.

2021-12-07 12:18 UTC, wojciech-turek commented on ui/pages/Send.tsx
> +            setSelectedGas={setSelectedGas}
I went with `onSaveGasChoice` as I find it most descriptive, since we're in a chooser :)

2021-12-07 12:28 UTC, wojciech-turek commented on ui/components/NetworkFees/NetworkFeesChooser.tsx
> +  estimatedFeesPerGas: {
Great idea, reduced code length :)

2021-12-07 14:03 UTC, wojciech-turek commented on ui/components/NetworkFees/NetworkFeesChooser.tsx
> +  selectedGas?: GasOption
This made sense, I went ahead and it turned out to be a bigger refactor but I think I've succeeded (at least partially 😅)

2021-12-07 19:34 UTC, Shadowfiend commented on ui/components/NetworkFees/NetworkFeesChooser.tsx
> +  onSaveGasChoice: React.Dispatch<React.SetStateAction<BlockEstimate>>
Let's just make this a `(BlockEstimate)=>void`. The chooser shouldn't care if the caller is setting state or not.

2021-12-07 20:21 UTC, Shadowfiend commented on ui/components/NetworkFees/NetworkFeesChooser.tsx
> +      ).toFixed(),
This is a dangerous thing to do in general, as the parse to `Number` can lose precision. Are you just trying to lose the fractional component here? If so, it may be worth leaning on the fact that ethers always uses a `.` for decimals and just do a `.split(".")[0]` here.

2021-12-07 20:21 UTC, Shadowfiend commented on ui/components/NetworkFees/NetworkFeesChooser.tsx
>        if (!!instant && !!express && !!regular) {
Again, we should be using `typeof === "undefined"` here. Cryptic fiddling like `!!` is the real underlying reason why we avoid type coercion-based checks, tbh.

2021-12-07 20:21 UTC, Shadowfiend commented on ui/components/NetworkFees/NetworkFeesChooser.tsx
> +  }, [updateGasOptions])
Got it. I mean, in general it feels like premature optimization, I really don't care *that* much hehe.

2021-12-07 20:24 UTC, Shadowfiend commented on ui/components/NetworkFees/NetworkFeesChooser.tsx
> +  const getGasOptionFormatted = (option: BlockEstimate) => {
Perhaps even `formatBlockEstimate`? :)

2021-12-07 20:24 UTC, Shadowfiend commented on ui/pages/Send.tsx
> +            setSelectedGas={setSelectedGas}
I would challenge the use of `save` here, as we're not really saving anything. `select` (i.e., `onSelectGasChoice`) feels like the correct choice, and in line with other selection events in other components.

I would also ask why the `NetworkFeesChooser` is selecting a `GasChoice`—we should either be choosing a fee, or it should be a gas chooser :grin:

2021-12-07 20:26 UTC, Shadowfiend commented on ui/components/NetworkFees/NetworkFeesChooser.tsx
> +  selectedGas?: GasOption
There's still some stuff I don't love about passing around the whole `BlockEstimate`, but I see why we're doing it. I'll noodle on it for later, maybe there'll be an interesting refactor down the line.

2021-12-07 20:27 UTC, Shadowfiend approved these changes
I left a few additional notes, but nothing is blocking. Let's 🚢

2021-12-07 20:39 UTC, merged

2021-12-08 15:16 UTC, wojciech-turek commented on ui/pages/Send.tsx
> +            setSelectedGas={setSelectedGas}
That makes sense 🙈  ill do some ranaming

2021-12-08 15:26 UTC, wojciech-turek commented on ui/components/NetworkFees/NetworkFeesChooser.tsx
> +      ).toFixed(),
Thanks, but isn't that even less precise? When using `split` `2.99` will show as `2`? ``Math.round()` is a viable option?

2021-12-08 15:31 UTC, wojciech-turek commented on ui/components/NetworkFees/NetworkFeesChooser.tsx
> +  const getGasOptionFormatted = (option: BlockEstimate) => {
Hahah, yeah, I like it.