Affinity Transforms: Correctly group account types in account switcher
tallycash/extension pull request #528
Opened 2021-12-07 21:29 UTC by Shadowfiend

The design for the switcher is still not aligned with the
latest from @VladUXUI in Figma, but I need to park that for
now and move to the next thing.

Also included in this are a couple of snipes:
- `selectCurrentAccountActivitiesWithTimestamps` returns `undefined`
  if no current account exists, with callers handling this themselves.
  This is more accurate to what can happen in practice.
- The UI slice refers to `currentAccount` instead of `selectedAccount`.
- The account selector dismisses when an address is clicked.

<img width="395" alt="145106493-604527a7-9cea-4c3b-9b84-959e4d4725b6" src="https://user-images.githubusercontent.com/8245/145106693-c9ab5644-83a3-4425-88fb-b5e711397e77.png">

------

Draft until #523 lands.

2021-12-07 23:14 UTC, mhluongo commented
Undrafted this after what I think was sync permission from @Shadowfiend? :sweat_smile:

2021-12-07 23:50 UTC, Shadowfiend commented
Yep!

2021-12-08 01:31 UTC, henryboldi requested changes
I left a couple of questions. My main concern is that we're doing too much heavy lifting in the selectors rather than the reducers. Firstly, relying on the selectors makes composability more difficult, since grabbing the enriched info in a new way needs to dubiously latch on to the existing selector. I suppose pulling the logic out of the selectors into shared utils helps. But why not save the enriched data to the store rather than run it on every update?

2021-12-08 01:31 UTC, henryboldi commented on background/redux-slices/keyrings.ts
> +      // so we ignore an empty list if the keyrings are locked.
What would happen if a user decides to remove their added accounts?

2021-12-08 01:31 UTC, henryboldi commented on background/redux-slices/selectors/accountsSelectors.ts
> +          }
Why does `accountData === "loading"` mean it's read-only in the account switcher category?

2021-12-08 01:31 UTC, henryboldi commented on background/redux-slices/selectors/accountsSelectors.ts
> +        const resolvedAccountType =
Why is this determined in the selector rather than the reducer?

2021-12-08 01:31 UTC, henryboldi commented on ui/components/AccountsNotificationPanel/AccountsNotificationPanelAccounts.tsx
> +      setPendingSelectedAddress("")
Why is `pendingSelectedAddress` needed here?

2021-12-08 03:21 UTC, Shadowfiend commented on background/redux-slices/keyrings.ts
> +      // so we ignore an empty list if the keyrings are locked.
They'd need to unlock the keyrings first.

There's actually no way to remove accounts at the moment, to be clear, only a way to start with a clean slate (i.e., “erase” all accounts)—but the result is the same, the keyrings are unlocked when the event with the empty list goes out.

2021-12-08 03:26 UTC, Shadowfiend commented on background/redux-slices/selectors/accountsSelectors.ts
> +          }
Whoopsies, it absolutely doesn't! This should be running the same logic as `resolvedAccountType` below.

2021-12-08 03:27 UTC, Shadowfiend commented on background/redux-slices/selectors/accountsSelectors.ts
> +        const resolvedAccountType =
Because it has to cross slices to conclude the account type–an account's data is stored in the accounts slice, while its type is (effectively) read from the keyrings slice.

We could hook up keyring-related events to the accounts slice, but it's not immediately clear to me that that is better in any material way.

2021-12-08 03:42 UTC, Shadowfiend commented on ui/components/AccountsNotificationPanel/AccountsNotificationPanelAccounts.tsx
> +      setPendingSelectedAddress("")
We need to clean up state for the cycle so that the user can interact with it again. If the pending address remains set, then if the user tries to bring up the account selector again this effect will run again and `onCurrentAddressChange` will be called again (because `pendingSelectedAddress === selectedAccount` will be `true`). In practice that means the account selector will immediately be dismissed again 🙊

2021-12-08 03:46 UTC, Shadowfiend commented
> relying on the selectors makes composability more difficult, since grabbing the enriched info in a new way needs to dubiously latch on to the existing selector

Hmm… What's dubious about composing selectors instead of reducers?

The tradeoff for me is basically stored size vs runtime computation, but I don't see a significant composability tradeoff. I've been tilting towards runtime computation in my recent PRs because most of the enrichments and other determinations being made are either cacheable (by `createSelector`) or fairly cheap and cross slices, and a smaller store means cheaper serialization costs that we're having to pay in a few places. Charging selectors with inter-slice data coordination is also allowing for better separation of concerns, in particular leading to a bit less duplication of data and data handling (which tend to be opportunities for parts of the store to get out of sync due to bugs elsewhere).

2021-12-08 04:28 UTC, henryboldi commented
Good points, I stand corrected and informed 🙇‍♂️

I'll keep in mind the value of deriving data in the selectors. Reductively, given their efficiency, maybe I should think of selectors as creating a ✨free✨ new version of part of the store? Still, something about chunky selectors strikes me as tricky to deal with. There's an added complexity, in terms of dealing with similar yet different objects, when a foundational(?) selector isn't used consistently.

Anyway, the spacing here feels tight,
<img width="266" alt="spacing" src="https://user-images.githubusercontent.com/1918798/145147564-6682bbb1-bcf5-41db-b3db-28eec443fa4d.png">
Particularly the space between "accounts" and "imported". This doesn't need to be blocking, but it feels funky. We could create a version that doesn't involve perfectly emulating the design, but also doesn't look like a bug. If you'd like, so you can move on to the next thing, I could apply a bit of makeup here in a follow-up PR.

2021-12-08 04:32 UTC, henryboldi approved these changes

2021-12-08 04:32 UTC, merged

2021-12-08 06:04 UTC, henryboldi commented on background/redux-slices/selectors/accountsSelectors.ts
> +export const selectAccountTotalsByCategory = createSelector(
In retrospect, for orthogonality, would it make sense for `selectAccountTotalsByCategory` to be separate from and build on top of `selectAccountTotals`?