Update to sign page to show more data
tallycash/extension pull request #617
Opened 2021-12-14 14:55 UTC by wojciech-turek

We now have more data to fill in on the Sig Transaction page, we can now show the proper amount, destination and value.

This PR also introduces a new feature flag `ENABLE_EDIT_NETWORK_FEE` currently hardcoded to `false` to hide the `FeeSettingButton` since it's not fully ready and configured, instead I've decided to show the estimated fee based on the `maxFeePerGas` coming from the stored transaction request.

The user is now transferred to the activities tab of the currency used.

![ezgif com-gif-maker (6)](https://user-images.githubusercontent.com/61434499/146022023-5c246f1e-c6b1-4f9c-b9ab-5930bc62ef2f.gif)

2021-12-14 18:07 UTC, henryboldi reviewed
I'm not sure what happened, but when I test this branch locally it seems that the activities tab has disappeared completely. Doesn't seem like an issue created here though

2021-12-14 18:09 UTC, henryboldi requested changes

2021-12-14 18:09 UTC, henryboldi commented on ui/components/Shared/SharedPanelSwitcher.tsx
> +        {/* CURRENTlY UNUSED BUT STC */}
Ok, here's where the activities tab disappeared.

2021-12-14 19:17 UTC, Shadowfiend submitted a review, later dismissed
This is working, h/t @henryboldi for the activity list fix.

2021-12-14 19:17 UTC, Shadowfiend commented on ui/components/Shared/SharedPanelSwitcher.tsx
> +        {/* CURRENTlY UNUSED BUT STC */}
Yeah… Let's be careful editing shared components, please :pray:

2021-12-14 19:31 UTC, Shadowfiend commented on background/features/features.ts
> +export const ENABLE_EDIT_NETWORK_FEE = false
We should always add these with the associated env lookup, otherwise this is just another place to look for feature flags :)

2021-12-14 19:31 UTC, Shadowfiend approved these changes
Okay nooowww we're doing it.

2021-12-14 19:31 UTC, merged

2021-12-15 09:13 UTC, wojciech-turek commented on ui/components/Shared/SharedPanelSwitcher.tsx
> +        {/* CURRENTlY UNUSED BUT STC */}
Aww man, all I wanted is to hide advanced tab on the sign page. Thanks for fixing that!

2021-12-15 09:15 UTC, wojciech-turek commented on background/features/features.ts
> +export const ENABLE_EDIT_NETWORK_FEE = false
@Shadowfiend What do you think about keeping everything here? If someone adds an env variable but forgets to add it to the defaults we may experience some bugs, with everything here we should be much safer?