Pull updated ETH balance after transaction
tallycash/extension pull request #752
Opened 2021-12-23 14:58 UTC by wojciech-turek

This PR fixes the ETH balance update once a transaction is completed.

Users should see the new balance within one minute from the transaction confirmation.

2021-12-23 15:15 UTC, mhluongo requested changes
I think you're approaching this in a way that fights the current architecture.

2021-12-23 15:15 UTC, mhluongo commented on background/lib/alchemy.ts
> +export async function getMainNetworkCurrencyBalance(
This isn't Alchemy specific, no need for it to go in here.

2021-12-23 15:15 UTC, mhluongo commented on background/lib/alchemy.ts
> +  return { amount: BigInt(json) }
Missing error handling, etc, etc. Instead of rolling your own, use `ChainService.getLatestBaseAccountBalance(addressNetwork)`.

2021-12-23 15:15 UTC, mhluongo commented on background/services/indexing/index.ts
> +  getMainNetworkCurrencyBalance,
This idea of a "main" network is problematic, and works against us going multi-network.

2021-12-23 15:15 UTC, mhluongo commented on background/services/indexing/index.ts
> +    const mainCurrencyBalance = await getMainNetworkCurrencyBalance(
Instead of doing this periodically, we should only do a balance check once we've sent or received a transaction.

2021-12-23 16:20 UTC, wojciech-turek commented on background/lib/alchemy.ts
> +export async function getMainNetworkCurrencyBalance(
Removed altogether, there is another function already existing we can use for that. Thanks for pointing out :)

2021-12-23 16:22 UTC, wojciech-turek commented on background/services/indexing/index.ts
> +  getMainNetworkCurrencyBalance,
My thinking was its a main currency of a given network but I've probably phrased it poorly.

2021-12-23 16:23 UTC, mhluongo requested changes
So sleek! Couple comments to address but like the direction :)

2021-12-23 16:23 UTC, mhluongo commented on background/services/indexing/index.ts
> +      if ("status" in transaction && (transaction.status === 1 || 0)) {
Pretty sure this conditional is the same as

```
if ("status" in transaction && transaction.status === 1)
```

because of operator precedence... is that what you intended?

2021-12-23 16:23 UTC, mhluongo commented on background/services/indexing/index.ts
> +          address: transaction.from.toLowerCase(),
`lib.utils.normalizeEVMAddress`

2021-12-23 16:23 UTC, mhluongo commented on background/services/indexing/index.ts
> +        this.emitter.emit("accountBalance", balance)
The chain service already does this, no need to emit and save from both service. I think you can replace 273 - 278 with just

```
await this.chainService.getLatestBaseAccountBalance(
    addressNetwork
)
```

2021-12-23 16:23 UTC, mhluongo commented on background/services/indexing/index.ts
> +          address: transaction.from.toLowerCase(),
Maybe? It's not actually clear to me when / whether we normalize, which is a problem.

2021-12-23 16:25 UTC, wojciech-turek commented on background/services/indexing/index.ts
> +    const mainCurrencyBalance = await getMainNetworkCurrencyBalance(
Moved it out to a on("transaction") handler, very good point, I was thinking of ETH as a token initially.

2021-12-23 16:29 UTC, wojciech-turek commented on background/services/indexing/index.ts
> +      if ("status" in transaction && (transaction.status === 1 || 0)) {
Isn't that a case that when transaction fails and has status 0, the user might still incur a fee for gas spent? With that condition reduced to checking only status of `1` it won't run when status is 0 and therefore won't update the amount while it should?

2021-12-23 16:31 UTC, wojciech-turek commented on background/services/indexing/index.ts
> +          address: transaction.from.toLowerCase(),
I am not sure either, I saw `.toLowerCase()` being used in another case and followed the same pattern.

2021-12-23 16:32 UTC, wojciech-turek commented on background/services/indexing/index.ts
> +        this.emitter.emit("accountBalance", balance)
Right, I missed this. Thank you!

2021-12-23 16:36 UTC, mhluongo commented on background/services/indexing/index.ts
> +      if ("status" in transaction && (transaction.status === 1 || 0)) {
Oh I didn't know your intent, I'm just saying that `x === 1 || 0` is that same as `(x === 1) || 0`.

If you want to check if it's either, you need `x == 1 || x === 0`.

2021-12-23 16:36 UTC, mhluongo commented on background/services/indexing/index.ts
> +          address: transaction.from.toLowerCase(),
Not blocking rn

2021-12-23 16:57 UTC, wojciech-turek commented on background/services/indexing/index.ts
> +      if ("status" in transaction && (transaction.status === 1 || 0)) {
Updated, good catch, my brain took a shortcut which wasn't a shortcut 🙈

2021-12-23 16:58 UTC, mhluongo approved these changes
:rocket:

2021-12-23 16:58 UTC, merged

2021-12-23 17:06 UTC, Shadowfiend commented on background/services/indexing/index.ts
> +        (transaction.status === 1 || transaction.status === 0)
Should we have bundled this in with the scheduled refresh were already doing for tokens? Should that periodic check also check the ETH balance?

2021-12-24 11:20 UTC, wojciech-turek commented on background/services/indexing/index.ts
> +        (transaction.status === 1 || transaction.status === 0)
We discussed that with @matt on fd and since it is likely that every tx will have an impact on ETH balance we should refresh it after every transaction failed or successful.

2021-12-27 14:41 UTC, mhluongo commented on background/services/indexing/index.ts
> +        (transaction.status === 1 || transaction.status === 0)
I still think the ERC-20 check makes sense FWIW, just thought it deserved a bit more discussion on approach... especially as we figure out how "smart" we want the wallet to be. Eg if a tx is a known ERC-20 transfer, we can stick with checking 1 contract