Approve token spend page
tallycash/extension pull request #760
Opened 2021-12-27 17:08 UTC by wojciech-turek

When users are approving token spend of an ERC-20 they should see a specific page and be able to change the approval amount.

2021-12-28 15:59 UTC, mhluongo requested changes
The code looks mergeable, but the approval selector isn't coming up for dashboard.keep.network :grimacing:

2021-12-28 15:59 UTC, mhluongo commented on ui/components/SignTransaction/SignTransactionApproveSpendAssetBlock.tsx
> +  const approveAmount = transactionDetails?.input?.substring(74, 138)
I think we should properly parse this with the ABI, ala `EnrichmentService`... but not blocking.

2021-12-28 15:59 UTC, mhluongo commented on ui/pages/SignTransaction.tsx
> +    signType: transactionDetails?.input?.startsWith("0x095ea7b")
Ditto

2021-12-28 16:00 UTC, mhluongo commented
I couldn't test on Uniswap (this wallet already had an approval) so I tried the Keep dashboard. Results below

![Screenshot from 2021-12-28 10-58-20](https://user-images.githubusercontent.com/427505/147584306-e6b068cb-d8f1-4b04-a7e5-4050ec3d0189.png)

2021-12-29 11:08 UTC, wojciech-turek commented on ui/components/SignTransaction/SignTransactionApproveSpendAssetBlock.tsx
> +  const hexedAmount = ethers.utils.hexlify(2)
I will create that in this PR

2021-12-29 11:10 UTC, wojciech-turek commented on ui/components/SignTransaction/SignTransactionApproveSpendAssetBlock.tsx
> +  const approveAmount = transactionDetails?.input?.substring(74, 138)
You are right, I am not 100% how to wire it up at this point though.

2022-01-10 14:20 UTC, mhluongo reviewed
Left a few thoughts, haven't tried the latest code locally though

2022-01-10 14:20 UTC, mhluongo commented on background/lib/utils/index.ts
> +export const verifyIsInfiniteAmount = (amount: string): boolean => {
This name is both too specific and not enough! Perhaps `isInfiniteERC20Amount` or `isMaxUint256`?

2022-01-10 14:20 UTC, mhluongo commented on background/services/indexing/index.ts
> +  getTokenMetadata = async (
I'd recommend

```typescript
async getTokenMetadata(contractAddress: HexString, network: EVMNetwork)
```

and error out if the network isn't what you want, or ignore it and leave a TODO. Multi-network is open in another PR, don't want to keep making this mistake.

2022-01-10 14:20 UTC, mhluongo commented on background/services/indexing/index.ts
> +      (await getTokenMetadata(provider, contractAddress)) || undefined
What if we already have the data in the DB? Shouldn't we check their first?

Either paradigm works, but would be good in docs

2022-01-10 14:20 UTC, mhluongo commented on ui/components/SignTransaction/SignTransactionApproveSpendAssetBlock.tsx
> +        138,
Can we pull this out to a util function? Fine to leave it in the same file (for now), but it's tough to understand tx parsing + rendering intermingled.

2022-01-10 14:20 UTC, mhluongo commented on ui/components/SignTransaction/SignTransactionApproveSpendAssetBlock.tsx
> +            asset?.symbol ?? truncateAddress(transactionDetails.to || "")
Putting on my Antonio hat, I think you want `??`

2022-01-10 14:20 UTC, mhluongo commented on ui/pages/SignTransaction.tsx
> +  const approvalCodes = ["0x095ea7b3", "0xcae9ca51"] // approve, approveAndCall
This should also be a util IMO. It'll make refactoring later simpler.

2022-01-11 03:34 UTC, Shadowfiend requested changes
Just one… Blocker :grimacing:

2022-01-11 03:34 UTC, Shadowfiend commented on ui/components/SignTransaction/SignTransactionApproveSpendAssetBlock.tsx
> +  const approveAmount = transactionDetails?.input?.substring(74, 138)
I'm going to say… It *is* blocking. We should not be doing byte twiddling. Our previous foray, which we let through as not blocking, led to a lot of unexpected issues and some half fixes, including one I did that was completely broken. In general: we have the tools to do this right and should wield them.

I expect the preferred _flow_ here is going to be to pipe through the enrichment service; however, we don't need to solve that full flow here to use the correct parsing strategy. The short version here is we can move [`parseERC20Tx`](https://github.com/tallycash/extension/blob/main/background/services/enrichment/index.ts#L80-L88) to `lib/erc20.ts`, then use it here. That parse will give us an object whose `name` property should be `"approve"` (we should check that) and which should also have a property `args: { spender: string, value: BigNumber }`. The `value` can then be compared against [`ethers.constants.MaxUint256`](https://docs.ethers.io/v5/api/utils/constants/#constants-MaxUint256).

To rewrite the transaction, we can use the `ERC20_INTERFACE` exported by `lib/erc20.ts` to do `ERC20_INTERFACE.encodeFunctionData("approve", { spender: ..., value: updatedValue })`.

2022-01-11 10:55 UTC, wojciech-turek commented on background/services/indexing/index.ts
> +      (await getTokenMetadata(provider, contractAddress)) || undefined
This whole thing is gone with the newest iteration.

2022-01-11 13:13 UTC, wojciech-turek commented on ui/pages/SignTransaction.tsx
> +  const approvalCodes = ["0x095ea7b3", "0xcae9ca51"] // approve, approveAndCall
It doesn't belong there anyway
![Alt Text](https://c.tenor.com/w5A7rgqhs-cAAAAM/ripping-off-paper-trash-bin.gif)

2022-01-11 13:19 UTC, wojciech-turek commented on ui/components/SignTransaction/SignTransactionApproveSpendAssetBlock.tsx
> +        138,
This part was removed and replaced with use of ERC20_INTERFACE, but I know it was ugly :(

2022-01-14 13:59 UTC, mhluongo commented
Testing this on the [Keep dashboard](https://dashboard.keep.network/0x4495c5bf67ba43aa279f41c90083bbbfcf46e643/coverage-pools/deposit) and I'm still not seeing an approval page.

![Screenshot from 2022-01-14 08-58-07](https://user-images.githubusercontent.com/427505/149527136-97007c66-cc8c-404e-ab90-a821ef470b4e.png)

2022-01-14 14:20 UTC, mhluongo commented
Testing on Uniswap and Chrome as the Keep dash appears to use `approveAndCall`. Running into unrelated bugs. @wojciech-turek can you rebase or merge `main`?

2022-01-19 03:17 UTC, Shadowfiend approved these changes
I think we're good to go here, but haven't had a chance to test drive. Once that's done, merge is a go, and the remaining comments here can be handled separately.

2022-01-19 16:34 UTC, Shadowfiend commented
Changed closed to see for #726 as it also covers rendering infinite approvals correctly in the transaction list.

2022-01-19 20:31 UTC, mhluongo commented
![Screenshot from 2022-01-19 15-29-30](https://user-images.githubusercontent.com/427505/150209005-8f7c23c1-732d-4350-a3cf-3723de90c6ae.png)
![Screenshot from 2022-01-19 15-30-08](https://user-images.githubusercontent.com/427505/150209020-2f8523eb-50c7-4886-b017-12e47a6cbadc.png)
![Screenshot from 2022-01-19 15-30-46](https://user-images.githubusercontent.com/427505/150209042-0783a805-baae-435c-97d6-90689f82e0ae.png)

2022-01-19 20:35 UTC, merged