⛽ Patent Cazeline Oil: Fall back to local gas estimates
tallycash/extension pull request #775
Opened 2021-12-29 16:30 UTC by mhluongo

> "Gasoline" is an English word that denotes fuel for automobiles. The term is thought to have been influenced by the trademark "Cazeline" or "Gazeline", named after the surname of British publisher, coffee merchant, and social campaigner John Cassell. On 27 November 1862, Cassell placed an advertisement in The Times of London:
> > The Patent Cazeline Oil, safe, economical, and brilliant … possesses all the requisites which have so long been desired as a means of powerful artificial light.[10]
> 
> This is the earliest occurrence of the word to have been found.

— [Wikipedia](https://en.wikipedia.org/wiki/Gasoline#Etymology)

Fall back on gas estimates based on Alchemy or another provider, both on unsupported chains and in case of a BlockNative failure.

As we aren't multi-network quite yet, the best way to test this is to...
* make sure gas prices are still working with a BlockNative API key
* make sure they work after misspelling the API key

Closes #735

2021-12-29 22:58 UTC, henryboldi commented on background/services/chain/index.ts
> +    await Promise.allSettled(
This no longer immediately fetches the current block prices, which could be a blocking regression

2021-12-29 23:25 UTC, henryboldi requested changes
This no longer immediately fetches the current block prices, which, in my opinion, is a blocking regression. Users would have a decent chance of seeing an empty gas selector screen.

`this.subscribedNetworks` is an empty array when `pollBlockPrices` initially runs, because `subscribeToNewHeads` happens after

2021-12-30 20:47 UTC, mhluongo commented
Easy fix, thanks for digging in @henryboldi. One minute

2021-12-30 20:54 UTC, mhluongo commented
That last commit should have fixed it @henryboldi!

2021-12-30 21:16 UTC, henryboldi approved these changes
Awesome! Works as expected 😁

<br/>

Anyway, should `runAtStart` be `false` here now? (line 151)
```
 blockPrices: {
        runAtStart: true,
        schedule: {
          periodInMinutes:
            Number(process.env.BLOCKNATIVE_POLLING_FREQUENCY ?? "120") / 60,
        },
   ...
 ```

2021-12-30 21:58 UTC, henryboldi approved these changes
Excellent!

2021-12-30 21:58 UTC, merged