🆙 Have version bump script also update bug template
tallycash/extension pull request #783
Opened 2021-12-30 23:27 UTC by henryboldi

2022-01-04 14:22 UTC, greg-nagy requested changes
For me the yq command does not add the new version but duplicates the block and adds the version to the 2nd block. 

Also the `preversion` script creates a new file name 1 with the path for `yq`.
Not sure why, but the script is working though, just creates a new file. 

Now that you are in this PR anyway, can you please add brave browser to the list? :) 🙏

![CleanShot 2022-01-04 at 15 06 39](https://user-images.githubusercontent.com/7690112/148071353-7a94febb-291c-44e7-85f9-93528e4c9038.png)

2022-01-05 03:36 UTC, Shadowfiend commented on scripts/update-version.sh
> +yq e -i '.body[] |= select(has("id")) |= select(.id == "version").attributes.option = ["Community Edition v'$npm_package_version'"] + select(.id == "version").attributes.options' .github/ISSUE_TEMPLA
```suggestion
yq e -i '.body[] |= select(has("id")) |= select(.id == "version").attributes.options = ["Community Edition v'$npm_package_version'"] + select(.id == "version").attributes.options' .github/ISSUE_TEMPLATE/BUG.yml
```

2022-01-05 03:45 UTC, henryboldi commented on scripts/update-version.sh
> +yq e -i '.body[] |= select(has("id")) |= select(.id == "version").attributes.option = ["Community Edition v'$npm_package_version'"] + select(.id == "version").attributes.options' .github/ISSUE_TEMPLA
Oh my lord. Thank you sir

2022-01-05 14:52 UTC, Shadowfiend commented
Letting @greg-nagy wrap this one up.

2022-01-06 20:09 UTC, greg-nagy approved these changes
it wooooorkkss ..... yeeeey :D

2022-01-06 20:09 UTC, merged