Remove OnboardingDerivationPathSelect component from pages folder
tallycash/extension pull request #788
Opened 2022-01-03 12:40 UTC by 7alip

1. I removed `OnboardingDerivationPathSelect` component which should not be in pages dir.
2. It dispatches `importLegacyKeyring` action twice.
https://github.com/tallycash/extension/blob/7f0b7cae6245ac95599a4eac7490de729936fbe8/ui/pages/Onboarding/OnboardingImportMetamask.tsx#L97-L98

2022-01-03 16:41 UTC, henryboldi requested changes
Thoughts on moving `ui/pages/Onboarding/OnboardingDerivationPathSelect.tsx` to `ui/components/Onboarding/OnboardingDerivationPathSelect.tsx`? That's where I'd put it. And I'd love to keep the separate component!

2022-01-03 16:44 UTC, henryboldi commented on ui/pages/Onboarding/OnboardingImportMetamask.tsx
> -      dispatch(importLegacyKeyring({ mnemonic: recoveryPhrase.trim(), path }))
Oh jeez. Looks like resolving merge conflicts went wrong at some point. Thank you for splitting this!

2022-01-06 16:06 UTC, henryboldi approved these changes
Looks good! 😁

2022-01-06 16:25 UTC, Shadowfiend commented
Force-merging here since the build error is build configuration-related (see #793).

Ran `yarn build` manually to confirm:

<details>
<pre>
yarn run v1.22.10
$ webpack --mode=production
 
              ui.js ⏤  902 kB (+48.7 kB)
      background.js ⏤  596 kB (+3.13 kB)
   background-ui.js ⏤  66 B
          fonts.css ⏤  235 B (+14 B)
          index.css ⏤  865 B (+6 B)
         popup.html ⏤  184 B
 window-provider.js ⏤  4.97 kB (+332 B)
 provider-bridge.js ⏤  5.98 kB (+105 B)


              ui.js ⏤  902 kB (+48.7 kB)
      background.js ⏤  596 kB (+3.13 kB)
   background-ui.js ⏤  66 B
          fonts.css ⏤  235 B (+14 B)
          index.css ⏤  865 B (+6 B)
         popup.html ⏤  184 B
 window-provider.js ⏤  4.97 kB (+332 B)
 provider-bridge.js ⏤  5.98 kB (+105 B)


              ui.js ⏤  902 kB (+48.7 kB)
      background.js ⏤  596 kB (+3.13 kB)
   background-ui.js ⏤  66 B
          fonts.css ⏤  235 B (+14 B)
          index.css ⏤  865 B (+6 B)
         popup.html ⏤  184 B
 window-provider.js ⏤  4.97 kB (+332 B)
 provider-bridge.js ⏤  5.98 kB (+105 B)


              ui.js ⏤  695 kB (-207 kB)
      background.js ⏤  443 kB (-154 kB)
   background-ui.js ⏤  0 B (-66 B)
 window-provider.js ⏤  3.42 kB (-1.55 kB)
 provider-bridge.js ⏤  3.63 kB (-2.34 kB)
          fonts.css ⏤  235 B
          index.css ⏤  865 B
         popup.html ⏤  184 B

✨  Done in 34.93s.
</pre>
</details>

2022-01-06 16:27 UTC, merged