📝 Create a recovery phrase in Tally onboarding
tallycash/extension pull request #801
Opened 2022-01-05 16:19 UTC by henryboldi

2022-01-06 21:35 UTC, greg-nagy requested changes
I love, that you edited the keyring service in such a bald way! :) 

- I alway ran into the incorrect order, which I believe is a bug and can be related to the getKeyrings() method still using 256 mnemonics
- It was strange that on verify step the entered seeds are running out of the window and I could not verify what I have entered 
- the async onClick felt really weird. Can we avoid doing that somehow? 

Overall I am loving this PR :) 
I never really understood why we postponed this for so long.

2022-01-06 21:35 UTC, greg-nagy commented on background/redux-slices/keyrings.ts
> +      .addCase(importKeyring.pending, (state) => {
I have ran into situations where this method proved to be unreliable. 
But that was around dApp permission request so it was probably the result of a window closing.

The solution was to dispatch sync actions from the async thunk. Not sure if it applies here, but good thing to have in mind.

2022-01-06 21:35 UTC, greg-nagy commented on background/services/keyring/index.ts
> +    if (type !== KeyringTypes.mnemonicBIP39S128) {
Poor Johnny got a memory downgrade ... :D

> The Johnny Mnemonic character is a data trafficker who has undergone cybernetic surgery to have a data storage system implanted in his head.

https://williamgibson.fandom.com/wiki/Johnny_Mnemonic

2022-01-06 21:35 UTC, greg-nagy commented on background/services/keyring/index.ts
> +    const newKeyring = new HDKeyring({ strength: 128 })
I am loving that you are deleting/modifying background services :)

2022-01-06 21:35 UTC, greg-nagy commented on background/services/keyring/index.ts
> +    const newKeyring = new HDKeyring({ strength: 128 })
`getKeyrings()` returns `mnemonicBIP39S256`. Not sure if it's an issue, but the method is used in `emitKeyrings` and the `keyrings` method is propagated to the store.

2022-01-06 21:35 UTC, greg-nagy commented on background/services/keyring/index.ts
> +    const newKeyring = new HDKeyring({ strength: 128 })
Might be a good time to increase our leverage for stability opportunities ...  eg. write test for it :)

2022-01-06 21:35 UTC, greg-nagy commented on ui/components/Shared/SharedButton.tsx
> +    await onClick?.(e)
Why did you need this here? To wait for the dispatches In SuccessMessage? 
This worries me, if it's really the direction we need?

2022-01-06 21:35 UTC, greg-nagy commented on ui/pages/Onboarding/OnboardingVerifySeed.tsx
> +        <KeepInView />
Did you intentionally shift out of the screen the first part of the entered seed phrase while there is a lot of space underneth? 

I wanted to check back if I entered my mnemonics in the correct order, but could not do it. I think I would prefer if I could.

2022-01-06 21:37 UTC, henryboldi commented on ui/pages/Onboarding/OnboardingVerifySeed.tsx
> +        <KeepInView />
You can scroll up, no?

2022-01-06 21:38 UTC, henryboldi commented on ui/components/Shared/SharedButton.tsx
> +    await onClick?.(e)
Yes, to wait for the dispatches in `SuccessMessage `. What worries you about this? Do you have a different solution in mind?

2022-01-06 21:39 UTC, henryboldi commented on background/redux-slices/keyrings.ts
> +      .addCase(importKeyring.fulfilled, (state) => {
Ah good point! Thank you

2022-01-06 21:40 UTC, mhluongo commented on background/main.ts
> +      await this.keyringService.importKeyring(mnemonic, path)
The original intent was to only import 12-word phrases, and always generate 24-word for new recovery phrases.

2022-01-06 21:42 UTC, henryboldi commented on background/main.ts
> +      await this.keyringService.importKeyring(mnemonic, path)
The original intention behind creating `importLegacyKeyring` was to import MetaMask "legacy" 12 word keys. But given #723 I don't think that's the case anymore.

cc @Shadowfiend

2022-01-06 21:43 UTC, greg-nagy commented on ui/pages/Onboarding/OnboardingVerifySeed.tsx
> +        <KeepInView />
I can — now that you told me that I can. I don't have a scrollbar and there is a lot of space under the confirm button. 
It even occured to me to scroll, but I guess I did not hit the area so I could not, when tried.

2022-01-06 21:49 UTC, greg-nagy commented on ui/components/Shared/SharedButton.tsx
> +    await onClick?.(e)
If you move the cleanup logic into the fullfilled reducer then you don't need 2 dispatches and I think you can skip the await part. 

For me using promises in a click handler felt strange. And also it's kind of a big change in a widely used component only for a single use case.

Generally async logic should live in async thunks or the main.ts in my view. Patching things together in the view feels out of place.

2022-01-06 21:54 UTC, henryboldi commented on ui/components/Shared/SharedButton.tsx
> +    await onClick?.(e)
Makes sense! Thank you. I'll update this

2022-01-06 21:55 UTC, greg-nagy commented on background/main.ts
> +      await this.keyringService.importKeyring(mnemonic, path)
So this 12-word phrase is not legacy after all? Ot this event/method will be responsible for importing all the keyrings? 

Removing the `Legacy` part signaled to me an increase in responsibility which might not have been the original idea. 
So I thought it worth a question.

2022-01-06 21:57 UTC, henryboldi commented on background/services/keyring/index.ts
> +    const newKeyring = new HDKeyring({ strength: 128 })
It returns `mnemonicBIP39S256` in the `type` attribute? If we've been importing legacy keyrings then this type has been mostly wrong all along, no?

2022-01-07 19:39 UTC, greg-nagy commented on ui/pages/Onboarding/OnboardingAddWallet.tsx
> +  useAreKeyringsUnlocked(!HIDE_CREATE_PHRASE && true)
The `&& true` does not seem to be necessary here.

2022-01-07 19:40 UTC, greg-nagy approved these changes
it worked for me this time and I don't see any blocking issue, so let's do this 🎸

2022-01-07 19:49 UTC, merged

2022-01-07 19:51 UTC, Shadowfiend commented on background/main.ts
> +      await this.keyringService.importKeyring(mnemonic, path)
> The original intention behind creating importLegacyKeyring was to import MetaMask "legacy" 12 word keys. But given #723 I don't think that's the case anymore.

I don't think that's true, fwiw. 723 didn't change anything about the kind of key we're importing, just what we're deriving from it.

> Removing the Legacy part signaled to me an increase in responsibility which might not have been the original idea.

I think this is probably still true. The underlying question is whether we want the same method to import “legacy“ keys and our own keys. Mostly the argument here is a validation one: if we use different methods for the two, validating different reqs is straightforward (e.g., 24 vs 12 words). We _should_ validate those requirements in the keyring service _in addition to_ any UI validation we do—this is the standard principle of having the UI do user-facing validation, and letting the sensitive systems in the backend be locally responsible for data-shape validation.

From that perspective, if we move generated keyrings to 24-word, we should make sure that we can declare intent (e.g. by passing a keyring type alongside the mnemonic), so that we can validate that the given mnemonic and desired keyring type agree.