Nonces and queues: More direct nonce management and multi-transaction enqueuing
tallycash/extension pull request #822
Opened 2022-01-12 03:50 UTC by Shadowfiend

Transaction request queuing isn't quite done yet. Nonce management should be
roughly there. This PR won't include the UI work to track multiple pending
transactions; however, it will include the UI work to keep the sign page up
until all pending transactions have been signed.

2022-01-12 14:50 UTC, mhluongo requested changes
Concept ACK, open implementation question

2022-01-12 14:50 UTC, mhluongo commented on background/services/chain/index.ts
> +              transaction.from.toLowerCase()
`normalizeEVMAddress` plz and ty :)

2022-01-12 14:50 UTC, mhluongo commented on background/services/chain/index.ts
> +            typeof addressNetwork.network.chainID !== "undefined" &&
This is difficult to parse and something we need elsewhere. Can we use the typeguard from the multi-network PR or another broken out here?

2022-01-12 14:50 UTC, mhluongo commented on background/services/chain/index.ts
> +    this.evmChainNoncesByAddress[network.chainID] ??= {}
It'd be nice to know if these are the nonces that we've seen, the nonces that have been confirmed, or...? Feels like a better var name is in order

2022-01-12 14:50 UTC, mhluongo commented on background/services/chain/index.ts
> +  private evmChainNoncesByAddress: {
Ser please my family needs docs

2022-01-13 20:01 UTC, Shadowfiend commented on background/services/chain/index.ts
> +  private evmChainNoncesByAddress: {
Doesn't everything :)

2022-01-13 20:02 UTC, Shadowfiend commented on background/services/chain/index.ts
> +            typeof addressNetwork.network.chainID !== "undefined" &&
(Note that this filter is _more type-safe than a type guard_. Type guards are assumed to be internally correct, this is verified by the compiler to filter the type union as needed.)

2022-01-13 20:11 UTC, mhluongo commented on background/services/chain/index.ts
> +            typeof addressNetwork.network.chainID !== "undefined" &&
I just meant: is there not a better way to do this that we can reuse? But it's not blocking at all

2022-01-13 22:27 UTC, Shadowfiend commented on background/services/chain/index.ts
> +            typeof addressNetwork.network.chainID !== "undefined" &&
Unfortunately the type guard is the way that's reusable, but it's also less type-safe. Probably the right long-term solution though.

2022-01-14 02:24 UTC, Shadowfiend commented on background/services/chain/index.ts
> +  private evmChainNoncesByAddress: {
Light docs + FIXME added.

2022-01-14 02:24 UTC, Shadowfiend commented on background/services/chain/index.ts
> +    this.evmChainNoncesByAddress[network.chainID] ??= {}
Tried to clarify this.

2022-01-14 02:25 UTC, Shadowfiend commented on background/services/chain/index.ts
> +              transaction.from.toLowerCase()
Donezo.

2022-01-14 03:55 UTC, Shadowfiend commented
Need to refine this on top of the base swap branch, but the changes will remain more or less as-is. Tackling the lifecycle stuff tomorrow.

2022-01-20 03:35 UTC, Shadowfiend commented
Need to do a little commit juicing, but this is the expected final state here.

2022-01-20 19:57 UTC, Shadowfiend commented
Flipping this to ready for review.

2022-01-20 20:10 UTC, Shadowfiend commented
Lol CI disagreed 😢

2022-01-20 21:45 UTC, mhluongo approved these changes
Appears to work well locally. I ran into an issue with broadcasting an ETH payment to my own wallet, but it's a separate bug.

2022-01-20 21:45 UTC, mhluongo commented on background/main.ts
> +          this.chainService.releaseEVMTransactionNonce(transactionWithNonce)
Woo we've got locks

2022-01-20 21:45 UTC, mhluongo commented on background/services/chain/index.ts
> +  private evmChainLastSeenNoncesByNormalizedAddress: {
:pray: thank you for making this multi-network :heart:

2022-01-20 21:45 UTC, mhluongo commented on background/services/chain/index.ts
> +   * the known on-chain nonce state of the service, attempting to ensure that
Might be good to call out more specifically that this ignores the mempool?

2022-01-20 21:45 UTC, mhluongo commented on background/services/chain/index.ts
> +   * pending nonces in the mempool.
Ah. This contradicts the "on-chain" bit earlier.

2022-01-20 21:45 UTC, mhluongo commented on background/services/chain/index.ts
> +    ] ??=
so fancy

2022-01-20 21:45 UTC, mhluongo commented on background/services/chain/index.ts
> +    // TODO relatively rare edge case, but we should handle it at some point.
Way less rare when hardware wallet support goes live I'd bet.

2022-01-20 21:45 UTC, mhluongo commented on background/services/chain/index.ts
> +    // TODO relatively rare edge case, but we should handle it at some point.
Thinking about it, I'm most concerned about edge cases where the extension is closed to switch wallets or leave, etc. Any concerns around the lask of persistence here?

2022-01-20 21:53 UTC, mhluongo commented
Opened a new bug for a nonce-related issue I ran into here... but IMO it's out of the scope of this PR.

https://github.com/tallycash/extension/issues/858

2022-01-20 21:55 UTC, merged

2022-01-20 22:01 UTC, Shadowfiend commented on background/services/chain/index.ts
> +   * the known on-chain nonce state of the service, attempting to ensure that
It doesn't! We update the seen nonces in the `filteredNewFullPendingTransactionsSubscriptionID` event watcher, so pending transactions external to the wallet also update this state.

There's an interesting question here on whether that should be the only way to increment the nonce (with releasing being the only way to decrease it).

2022-01-20 22:05 UTC, mhluongo commented on background/services/chain/index.ts
> +   * the known on-chain nonce state of the service, attempting to ensure that
> the known on-chain nonce state of the service

My bone to pick then :D

2022-01-20 22:11 UTC, Shadowfiend commented on background/services/chain/index.ts
> +    // TODO relatively rare edge case, but we should handle it at some point.
Curious what you mean re: hardware wallet support here.

Currently the only time we actively allocate a nonce is right before internal signing occurs (i.e., after the user has hit the approve button). For the keyring this means the nonce is immediately consumed, though broadcast may be delayed if it's for a dApp using `eth_signTransaction`. For hardware wallets we should probably time the nonce out and throw an exception, releasing the nonce at that point.

Obviously this still leaves edge cases, and there's a question of e.g. what we should do if we're currently signing a nonce and receive a pending transaction with the same nonce, but that seems even less likely with hardware signing since generating a nonce conflict would requires a synchronous action from the same hardware wallet in a different place.

Ultimately we'll need to handle, in the UI, errors like `replacement transaction underpriced` and `nonce too low`, either by displaying the relevant state or by prompting the user to re-sign or both. Lot of complexity behind that one.