Added LedgerService skeleton
tallycash/extension pull request #844
Opened 2022-01-18 18:07 UTC by fernya

First PR draft, don't expect ground-breaking stuff right now!

2022-01-19 20:28 UTC, Shadowfiend commented on background/services/ledger/index.ts
> +    [] // we don't know our final dependencies
Fwiw—this is more likely to be a dependee than a dependent. Keyring service is a decent, though probably incomplete, guide for the API here.

2022-01-20 12:25 UTC, greg-nagy commented on package.json
> +    "@types/w3c-web-usb": "^1.0.5",
This should be in the background package.json I think.

2022-01-20 12:26 UTC, greg-nagy requested changes

2022-01-20 12:26 UTC, greg-nagy commented on package.json
> +    "@types/w3c-web-usb": "^1.0.5",
This should be in the background package.json I think.

2022-01-20 12:31 UTC, fernya commented on background/services/ledger/index.ts
> +          Object.keys(SupportedLedgerPids).includes(
Early return?

2022-01-21 12:14 UTC, mhluongo commented on background/services/ledger/index.ts
> +const idGeneratorPath = "44'/60'/0'/0/0"
We should probably call this derivation path to be consistent internally and w other wallets

2022-01-21 12:16 UTC, mhluongo commented on background/services/ledger/index.ts
> +  const address = await deriveAddressOnLedger(idGeneratorPath, eth)
Ahh I see. No way to ID a device but by it's address derivation?

2022-01-26 13:27 UTC, fernya commented on background/services/ledger/index.ts
> +const idGeneratorPath = "44'/60'/0'/0/0"
Then it'll be idDerivationPath to distinguish it from other derivation paths.

2022-01-26 13:29 UTC, fernya commented on background/services/ledger/index.ts
> +  const address = await deriveAddressOnLedger(idGeneratorPath, eth)
From the depths of the internet it seems so, there are people who inject custom uuid to the devices but that should be a big privacy no-no!

> Yes i got to know about this from ledger support team, there are certain security measures due to which unique identifier are not attached to these devices. however i needed unique identifier for some specific reasons in the project, so i stored uuid in the device via APDU commands and mapped the devices against that uuid. It is working fine for me as of now.

2022-01-26 13:59 UTC, mhluongo commented on background/services/ledger/index.ts
> +  const address = await deriveAddressOnLedger(idGeneratorPath, eth)
I certainly don't want to make fingerprinting easier for anyone else, just for consenting users. I assume that APDU approach is per device rather than per device / application? If the latter, the privacy concern might not be so bad. If the former... :grimacing: 

At the end of the day we only need a device that can sign for a particular account, but if we can tell people they're using the wrong device... or that the device has bee tampered with?... earlier in the process *without* chipping it so anyone who connects knows the user used Tally, this could be a big UX win.

2022-01-27 08:13 UTC, greg-nagy reviewed
There are bits and pieces which will require some polish, but overall looks decent so far.

2022-01-27 08:13 UTC, greg-nagy commented on background/services/ledger/index.ts
> +  const devs = await navigator.usb.getDevices()
I also like short variable names, but let's use readable names, please :)

2022-01-27 08:13 UTC, greg-nagy commented on background/services/ledger/index.ts
> +  const a = await eth.getAddress(path)
old habbits die hard :)

2022-01-27 08:22 UTC, greg-nagy commented on background/services/ledger/index.ts
> +  const address = await deriveAddressOnLedger(idGeneratorPath, eth)
> At the end of the day we only need a device that can sign for a particular account, but if we can tell people they're using the wrong device

We will be able to do this using the first address as an id.

2022-01-27 16:20 UTC, fernya commented on package.json
> +    "@types/w3c-web-usb": "^1.0.5",
Done.

2022-01-27 16:21 UTC, fernya commented on background/services/ledger/index.ts
> +  const devs = await navigator.usb.getDevices()
Alrighty!

2022-01-27 16:23 UTC, fernya commented
Shall I make it non-draft or wait for Massimo's branch to get merged?

2022-01-28 23:19 UTC, mhluongo commented
> Shall I make it non-draft or wait for Massimo's branch to get merged?

If it's ready to review for merge into `main`, undraft away! The only extra caveat is that we keep `main` releasable, but AFAIK this won't impact a user until there's a frontend?

2022-02-01 10:44 UTC, greg-nagy requested changes
Partial pass on the PR, but want to save state.

2022-02-01 10:44 UTC, greg-nagy commented on background/redux-slices/ledger.ts
> +async function doConnectReal() {
You don't need this function. You can emmit in the async thunk
See [setNewSelectedAccount](https://github.com/tallycash/extension/blob/8fb4db8ed7836ae082dd4a80b6b53eac80f55330/background/redux-slices/ui.ts#L105) and `newSelectedAccount`

`emit()` will return a promise and you can wait for that. 

See the [wiring in main.ts](https://github.com/tallycash/extension/blob/d070f46b7bf109e08a75d057954169537b2196a4/background/main.ts#L842)

2022-02-01 10:44 UTC, greg-nagy commented on background/redux-slices/ledger.ts
>  async function doFetchAddressReal(path: string) {
Same goes here as for the `doConnectReal()`

2022-02-01 10:44 UTC, greg-nagy commented on background/redux-slices/ledger.ts
> +    const deviceID = await doConnectReal()
emit comes here

2022-02-01 10:44 UTC, greg-nagy commented on background/redux-slices/ledger.ts
> +    const address = await doFetchAddressReal(path)
emit comes here

2022-02-01 10:44 UTC, greg-nagy commented on background/services/ledger/db.ts
> +    super("tally/ledgers")
I would use `tally/ledger` or `tally/ledger-service` as a name.

2022-02-01 10:44 UTC, greg-nagy commented on background/services/ledger/index.ts
> +const LedgerTypeStr = Object.values(LedgerType)
It's better not to use abbrevations

2022-02-01 10:44 UTC, greg-nagy commented on background/services/ledger/index.ts
> +  let v: string | number = signature.v - 27
This is some hardcore numerology :) 

Is it possible to do this in a way that is easier to understand? Or if not, then please add some comments here

2022-02-01 10:44 UTC, greg-nagy commented on background/services/ledger/index.ts
> +      return new this(await getOrCreateDB(), undefined)
You can remove the undefined from here and the constructor parameter list. 

The transport can a normal class property.

2022-02-01 10:44 UTC, greg-nagy commented on background/services/ledger/index.ts
> +const admittedProductIds = [0x1015, 0x4015]
What are these? I assume they are the ids for ledger nano s and nano x. If so please use a data structure that is easier to follow.

2022-02-01 12:43 UTC, fernya commented on background/services/ledger/index.ts
> +  const a = await eth.getAddress(path)
Already fixed :)

2022-02-01 13:16 UTC, fernya commented on background/services/ledger/index.ts
> +const LedgerTypeStr = Object.values(LedgerType)
Fixed.

2022-02-01 13:22 UTC, greg-nagy requested changes
Good amount of feedback, but want to say that this is a huge lift!

This is good work, but has the initial ramp up patterns.

2022-02-01 13:22 UTC, greg-nagy commented on background/services/ledger/index.ts
> +    this.emitter.emit("connected", { id: this.#currentLedgerId, type })
I think "saving seen ledgers and storing them" responsibility is missing from this function.

Or do you want to put that into the `SigningService`?

2022-02-01 13:22 UTC, greg-nagy commented on background/services/ledger/index.ts
> +    requireAvailableLedger()
This should also use the attached device and the created transport

2022-02-01 13:22 UTC, greg-nagy commented on background/services/ledger/index.ts
> +        ethersTransactionRequestFromEIP1559TransactionRequest(
What a gorgeous and easy to remember name ... :)

But this is why we have IntelliSense ...

2022-02-01 13:22 UTC, greg-nagy commented on background/services/ledger/db.ts
> +      (await this.accounts.where("address").equals(address).first()) ?? null
Based on how this is used this should be just 

`return this.accounts.where("address").equals(address).first()`

It's generally a nice idea to use `null` to say explicitly `we haven't found anything` but only if it's used consistently as a common understanding through the codebase. Generally we use the dexie api in other parts of the codebase so that should be fine here too.

2022-02-01 13:22 UTC, greg-nagy commented on background/services/ledger/index.ts
> +      const alteredSig = {
Why do we need this?

2022-02-01 13:22 UTC, greg-nagy commented on background/services/ledger/index.ts
> +    requireAvailableLedger()
Use the currently attached device, please.

2022-02-01 13:22 UTC, greg-nagy commented on background/services/ledger/index.ts
> +    requireAvailableLedger()
Use the currently attached device, please.

2022-02-01 13:22 UTC, greg-nagy commented on background/services/ledger/index.ts
> +}
I believe we will need a couple more signing methods, but not sure tbh. 

In the UI we have these:
```
  Sign = "sign",
  SignSwap = "sign-swap",
  SignSpend = "sign-spend",
  SignTransfer = "sign-transfer",
```

Not sure how these maps to ledger interactions though.

2022-02-01 13:22 UTC, greg-nagy commented on background/services/signing/index.ts
> +    this.deriveAddress = this.deriveAddress.bind(this)
I think you won't need these binds. But this seems to be placeholder code anyway.

2022-02-01 14:12 UTC, greg-nagy requested changes
Put the draft service initialization logic behind a feature flag please.

2022-02-01 14:12 UTC, greg-nagy commented on background/main.ts
> +      this.ledgerService.startService(),
Please put the initialization of these services and all their usage in the `main.ts` behind the `HIDE_IMPORT_LEDGER` feature flag from the environment variables. 

* service create
* Main class 
  * create dependency list
  * constructor
* internal start
* internal stop 
* initializeRedux

This is uncharted territory, so if you run into any roadblocks please let me know.

2022-02-01 14:22 UTC, fernya commented on background/services/ledger/index.ts
> +      return new this(await getOrCreateDB(), undefined)
Done.

2022-02-01 14:31 UTC, fernya commented on background/services/ledger/index.ts
> +const admittedProductIds = [0x1015, 0x4015]
Restructured the whole thing into a more descriptive data structure (LedgerProductDatabase) and a tester function (TestedProductId) to decide the same thing.

2022-02-01 14:34 UTC, cairomassimo commented on background/main.ts
> +      for (let i = 0; i < accounts.length; i += 1) {
> You could use `for (const {path, address} of accounts) { ...`

I wanted to at some point, but TSC complains about missing `--downlevelIteration` option. Should we set it? I'm not 100% sure about its implications though...

2022-02-01 14:36 UTC, cairomassimo commented on background/redux-slices/ledger.ts
> +async function doConnectReal() {
Agree. And it can be made even simpler once/if #911 is merged ;)

2022-02-01 14:38 UTC, cairomassimo commented on background/redux-slices/ledger.ts
>  async function doFetchAddressReal(path: string) {
I don't think we can do it here, though. We need a result (the address) and `emit()` returns `Promise<void>`. (I assume. How could it know from _which_ listener to get the result? What if there are none? What determines the return type?) Definitely simpler via #911

2022-02-01 14:46 UTC, fernya commented on background/services/ledger/db.ts
> +    super("tally/ledgers")
Done.

2022-02-01 14:48 UTC, greg-nagy commented on background/main.ts
> +      for (let i = 0; i < accounts.length; i += 1) {
I think we should not need to set `--downlevelIteration` https://www.typescriptlang.org/tsconfig#downlevelIteration, because our target is esnext and that plays a role only when compiling to ES5.

I get some really weird eslint error when I try to use it `iterators/generators require regenerator-runtime, which is too heavyweight for this guide to allow them. Separately, loops should be avoided in favor of array iterations.eslintno-restricted-syntax`

Have no idea what's the cause of this. I assume some eslint inherited rules. Tbh I would not touch it as the eslint rules are shared through thesis. Does not really worth the effort.

2022-02-01 15:04 UTC, fernya commented on background/redux-slices/ledger.ts
> +async function doConnectReal() {
Tbh I can't tell the difference between this and the one made on Line 151. We need the return value at both stuff (ledgerId and address respectively).

2022-02-01 15:04 UTC, fernya commented on background/redux-slices/ledger.ts
>  async function doFetchAddressReal(path: string) {
Tbh I can't tell the difference between this and the one made on Line 145. We need the return value at both stuff (ledgerId and address respectively).

2022-02-01 15:12 UTC, fernya commented on background/services/signing/index.ts
> +    this.deriveAddress = this.deriveAddress.bind(this)
Yes, this is needed only for successfully commit the placeholders. Otherwise linter complains that the member never use 'this'.

2022-02-01 15:20 UTC, fernya commented on background/main.ts
> +      this.ledgerService.startService(),
Done.

2022-02-01 16:32 UTC, fernya commented on background/redux-slices/ledger.ts
> +async function doConnectReal() {
I'll skip this in this round.

2022-02-01 16:32 UTC, fernya commented on background/redux-slices/ledger.ts
>  async function doFetchAddressReal(path: string) {
I'll skip this in this round.

2022-02-01 16:45 UTC, fernya commented on background/redux-slices/ledger.ts
> +    const deviceID = await doConnectReal()
I'll skip this right now.

2022-02-01 16:45 UTC, fernya commented on background/redux-slices/ledger.ts
> +    const address = await doFetchAddressReal(path)
I'll skip this right now.

2022-02-01 16:51 UTC, fernya commented on background/main.ts
> +     * A promise TODO
Done :)

2022-02-02 09:22 UTC, fernya commented on background/services/ledger/index.ts
> +    this.onConnection(event.device.productId)
We may get the productId of the connected devices from two different places.
1) navigator.usb "connect" event -> when the device was already onboarded and connected to the computer - it comes from the event descriptor
2) prepopulated list of paired devices -> when the device is newly onboarded - it comes the first paired device received from navigator.usb.getDevices()

It seems logical to me to create a wrapped function to the one that takes the productId as number and does the heavy-lifting, and wrap it with functions which extract the productId from the appropriate place.

2022-02-02 09:22 UTC, fernya commented on background/services/ledger/index.ts
> +    navigator.usb.addEventListener("connect", this.#onUSBConnect)
:)

2022-02-02 09:37 UTC, fernya commented on background/services/ledger/index.ts
> +    requireAvailableLedger()
A'ight, changed logic in all relevant places!

2022-02-02 09:38 UTC, cairomassimo reviewed
Some minor comments :)

2022-02-02 09:38 UTC, cairomassimo commented on background/services/ledger/db.ts
> +  ledgerId: string
The `ID` part is usually all-caps in the rest of the codebase, so I think we should be consistent here.

Also, I used the name `deviceID` for this, which I think is a bit clearer.

2022-02-02 09:38 UTC, cairomassimo commented on background/services/signing/index.ts
> + */
Stale comment.

2022-02-02 09:38 UTC, cairomassimo commented on background/services/signing/index.ts
> +  async deriveAddress(accountID: string): Promise<HexString> {
I don't understand the purpose of this method. I assume it was in the RFC, but I'd rather not add it until it's implemented (even better if we don't add it until it's actually used for something).

It's not clear to me the meaning of `accountID` (e.g., for ledgers, an account is created from a pair `deviceID,derivationPath`)

2022-02-02 09:38 UTC, cairomassimo commented on background/services/signing/index.ts
> +}
Is there an implementation of this?
It's ok for me if it's coming in a different PR, but even better if we do it here

2022-02-02 09:40 UTC, fernya commented on background/services/ledger/index.ts
> +}
I think these could be mapped to these three in LedgerService.

2022-02-02 10:04 UTC, fernya commented on background/services/ledger/index.ts
> +    this.emitter.emit("connected", { id: this.#currentLedgerId, type })
Saving seen ledgers (LedgerService::saveAddress) is triggered by the UI and done in background/main.ts when importLedgerAccounts event is handled.

The distinction is not made here I'll add it.

2022-02-02 10:14 UTC, fernya commented on background/services/ledger/index.ts
> +      const alteredSig = {
I had to convert the received signature format to the one which is compatible with the serialization functions ('v' field is string in the former and number in the latter).

I don't know any better than this.

2022-02-02 10:14 UTC, fernya commented on background/services/ledger/index.ts
> +        ethersTransactionRequestFromEIP1559TransactionRequest(
Built on current foundations! :)

2022-02-02 10:32 UTC, fernya commented on background/services/signing/index.ts
> +}
No, it's a skeleton as yet (in this PR)

2022-02-02 13:01 UTC, greg-nagy approved these changes
This should be good to go 👷‍♂️

2022-02-02 13:32 UTC, merged