Typed data signing
tallycash/extension pull request #857
Opened 2022-01-20 18:40 UTC by wojciech-turek

This PR will allow signing typed data according to [EIP-712](https://eips.ethereum.org/EIPS/eip-712) standard.

New `signing` redux slice has been introduced for the purpose of UI integration.
New SignTransaction sub page has been created to display to users what are they signing.

Exmple flow:
 [EIP-2612](https://eips.ethereum.org/EIPS/eip-2612)

2022-01-24 22:27 UTC, mhluongo reviewed
Quick thoughts!

2022-01-24 22:27 UTC, mhluongo commented on background/main.ts
> +          transactionConstructionSliceEmitter.off(
This is nice.

2022-01-24 22:27 UTC, mhluongo commented on background/redux-slices/signing.ts
> +  liquidityAmount: BigNumber
We use `bigint` everywhere for `uint256`s, why the switch to `BigNumber`?

2022-01-24 22:27 UTC, mhluongo commented on background/services/internal-ethereum-provider/index.ts
> +      case "eth_signTypedData_v3":
Are we sure we shouldn't error out for any of these?

2022-01-24 22:27 UTC, mhluongo commented on background/services/provider-bridge/index.ts
> +          const walletAddress = params[0] as HexString
This is a great place to validate the data. `normalizeEVMAddress`

2022-01-27 12:53 UTC, wojciech-turek commented on background/services/internal-ethereum-provider/index.ts
> +      case "eth_signTypedData_v3":
That is a great question to which I do not have an answer yet. I will check if we can somehow be able to accept older versions and if not ill add a rejection.

I believe most of the data signing goes through v4 though?

2022-01-27 12:55 UTC, wojciech-turek commented on background/redux-slices/signing.ts
> +  liquidityAmount: BigNumber
We decided to go away from PermitRequest as a type and go with generic typed data, but I also agree that would have to be changed anyway.

2022-01-27 13:16 UTC, wojciech-turek commented on background/main.ts
> +          transactionConstructionSliceEmitter.off(
Mostly Antonio's work, I have used what he did for rejecting the signatures. Gotta give credit where credit is due :) gj @Shadowfiend

2022-01-27 14:45 UTC, greg-nagy requested changes
Left a couple of notes, the `ProviderBridgeService` changes are quite important for security. 

The rest of the comments are up to you.

2022-01-27 14:45 UTC, greg-nagy commented on background/redux-slices/signing.ts
> +      typedDataRequest: undefined,
Should the `signedTypeData` also be set to undefined here?

2022-01-27 14:45 UTC, greg-nagy commented on background/services/internal-ethereum-provider/index.ts
> +      case "eth_signTypedData_v3":
Based on what I understand from this https://docs.metamask.io/guide/signing-data.html#signing-data-with-metamask

And that EIP-712 is quite old I would think it's safe to assume that if any of these are used this is the expected behaviour. 

Don't have deep/real insight into this though.

2022-01-27 14:45 UTC, greg-nagy commented on background/services/keyring/index.ts
> +    const filteredTypes = Object.keys(types)
This is a bit complex and expensive implementation for this problem. 

```
delete types["EIP712Domain"]
```

2022-01-27 14:45 UTC, greg-nagy commented on background/services/provider-bridge/index.ts
> +        case "eth_signTypedData_v4":
Please add the rest of the signing method RPC names, otherwise those will pass this check without being validated. 

The default is to pass anything we don't specify here to the internal provider.

2022-01-27 14:45 UTC, greg-nagy commented on ui/pages/SignData.tsx
> +  if (!areKeyringsUnlocked) {
These 2 check could be merged

2022-01-27 14:45 UTC, greg-nagy commented on ui/utils/formatting.ts
> +  return s[0].toUpperCase() + s.slice(1)
JS, you always amuse me ... :(

2022-01-27 14:55 UTC, wojciech-turek commented on background/redux-slices/signing.ts
> +      typedDataRequest: undefined,
Yes, this purpose of clearing the state is to have it revert to undefined once the transaction is signed so we never accidentally load old data.

2022-01-27 15:00 UTC, wojciech-turek commented on background/services/keyring/index.ts
> +    const filteredTypes = Object.keys(types)
Oh, thanks, replaced!

2022-01-27 15:33 UTC, merged

2022-01-27 21:16 UTC, Shadowfiend commented on background/services/keyring/index.ts
> +    delete types.EIP712Domain
Just one problem here…

```
> const myTypedData = { domain: "me", types: { my: "hey", types: "hai", EIP712Domain: "me" }, message: "it's me!" }
< undefined
> function cleanUpTheTest(typedData) {
  const { domain, types, message } = typedData
  delete types["EIP712Domain"]
  return { domain, types, message }
}
< undefined
> myTypedData
< {domain: "me", types: {my: "hey", types: "hai", EIP712Domain: "me"}, message: "it's me!"}
> cleanUpTheTest(myTypedData)
< {domain: "me", types: {my: "hey", types: "hai"}, message: "it's me!"}
> myTypedData
< {domain: "me", types: {my: "hey", types: "hai"}, message: "it's me!"}
```

This modifies the original object! This means if the caller is planning on doing anything else with the typed data, it's no longer in the correct format. You'll want to copy it first:

```
    const { EIP712Domain, ...typesForSigning } = types
```

`typesForSigning` can now safely be used, and doesn't have the `EIP712Domain` property. The linter even recognizes this pattern and doesn't yell at us for not using `EIP712Domain` anywhere :wink: