Update Custom Derivation Path Design
tallycash/extension pull request #884
Opened 2022-01-24 16:40 UTC by 7alip

<img width="385" alt="tally dpath" src="https://user-images.githubusercontent.com/22167684/152254634-ee963ab6-579c-414f-ac07-93b0ba0d0389.png">

Updated custom derivation path design based on #843 
May affect #893 since `SharedSelect` design has changed

- [ ] Save custom path added by user to browser db
- [ ] No action added for `How do I find the recovery phrase?`
- [ ] Component tests
- [ ] Input Validations & Error messages
- [x] SharedModal portal
- [x] SharedSelect component

2022-01-25 20:42 UTC, henryboldi requested changes
Lookin good! 🔥👏

Still, I'd love to keep `SharedSelect` since it'll be used for most of our dropdowns and for consistency. What do you think?

2022-01-25 20:42 UTC, henryboldi commented on ui/components/Onboarding/OnboardingDerivationPathSelect.tsx
> -    <SharedSelect
Would it be possible to keep `SharedSelect`? This will be a useful component for most of our dropdowns :)

2022-01-25 20:42 UTC, henryboldi commented on ui/components/Onboarding/OnboardingDerivationPathSelect.tsx
> +        <div className="modal_content">
How about creating a `SharedModal` component for this?

2022-01-25 20:42 UTC, henryboldi commented on ui/components/Onboarding/OnboardingDerivationPathSelect.tsx
> +        <div className="modal_overlay" />
Not blocked but the hook you added, `useOnClickOutside`, could be useful here

2022-01-25 21:50 UTC, henryboldi commented
I'd also like to note that `SharedSelector` is being used in @cairomassimo's PR https://github.com/tallycash/extension/pull/893

2022-01-26 08:06 UTC, 7alip commented on ui/components/Onboarding/OnboardingDerivationPathSelect.tsx
> -    <SharedSelect
Alright! I had considered it just as a proposal as I didn't know about Vlad's design. Let's keep it then.

2022-01-26 15:55 UTC, 7alip commented on ui/components/Onboarding/OnboardingDerivationPathSelect.tsx
> -    <SharedSelect
Do you mean, should I change the `SharedSelect` component style according to @VladUXUI's design for derivation path.
Or SharedSelect will remain as it is, and derivation path select has its own uniq design?

2022-01-26 17:12 UTC, henryboldi commented on ui/components/Onboarding/OnboardingDerivationPathSelect.tsx
> -    <SharedSelect
I believe the updated design here should apply to `SharedSelect` in general. So could `OnboardingDerivationPathSelect` use `SharedSelect`?

2022-01-26 17:14 UTC, henryboldi commented on ui/components/Shared/SharedModal.tsx
> +  return createPortal(
Very nice! 🤌

2022-01-31 16:25 UTC, henryboldi commented
@7alip Thank you so much for the fantastic contribution! 💪

I'll test this later today and hopefully we can merge :)

2022-02-02 04:54 UTC, henryboldi approved these changes
Phenomenal work man!

I want to note that there's not much room for the error message. Granted, I don't think this has been accounted for in our design yet, cc @VladUXUI 

<img width="324" alt="error space" src="https://user-images.githubusercontent.com/1918798/152095076-bf264c2e-8942-4901-aff7-d580eb80235a.png">

2022-02-02 04:58 UTC, henryboldi commented
@7alip, could you sign all the commits please? 🙏

2022-02-02 08:58 UTC, VladUXUI commented
That is true, my bad for not leaving enough room for error messages.

Best case scenario would be to increase the space if helper/error text is visible (making the page scrollable)

Another solution here is to increase the spacing of the bottom elements, not the biggest fan of how squeezed everything is, but should be good for a while till we add 24w seed.

Updated Figma with the second solution if first one ain't feasible at the moment.

2022-02-02 08:58 UTC, VladUXUI commented
Also, this is looking really nice @7alip!

2022-02-02 14:42 UTC, 7alip commented
> @7alip, could you sign all the commits please? 🙏

@henryboldi, I couldn't sign the previous commits. I have rebased and committed them by signing with gpg/yubikey, but nothing changed. Is there any alternative solution?

2022-02-02 18:16 UTC, henryboldi commented
>  I have rebased and committed them by signing with gpg/yubikey, but nothing changed.

@7alip, I think you'll need to force push after rebasing? And a command like `git rebase -i --root --exec 'git commit --amend --no-edit --no-verify -S'` should work 🤞

2022-02-02 20:23 UTC, 7alip commented
> That is true, my bad for not leaving enough room for error messages.
> 
> Best case scenario would be to increase the space if helper/error text is visible (making the page scrollable)
> 
> Another solution here is to increase the spacing of the bottom elements, not the biggest fan of how squeezed everything is, but should be good for a while till we add 24w seed.
> 
> Updated Figma with the second solution if first one ain't feasible at the moment.

@VladUXUI , hope it's what you expect.
![tally](https://user-images.githubusercontent.com/22167684/152231237-250c1557-812f-4cdb-9720-a12a9c85aca4.jpeg)

2022-02-02 21:52 UTC, henryboldi approved these changes
Thank you for signing the commits. Lookin great! ❤️

2022-02-03 13:30 UTC, greg-nagy commented
Created a PR that should solve this build issue: #938

2022-02-04 10:45 UTC, cairomassimo commented
> I'd also like to note that `SharedSelector` is being used in @cairomassimo's PR #893

FYI, that was mostly a dummy, I'm now changing the code to use `OnboardingDerivationPathSelectAlt` instead.

2022-02-04 16:27 UTC, henryboldi commented
@7alip, thank you for your patience here! 🙇 We're trying to solve the external build error issue soon. cc @greg

2022-02-05 02:31 UTC, Shadowfiend commented
Once more with feeling.

2022-02-05 06:21 UTC, merged