Add UI to import accounts from Ledger (wired to Redux but not actual services)
tallycash/extension pull request #893
Opened 2022-01-25 12:41 UTC by cairomassimo

Closes #850, closes #851, closes #852.

2022-01-25 16:57 UTC, greg-nagy requested changes
First changes, that we talked through in the PR call.

2022-01-25 16:57 UTC, greg-nagy commented on background/redux-slices/ledger-import.ts
> +  nonce: 0,
Instead of nonce we should keep track of ledgers by `ledgerID`

2022-01-25 16:57 UTC, greg-nagy commented on background/redux-slices/ledger-import.ts
> +  accounts: [],
Maybe use object instead of an array, that could clean up the logic.

2022-01-25 16:57 UTC, greg-nagy commented on background/redux-slices/ledger-import.ts
> +export const initialState: LedgerImportState = {
Change this data structure to be able to handle multiple ledgers. A main object with `ledgerID` as key, and all the ledger info here should be populated under that key. 

As a next step `nonce` could be used as `ledgerID`, then we can swap that to proper `ledgerID`

2022-01-25 16:57 UTC, greg-nagy commented on background/redux-slices/ledger-import.ts
> +import { createSlice } from "@reduxjs/toolkit"
We should rename this to `ledger.ts` and the name of the slice should also be `ledger`

2022-01-25 21:48 UTC, henryboldi submitted a review, later dismissed

2022-01-25 21:48 UTC, henryboldi commented on ui/pages/Ledger/Ledger.tsx
> +              /* Allow some time to react to clicks before changing the UI. */
Why? The additional 100ms isn't so perceptible

2022-01-25 21:48 UTC, henryboldi commented on ui/components/Ledger/LedgerContinueButton.tsx
> +export default function LedgerContinueButton({
If the only thing that's unique about this button is that its full width to its parent, is it worth creating a new component vs. `SharedButton`?

2022-01-25 21:48 UTC, henryboldi commented on ui/components/Ledger/LedgerContinueButton.tsx
> +          font-style: normal;
`font-style: normal;` is the default

2022-01-25 21:48 UTC, henryboldi commented on ui/components/Ledger/LedgerImportDoneScreen.tsx
> +            iconPosition="left"
Based on the design,

```suggestion
            iconPosition="right"
```

2022-01-26 09:25 UTC, cairomassimo commented on ui/components/Ledger/LedgerContinueButton.tsx
> +export default function LedgerContinueButton({
Good point. I didn't do it just yet, for the following reason.

I think it's not great when a shared component has (too many) props that control its style. IMHO it would be better if we could just style it from outside, with custom CSS and/or reusing CSS fragments. (This is especially true for shared buttons, which in most cases are just shared CSS, but partially applies also to other components such as `SharedSelect`.) However, I'm not sure what is the correct way to do this with the `<style jsx>` syntax...

For the moment, I could just patch `SharedButton` and add a new prop (e.g. `fullWidth`) for this use case.
Otherwise, we could also start sharing the CSS fragments for buttons (how?) and moving towards my approach, if you like it, or perhaps allow custom CSS to be applied to shared components from outside (how?) which is a kind of compromise. Let me know!

2022-01-26 09:26 UTC, cairomassimo commented
Thanks for the great comments @greg-nagy and @henryboldi !
I should have addressed all of them (except the one comment above), but another review pass is probably due.

2022-01-26 14:24 UTC, greg-nagy approved these changes
This PR should be good to go. Very well done. 

Not like a steak, because that's horible when well done. 

🥩

2022-01-26 14:24 UTC, greg-nagy commented on ui/pages/Ledger/Ledger.tsx
> +  const device = deviceID === null ? null : devices[deviceID] ?? null
The ternary check is not necessary here.

2022-01-26 14:24 UTC, greg-nagy commented on ui/pages/Tab.tsx
> +        {/* HashRouter seems the only choice supporting safe page reloads. */}
❗️

2022-01-26 14:26 UTC, merged

2022-01-26 17:20 UTC, henryboldi commented on ui/components/Ledger/LedgerContinueButton.tsx
> +export default function LedgerContinueButton({
How about adding a `style` prop to `SharedButton` which can handle these edge cases?

2022-01-31 20:56 UTC, henryboldi commented on ui/public/index.css
> -  height: 594px;
I believe removing `width` and `height` here is causing a flash of a smaller size when opening the extension. Not a huge deal but worth noting.

Issue added here → https://github.com/tallycash/extension/issues/924