Fee-d me: Finish restructuring fee selector for reuse in swaps
tallycash/extension pull request #922
Opened 2022-01-31 15:40 UTC by Shadowfiend

There are a few changes here, but going to pull the commit message from
the big commit as it's the core of the work:

-----

This is hopefully the last in a series of refactors of network setting
components for reusability in swaps and elsewhere. The key changes here
are:

- `NetworkSettingsSelect` is now strictly the rendered set of components
  that allow manipulating a NetworkFeeSettings object. This means that
  it interacts with its parent components entirely through a
  networkSettings prop and onNetworkSettingsChange prop, with the latter
  expected to update the former's state in the parent component.
  Estimated fees per gas are _currently_ still passed by the parent
  component. The component now includes the network fee update countdown
  timer.
- `NetworkSetttingsChooser` now manages only the display of the
  `NetworkSettingsSelect` and an associated `Save` button, which is used
  to persist fee type across the extension, as well as signal to the
  parent component that the network settings have been saved.
- Initial network fee settings for a chooser are provided by a new
  selector, `selectDefaultNetworkFeeSetings`.
- `SwapSettingsChooser` for now simply updates its usage of
  `NetworkSettingsSelect`; further rework is coming.

Additionally, the way that the main currency amount for gas options is
computed in `NetworkSettingsSelect` has been updated, leaning on
existing code in `enrichAssetAmountWithMainCurrencyValues` to limit the
number of places asset conversion code is managed.

-----

Send ETH and dApp signing are the primary consumers of network settings
right now,  so for testing, please double-check me that both of these work.
The sign transaction page's network settings are now propagating gas price
changes, which was not previously happening, so it's worth double-checking
that's behaving as expected.

2022-02-01 18:20 UTC, wojciech-turek approved these changes
The code changes are very useful and this PR is definitely a step towards correct direction, I will dare to say the era of restructuring fee settings is nearing towards the end.

I have manually tested as well and works great.
Lets ship it!

2022-02-01 18:20 UTC, wojciech-turek commented on ui/components/NetworkFees/NetworkSettingsChooser.tsx
> -  const [selectedSetting, setSelectedSetting] = useState({
I applaud changes in this component.

2022-02-01 18:20 UTC, wojciech-turek commented on ui/components/NetworkFees/NetworkSettingsSelect.tsx
> +      : undefined
![image](https://user-images.githubusercontent.com/61434499/152025998-cc5d5589-f0f5-4499-a268-3a575672a1c7.png)

2022-02-01 18:25 UTC, Shadowfiend commented on background/redux-slices/selectors/accountsSelectors.ts
> -    return undefined
The goal here wasn't removing the transformation, but rather reusing the existing work done in `enrichAssetAmountWithMainCurrencyValues`. Unfortunately that note is buried in the tail end of the commit message at https://github.com/tallycash/extension/commit/614f492b2ce72d0c2fd3e483ebe3b576356fc8ad#diff-b9f5cc466dc0aa4f504e2fcc6d69cb012e2a325efbbea8699fb944ce285f9301 .

In general, we should be leaning on the enrich* helpers for asset amounts and decimal amounts when dealing with asset amounts. They handle conversions, user preferences, unit prices, etc, in one place.

2022-02-01 18:26 UTC, Shadowfiend commented on background/redux-slices/transaction-construction.ts
> +} from "../constants/network-fees"
*In principle*, kebab-case anywhere that doesn't cause syntax errors.

In practice, we try to lightly follow existing standard practices when interacting with certain libraries. This is the reason why React components are CapsCamelCased and selector files are fileSelector. From a filename perspective, these should really be the only exception; anything else should be kebab-cased. I'm not even sure about the selector files tbh, just didn't have time to think about it too hard.

2022-02-01 18:29 UTC, Shadowfiend commented on background/redux-slices/transaction-construction.ts
> +
I named it this way because it's the default from the user's perspective; i.e., what will be selected if they don't interact with the fee selection UI. That said, I see what you mean and agree `selectCurrentNetworkFeeSettings` might be clearer here... Or perhaps `selectLatestNetworkFeeSettings`/`selectSavedNetworkFeeSettings`.

2022-02-01 18:29 UTC, wojciech-turek commented on background/redux-slices/selectors/accountsSelectors.ts
> -    return undefined
Fantastic, thanks!

2022-02-01 18:51 UTC, mhluongo commented on background/redux-slices/transaction-construction.ts
> +} from "../constants/network-fees"
:raised_hand_with_fingers_splayed: I vote we kill the selector kebab-casing :blush:

2022-02-01 22:16 UTC, Shadowfiend commented on background/redux-slices/transaction-construction.ts
> +} from "../constants/network-fees"
Kill the selector file camel-casing you mean?

2022-02-02 11:00 UTC, wojciech-turek requested changes
These seems to be a blocker for this PR.

There is a setState loop in the `EstimateRefreshCountdownDivider`
![image](https://user-images.githubusercontent.com/61434499/152140383-ebbf9721-af06-42e8-b8c7-346fb1176e5b.png)

I have tested the dApp transaction and the gasOptions are updating correctly.

2022-02-03 03:29 UTC, Shadowfiend commented
Derp. Must have missed that log when I was testing. I've pushed a fix—turns out the issue was higher up in `NetworkSettingsSelect`.

2022-02-03 15:30 UTC, merged