Fix Ledger UI bugs
tallycash/extension pull request #993
Opened 2022-02-14 19:46 UTC by fernya

During QA we'll find many small bugs in displaying the current state. Let's squash them here!

2022-02-15 13:39 UTC, cairomassimo commented on ui/pages/Ledger/Ledger.tsx
> +          reloadTimeMs="15000"
I'd rather put a "Reload" or "Start from the beginning" button here, instead of a timer. What do you think about it @VladUXUI ? (This happens if there is an error while connecting to a Ledger to import accounts)

2022-02-15 16:36 UTC, VladUXUI commented on ui/pages/Ledger/Ledger.tsx
> +          reloadTimeMs="15000"
Not sure i totally understand were this would be? what page are we talking about?

2022-02-15 19:12 UTC, fernya commented on ui/pages/Ledger/Ledger.tsx
> +          reloadTimeMs="15000"
@VladUXUI 

When something goes wrong here (eg no Ledger connected, user clicks on cancel etc.)
<img width="1339" alt="image" src="https://user-images.githubusercontent.com/499307/154132011-62db90c2-faed-4e1b-a77d-63f350bed237.png">

We're showing an error page like this:
<img width="1339" alt="image" src="https://user-images.githubusercontent.com/499307/154131954-11850ca9-df33-41a7-ab61-936628d5ecdc.png">

2022-02-18 21:49 UTC, fernya commented
I've restructured the flow as we agreed upon with @VladUXUI in https://github.com/tallycash/extension/issues/984

It is similar that @cairomassimo proposed here.

2022-02-21 10:00 UTC, cairomassimo requested changes
Minor code style issues, and I'm not sure that all error states are handled correctly.
Let's fix the code style first, and then we can make sure that the error states are handled properly (I haven't tested this yet).

2022-02-22 10:43 UTC, fernya commented on ui/pages/Ledger/Ledger.tsx
> +
Got rid of it, thanks!

2022-02-22 10:44 UTC, fernya commented on ui/pages/Ledger/Ledger.tsx
> +              rejected = true
Giant :facepalm: award unlocked for me!

2022-02-22 10:44 UTC, fernya commented on ui/pages/Ledger/Ledger.tsx
> +            } else {
Got it, thanks!

2022-02-23 08:49 UTC, VladUXUI commented
<img width="521" alt="image" src="https://user-images.githubusercontent.com/80846886/155286633-b10af51a-30e5-4ef8-b396-4af0b203e376.png">

As a bit of an update, let's add this in there if we can(same design as the referral page) @cairomassimo 

[Figma Link](https://www.figma.com/file/q8gfu9XTbYBF07KMnDCtsD/UI---Dark?node-id=6062%3A150919)

2022-02-23 09:01 UTC, VladUXUI commented
<img width="604" alt="image" src="https://user-images.githubusercontent.com/80846886/155288013-83c67bc2-e61e-4617-a76d-86ed0470ff85.png">
On another note, let's please add the "I Don't see my device" button back. For now let's point it back to the steps page.

Reason for this is, that if i don't see my device there, i don't know what to do. Clicking cancel is not really what users want to do, they want to move forward but don't know how. For now we are going to assume they didn't take the correct steps

2022-02-23 14:36 UTC, cairomassimo approved these changes

2022-02-23 14:36 UTC, merged